#+title:      keller
#+date:       [2023-12-29 Fri 09:35]
#+filetags:   :casenotes:
#+identifier: 20231229T093527

Counsel for Defendants: [[https://www.gabar.org/MemberSearchDetail.cfm?ID=MjYxMTYx][Alex McDonald, Swift Currie McGhee & Heirs LLP]]]

LI: 3250000.00 Farmers 
UM: 1000000.00 Central Mutual 

Medical: 99,475.28

Migraines (neck trauma?), lower back pain radiates, leg weakness, epidurals, nerve block, dry needling, meds (Lyrica, Tramadol), kids in the car. Talking about device, surgery. We sent her to a different neuro. Both were insured through work. UM out on Yarb.  Per SKL: "We need to push the mediation out until spring, so that we have a better picture of what needs to be done in this case. It may be that we will have to dismiss this case without prejudice, and bring it back in order to get more time." 3MM UMBRELLA ON LI SIDE Per SKL client TBI headaches, hearing, memory, obgyn, big brain. sent to Weber (Neuro) and Combier for review. Medicaid.  Birthday, winery, not drinking, just turned in front, clear liability. No conversations with my client. Disinterested witness with dashcam, willing to talk. Might have. His client has video going around car.  Olivia 414877580 SSN 770-314-7823 ATT Jason Wilson Father 4045975286 No service defense per Wysocki, DOL 2020-11-24 Per Wysocki, this is really a damages case, regardless of what Olivia says. Liability not an issue.  Discovery ran 3/6 --> D depos done, set up Zoom with other P, fu Pl depo, get medical in order wages: NO lost income 
