920 7440 0590
168932

* Bobby Anderson

This is the deposition of Bobby Anderson, taken pursuant to notice and agreement of counsel under the Georgia Civil Practice Act for all allowable purposes, including discovery and cross-examination, with the understanding both that objections will be reserved until the first lawful use of the transcript and that the witness may be sworn remotely in this videoconference deposition. Are these counsel's understanding as well?

Signature?

Swear the witness.

Mr. Anderson, you are under oath, and you understand what it means to be under oath, correct?

And you are in reasonably good health and able to give me truthful and accurate testimony today?

Were you employed by the Jim Hardman Buick dealership in December of 2019?

Are you still?

Your employer is technically Jim Hardman Buick GMC, Inc., correct?

Is that what it says on your paychecks?

Do you mind if I just say the dealership?

Who do you report to, who's your boss?

Who is Mr. Hardman, what's his role?

What are your duties?

How about in December of 2019?

How long have you worked at the dealership?

What did you do before that?

What's your highest level of education? Where and when?

Do you have any family or social connections in Hall County, where this lawsuit is pending? 

Let's get right to it. Were you working the day my client fell, yes?

Walk me through what happened.

Did you create an accident or incident report of any type?

Was there any policy at the dealership regarding response to slip and fall or trip and fall incidents? Incidents in genera?

Did you actually see my client fall? How were you informed? Where were you standing?

Witnesses, during or after.

Tell me about the area where my client fell.

Ever see anyone else trip or fall there?

Was it wet on the day my client fell?

Could it have been slippery for some reason?

Who did you talk to about the fall that day?

Emergency response?

Any other witnesses?

Did people often step over that curb?

Was it permitted?

Any marking to suggest that she should have walked a different way?

What are the dealership's policies regarding prevention of falls?

How are the communicated to employees?

What about cleaning policies? Wet floors?

Are you the person who is supposed to be keeping an eye out for slip and fall hazards?

How do you go about doing that?

Did you miss anything that day?

If there was no hazard, how do you think my client fell?

Did you clean up anything after my client fell?

Later on, have you or the dealership changed anything about that walkway? 

Do you recall any other falls at the restaurant?

Did you take any pictures? That day?

Are there any video cameras in that area?

Are you aware of any documentation regarding this fall?

How about photos?

Did you review any documents to prepare for your deposition today?

Have you ever been arrested?

Have you ever been convicted of a crime?

Have you ever been bankrupt?

Do you think you've understood my questions today?

Have you given me truthful, accurate, and complete testimony today?

Have you left anything out?

Is there anything relevant to this case that we haven't thought about, that you think a jury might want to know in deciding whether VJM is liable to my client?

* Jim Hardman

This is the deposition of James Hardman, taken pursuant to notice and agreement of counsel under the Georgia Civil Practice Act for all allowable purposes, including discovery and cross-examination, with the understanding both that objections will be reserved until the first lawful use of the transcript and that the witness may be sworn remotely in this videoconference deposition. Are these counsel's understanding as well?

Signature?

Please swear the witness.

** Introduction

Good morning, Mr. Hardma. My name is Paul Menair and I represent the plaintiff in a lawsuit against three business entities, Jim Hardman Autos, Inc., Jim Hardman Buick GMC, Inc., and Atlantic Leasing, LLC.

You have a relationship with all three of these entities, correct?

This deposition has been noticed as a deposition of you individuall, and also as a rule 30b6 deposition Jim Hardman Buick GMC, Inc., which means that during part of the deposition, and I'll try to make this clear, I will be asking you to testify on behalf of Jim Hardman Buick GMC, Inc. and not you individuallly. Do you understand that distinction?

So just so we're clear, if I ask you to testify on behalf of "the company," or "the dealership," I mean Jim Hardman Buick GMC, Inc., and if I ask you about either of the other companies, I'm asking you personally what you know about those companies, but you are not testifying on their behalf, okay?

If there is ever any confusion in you mind as to what I mean, and that's entirely possible because I don't always ask perfect questions, please let me know you don't understand and ask me to rephrase, okay?

If you do answer a question, I will assume you thought about the question and are giving me a truthful and complete response to the question I asked, okay?

If you need to take a break at any time, please let me know, and all I will ask is that you give me an answer to any question that's already been asked before we go on mute, sound fair?

Finally, if I ask you to restate an answer because I'm not sure it was clear, I'm just trying to help the court reporter make an accurate verbatim transcript of what we say, it's nothing personal.

Are you ready?

Is there anything that might interfere with your ability to give me truthful and complete responses to my questions today, like an illness or some sort of medication you are on?

Please state your full name for the record.

** Background

We'll start with some questions I have for you personally, not the company.

What is your date of birth?

Could you tell me what your physical address is?

Do you have any relatives in Hall County, Georgia?

Do you have any social connections in Hall County, like a church or rotary club membership, anything that would connect you to someone who might show up to serve on a jury in Hall? 

Where did you go to high school?

Did you graduate? What year?

Any college? Where? Degree?

Walk me quickly through your work experience.

** JHB - General

So let's talk about the three companies in general first, and again these questions are for you as an individual.

First, tell me about Atlantic Leasing, LLC.

Fair to characterize Atlantic Leasing as a company set up to own property, separate from the operating entities?

According to the Georgia Secretary of State, it was originally set up as a corporation but converted to an LLC in 2007, is that correct?

Looks like you are the manager of that entity, correct?

Are their any officers?

Who are the members?

Does the company have any employees?

What properties does it own?

Business address is 1592 Browns Bridge in Gainesville, yes?

Does Atlantic Leasing engage in any business other than purchasing property and leasing it to your dealership?

Let's talk about Jim Hardman Autos and Jim Hardman Buick GMC.

Both business corporations, yes?

Looks like Jim Hardman Autos was the original company formed in 1979, and you originally had a location at 1121 West Broad.

Why maintain two corporations?

You are CEO, CFO, and Secretary of both?

Any other officers?

I assume you're a shareholder as well.

Are there any other shareholders of these entities?

Directors?

What does your work entail on a day to day basis.

Do you have any locations where you work other than 1592 Browns Bridge.

How many folks report to you directly?

Are they all employees of JHBGMC?

Do you have any other companies that you operate?

** 30b6

Okay, now I'm going to ask you to switch hats and testify on behalf of JHB.

To start, I'll ask if you met with anyone to prepare for today's deposition, and to be clear, I want to know if there was a meeting, but not anything that your lawyer might have said to you by way of legal advice, that's none of my business.

Can you tell me who was at the meeting, again without telling me anything about what was said.

Did you review any documents to prepare for today's deposition, at that meeting or on any occasion?

If you would, please look at Plaintiff's Exhibit 1 to this deposition.

Are you familiar with this document?

Please take a look at the list of topics on page 2.

Are you prepared to testify regarding these topics?

Are you the person best qualified to testify on these topics on behalf of the company?

Are you authorized by the company to testify on its behalf as to these topics?

Thank you.

Let's now take a look at Exhibit 2, which is the answer of all three of the defendants in this action.

Have you seen this document before?

I'd like to direct your attention to the Second Defense, and please understand, I realize you're not a lawyer. Basically, though, this says that the entity Jim Hardman Autos, Inc. is not properly named as a defendant, and that could mean a number of different things. Can you tell me, on behalf of the company, what that means?

Jim Hardman Autos, Inc. is correctly named, in the sense that this is its correct legal name, yes?

So, fair to say what this means is that Jim Hardman Autos, Inc. had nothing to do with day to day operations at the dealership, so it can't be liable in this lawsuit, yes?

The rest of the defenses, if you'll just look through them, these are what lawyers call affirmative defenses.

Without getting too far into the weeds, I'll represent I understand these affirmative defenses to mean that other folks, not the company, are at least partially responsible for my client's fall, including my client.

And it's understandable, as in any slip and fall, that the company might allege that my client was at least partly responsible for her own fall.

What I'm wondering, and I'd like you to tell me on behalf of the company, is the company aware of any person or entity other than my client who might be partially responsible for her fall?

Let's look at Plaintiff's 3.

These are responses to what lawyers call requests for admissions.

Are you familiar with this document?

Did you assist with preparing it?

Look at 8.

The company, Jim Hardman Buick GMC, is the entity that operated the dealership where my client fell.

Any other companies operating out of the dealership?

So Atlantic Leasing owns the property, Jim Hardman Buick GMC operates the dealership, and Jim Hardman Autos is out of the picture.

And if we look at 9 and 10, at the time of the fall, the business was open, and the company has no reason to think my client was there for any other purpose but to do business with the dealership, fair?

So number 11 is going to require a little explanation. You deny that the company had custody and control of the premises, subject to the objection that the question was allegedly vague and ambiguous. Given the company understood this question well enough to deny it, I'm wondering what the basis was for the denial.

Who had custody of the premises?

Were there any other persons or entities with a leasehold interest in this property?

Who had control of the premises?

Who paid to insure it? Who hired people to clean it? If someone was trespassing, who had a right to call law enforcement to have them removed?

Let's look at 12, which denies a duty to inspect for and mitigate hazards?

Did the company run a business at the premises where my client fell?

Did any other company occupy those premises?

Did the company have an obligation to at least use ordinary care try to keep the premises safe for people who might visit to do business with the company?

Fair to say this denial might simply mean that the company might not be able to mitigate any conceivable hazard?

Any other basis for this denial that the company is aware of?

You'll agree that safety is important when you keep premises that are open to the public?

Let's look at Ex. 4

Familiar with this?

Did you assist in preparing this?

I don't think we ever got what's called a verification of these answers, but if there was someone to verify that these are true and correct, would that be you?

Could to talk with your lawyer about providing a verification?

Let's look at 1.

This is a list of witnesses, and I'm going to ask some follow up questions about these folks if you don't mind.

James Robert "Bobby" Anderson.

You heard his testimony today, yes?

Is there anything that he knows relevant to this case that I didn't ask him about?

We'll get back you your personal knowledge about this incident in a bit.

Next you list Michele Foitle and Tom Rumble, who are insurance company personnel.

What do they know relevant to this case?

Are these folks that might be called upon to testify at trial?

They are not employees of any of the companies that are defendants in this case, right?

Any objection to our deposing these folks?

Mr. Rumble prepared a report, but that was not produced, correct?

Do you know where Mr. Rumble is located?

Mr. Rumble took all 16 of the photographs that were produced by y'all?

Who was present when those photographs were taken?

Do you know how it was determined that was the area where my client fell?

Let's put those into evidence as a collective Exhibit, call it Ex. 5.

These are the photographs we were just talking about yes?

Do they truly and accurately depict the area at the dealership where the company believes my client fell?

And do they truly and accurately depict that area in its condition at the time Mr. Rumble investigated this matter and took those photographs?

And, again, you were there when these were taken? Who else was present?

While we're at it, let's mark Ex. 6

This appears to me to be a least agreement between Atlantic Leasing LLC and the operating company, yes?

Is it complete, except for some minor redactions?

These are your signatures on the last page?

This was the lease in effect at the time of my client's fall in December of 2019.

And this governs the relationship between Atlantic Leasing and the dealership regarding the premises where my client fell.

And there were no other persons or entities leasing the premises at 1592 Browns Bridge Road in Gainesville at the time my client fell.

Look at 15.

Are you, sitting here today, aware of any persons or entities that were responsible for cleaning or maintenance at the dealership?

Do you hire folks to do any of that?

Who cleans the parking lot?

Who maintains the parking lot?

Does anyone look at the parking lot on a daily basis for slip or trip hazards, like trash, oil spills, anything of that nature?

Are there video cameras?

Any video monitoring of the area where my client fell?

Is there any video of my client's actual fall? why not?

Look at 19.

You've never had a trip and fall or slip and fall at the dealership?

Not even one that didn't result in a lawsuit?

Employees? I'm asking specifically about falls?

Ever call an ambulance because someone fell, that you're aware of?

Let's look again at those photographs.

On the third page, how do y'all know this is where my client parked.

Let's look at the 10th page.

This looks like you are alleging that the curb height where you believe my client fell was about 2 inches, fair?

It is fairly uniform there, or does it get shorter or higher in places?

Does the company believe this is an appropriate curb height?

Do you happen to have an opinion about what the relevant building and safety codes might say?

Next picture appears to show a measurement of the striping, any idea what that tells us?

And then there is a series that seems to show the depth of the sidewalk? Fair?

Can you tell me why that's important?

Was this parking lot and this curb in place before you opened a dealership there, or did your company build this out?

Has the parking lot ever been repaved? Did that change the curb height?

So this curb is not as high as it once was.

But the company still takes the position that the height is appropriate, legal, and safe.

And you are not aware of anyone ever tripping over this curb.

Is this an area where you would expect customers to be walking, and specifically stepping over that curb?

Were they permitted to do so?

Any way of letting them know there was a different path they were supposed to take?

How many times a day would you say people step over that curb?

And there are no warning signs saying watch your step or anything to that effect?

And the curb itself is not painted.

The company has no video of my client's fall.

There would have been video at the time.

Did anyone decide not to preserve the video, for whatever reason?

Was the company aware of the potential for litigation around the time of my client's fall?

The company has no contemporaneous incident reports or records documenting the fall.

Does the company have any policies and procedures in place regarding documenting accidents such as slip and falls.

Now, I don't want to know anything about correspondence with your attorney, but were reports or any written documents at all generated in response to this incident that are maintained in the dealership's files or in your own personal files?

Did anyone notify the company's insurance carrier? When?

Did anyone give a recorded statement?

Does the company have any written policies about fall prevention?

How about unwritten policies? How communicated?

Who was responsible for cleaning outside? How conducted, how often?

Did the company ever have any safety inspections? Time it was built to present?

Insurance audits for safety?

Anyone ever flag that curb as an issue?

Have any changes been made to the curb since my client fell.

** Incident

All right, so I've been asking you questions in your capacity as a corporate representative, and I want you now to change hats again so we can talk about your personal knowledge

How did you find out about the incident where my client fell? {Details}

Were you there that day?

What did he say, exactly? {Details}

Have you talked to anyone else about this fall, other than your lawyers and the insurance company representatives we've discussed?

Have you ever talked to my client or her husband?

Do you personally know anything about my client's injuries, from any source, other than what you might have heard from your attorney, which I don't want to know about.

What did Mr. Anderson tell you about my client's injuries, or lack thereof?

Anyone else?

Have you put anything in writing about the fall anywhere? Including social media?

Are you aware of anything in writing, like in a memorandum or on social media, other than what we've looked at?

What do you believe caused my client to fall?

What do you base that belief on?

Is there anything you can think of that could have been done by your employees to prevent my client's fall?

Anyone else who could have prevented the fall?

In your opinion, was my client solely responsible?

** Personal

Have you ever been arrested?

Have you ever been convicted of a crime?

Have you ever been bankrupt?

Do you think you've understood my questions today?

Have you given me truthful, accurate, and complete testimony today?

Have you left anything out?

Is there anything relevant to this case that we haven't thought about, that you think a jury might want to know in deciding whether the dealership is liable to my client?

** Thank You

