* Beck Complaint

IN THE SUPERIOR COURT OF WHITE COUNTY
STATE OF GEORGIA

SARAH BELL,

Plaintiff,

v.

KASEY LEEANN CHRISTOPER and
MONDAY'S, LLC, d/b/a MONDAY'S
PUB,

Defendants.

JURY TRIAL DEMANDED

COMPLAINT

COMES NOW the above Plaintiff and files her Complaint, showing the following:

Jurisdiction and Venue

x. This is an action for money damages arising from a traffic collision.

x. Plaintiff Sarah Bell ("Bell") is a citizen of the State of Georgia submitting herself hereby to the jurisdiction and venue of this Court.

x. Defendant Kasey Leeann Christopher ("Christopher") may be served with summons and complaint in this matter at her residence, 54 Bake Shop Lane, Cleveland, White County, Georgia 30528.

x. Defendant Monday's, LLC, d/b/a Monday's Pub ("Monday's") is a domestic limited liability company with its principal place of business and registered office located at 205 Putnam Road, Cleveland, White County, Georgia 30528, and it may be served with summons and complaint in this action by its registered agent, Donald Monday, at that address.

x. Venue is proper in White County pursuant to Ga. Const. Art. VI, Sec. II, Para. IV and VI; OCGA §§ 14-11-1108, 14-2-510(b)(1) and (3).

Facts Common to All Counts

x. On August 17, 2021, Christopher was a patron at the business premises of Monday's, located at 7934 S. Main St., Helen, White County, Georgia 30345.

x. Christopher consumed alcohol at Mondays that was sold and served to him by Monday's, its employees or agents, until and after she was noticeably intoxicated, despite the fact that they knew or should have known that Christopher would be operating a motor vehicle.

x. Christopher left Monday's, noticeably intoxicated, and operated a motor vehicle, specifically a 1990 Lexus LS400.

x. While driving southbound on State Route 17, attempting to navigate a curve, Christopher failed to maintain her lane and collided with a vehicle, specifically a 2014 Kia Sorento, operated by Zoey Abigail Thomason ("Thomason").

x. Bell was a passenger in Thomason's vehicle.

x. Bell suffered personal injuries in said collision.

x. The responding officers issued Christopher citations for violations of OCGA §§ 40-6-48 (Failure to Maintain Lane) and 40-6-391(a)(1-5) (Driving Under the Influence of Alcohol, Drugs, or Other Intoxicating Substances).

x. Christopher entered a plea of guilty to said offenses in the Probate Court of White County, Georgia.

COUNT I - Negligence and Negligence Per Se (Christopher)

x. On August 17, 2021, Christopher had a duty to operate her motor vehicle with due care and regard for other vehicles, and in compliance with Georgia law.

x. Christopher breached said duty or duties by, without limitation, failing to maintain her lane and operating under the influence of alcohol and/or other intoxicating substances, which breach of duties constituted negligence or negligence per se.

x. As a direct and proximate consequence of Christopher's breach of duty, Bell suffered personal injuries, and Christopher should be held liable to pay damages, including, without limitation, special damages in the form of medical expenses in the amount of at least $11,889.69 and general damages for her pain, suffering, and emotional distress in an amount to be determined at trial by the enlightened conscience of an impartial jury.

COUNT II - Negligence and Negligence Per Se ("Monday's")

x. On August 17, 2021, Monday's and its employees or agents had a duty to operate its business with due care and in compliance with Georgia law.

x. Monday's employees breached said duty or duties of care by serving alcohol to Christopher when she was visibly intoxicated and its employees or agents knew or should have known that she would be operating a motor vehicle.

x. Monday's should be held vicariously liable for the negligence of its employees or agents.

x. Monday's should also be held directly liable for having negligently hired, trained, supervised, and retained its employees or agents.

x. As a direct and proximate consequence of the above described negligent conduct, Bell suffered personal injuries, and Monday's should be held liable to pay damages, including, without limitation, special damages in the form of medical expenses in the amount of at least $11,889.69 and general damages for her pain, suffering, and emotional distress in an amount to be determined at trial by the enlightened conscience of an impartial jury.

COUNT III - Punitive Damages (all defendants)

x. Christopher and Monday's were willful, reckless, and wanton, showing that entire want of care that would raise the presumption of conscious indifference to the consequences of their conduct.

x. Said conduct proximately caused injury to Bell, and Christopher and Monday's should, accordingly, be held liable to pay punitive damages pursuant to OCGA § 51-12-5.1.

WHEREFORE, Plaintiff respectfully prays that summons issue and be served with the foregoing complaint as provided by law, that six months of discovery be had, that the matter be tried to a jury, that the Court enter judgment in favor of Plaintiff and against Defendants, that the costs of the action be cast upon the Defendants, and that the Court grant such other and further relief as it deems proper and just.
