* Brackett, Mercades

** Autopsy

Requested 2020-08-25
Report generated 2020-09-15
Department of Forensic Services No. 2020-1020047
Toxicology 2020-08-10: Positive THC and alprazolamn, negative opiods
Autopsy 2020-08-7: Ruptured spleen

** ORR

### White County 2021-01-25

All records, no response on file

### White County 2021-03-17

Request for K with medical, response provided same day, CorrectHealth White, LLC, GCH maintains 3MM insurance, indemnifies county for negligence.

### Gainesville PD 2021-04-14

Response promised, check requested, BP following up.

### GBI 2021-04-13

No documents provided per open investigation as of 2021-04-23

### Hall County 2021-02-16

Request made for "entire investigative file," they produced the next day a single sheet showing a booking number an log showing transfer to White County "For Other Agency."

## NEGMC

No dates of service for month or so prior.

Hall SO OR

AXON_Body_2_Video_2020-08-05_1905.mp4

Picking her up - they were looking for a guy at her house, called her in and ended up picking her up on a probation violation warrant out of White County.

I've got a broken rib but it ain't from him, him hitting me didn't help - 16:30
I've been throwing up, broken rib, etc. - 21:00
Can't breath when I'm trying to sleep, can't even go out to get a pack of cigarettes - 23:30

Mercedes_Brackett.mp4

Bruising at handoff, she was good until I said she had a warrant - 25:00


[[ESTATE???}}

** Ante-Litem

   OCGA § 36-11-1 Sufficient to County Atty? 301 Ga. 380
   Applies to Sheriff Davis v. Morrison, 344 Ga. App. 527, 532, 810 S.E.2d 649, 653 (2018); Columbia Cty. v. Branton, 304 Ga. App. 149, 151, 695 S.E.2d 674, 677 (2010), overruled in part on other grounds by Harrison v. McAfee, 338 Ga. App. 393, 788 S.E.2d 872 (2016); see alsoCameron v. Lang, 274 Ga. 122, 126, 549 S.E.2d 341, 346 (2001) (“Suits against public employees in their official capacities are in reality suits against the state and, therefore, involve sovereign immunity.” (quotation marksomitted)) (citation omitted)

   The whole Sheriff v. County thing is super dumb as set forth in detail in Mendez v. Moats, 310 Ga. 114 (Ga. 2020) (Nahmias, concurring)...

   Rick Kelly, Sheriff
   White County Sheriff's Office
   1210 Hulsey Road
   Cleveland, Georgia 30528

   Travis Turner, Chairman
   White County Board of Commissioners
   1235 Helen Highway
   Cleveland, Georgia 30528

   Jason Cobb, County Manager
   White County
   1235 Helen Highway
   Cleveland, Georgia 30528

   Mary Jane Henneke, County Attorney
   White County
   210 Washington Street, Suite 208
   PO Box 3157
   Gainesville, GA 30503

   --- {two separate letters}
   
   Gerald Couch, Sheriff
   Hall County Sheriff's Office
   2859 Browns Bridge Road
   Gainesville, Georgia 30504

   Richard Higgins, Chairman
   Hall County Board of Commissioners
   2875 Browns Bridge Road
   Gainesville, GA 30504-5635

   Jock Connell, County Administrator
   Hall County
   2875 Browns Bridge Road
   Gainesville, GA 30504-5635
   
   Van Stephens, County Attorney
   Hall County
   2875 Browns Bridge Road
   Gainesville, GA 30504-5635
   
Dear Sirs{ and Madam},

I have the honor of representing Janet Denise Brackett, the mother of Mercedes Brackett, who passed away on August 7, 2020 while in the custody of the White County Sheriff's Office at the White County Jail, following transfer from Hall to White County custody. Ms. Brackett made numerous complaints while in the custody of both agencies that should have led to arrangements being made for an immediate and more thorough medical evaluation than was routinely conducted on her arrival at the jail, which would have diagnosed her with a medical condition that was survivable with treatment. Instead, the deputies and other agents of both Sheriff's Offices failed to provide her with appropriate treatment, and that failure was the direct and proximate cause of her avoidable death.

Although the Georgia Bureau of Investigations conducted a thorough investigation of this matter and ultimately determined that criminal charges should not be pursued in the case, the agencies can and should be held civilly liable for their failure to provide appropriate medical treatment to Mercedes, a violation of her rights under the Eighth Amendment to the Constitution of the United States of America, as well as similar provisions of Georgia statutory and constitutional law, which mandate the provision of adequate medical care to individuals in law enforcement custody and prohibit deliberate indifference to the medical needs of arrestees and inmates.

Accordingly, the purpose of this letter is presentment of our client's claims for the wrongful death of her daughter, as well as any other related state or federal claims, with respect to which we demand payment, and offer compromise in exchange for payment, of One Million Dollars or the applicable limit of coverage under any and all available policies of insurance or pooled risk-managment programs, whichever is greater.

Please do not hesitate to contact me if you wish to discuss this matter. Note that I am communicating both with the county administration and with the Sheriff's Office due to lack of clarity in the current law surrounding anti-litem notice in cases involving sheriffs, who are entitled to presentment under OCGA § 36-11-1 even though they are independent, elected officials under the Georgia Constitituion. See the discussion in Mendez v. Moats, 310 Ga. 114 (Ga. 2020) (Nahmias, concurring). 
