* Clark Substitution Argument

Good afternoon, your honor. I'm here representing the plaintiff, Deborah Clark in a routine traffic collision case that was filed by my office in April of 2020. We were never able to really begin discovery, because the defendant was elderly and ill and, eventually, passed away on December 21, 2020. I had hoped that the family would establish an estate, but they didn't, so we were forced to open a creditor's estate.

Ms. Bowen Higgins, the attorney for the decedent, filed a suggestion of death on April 30, 2021, and we filed our motion to substitute the estate on August 18, 2021. Ms. Bowen Higgins didn't file any objection to the motion, so it is formally unopposed, and this motion is subject to waiver of objection. See HWA Props., Inc. v. Cmty. & S. Bank, 322 Ga. App. 877 (2013). It's frankly not clear to me that she was authorized to file a suggestion or an objection, because her client is deceased.

Numerous appeals court cases describe the purpose of the procedure in 9-11-25 as provision of a time limit intended for the protection of the non-party administrator. Anderson v. Southeastern Capital Corp., 243 Ga. 498 (1979); Berry v. Morton, 152 Ga. App. 117 (1979); Binns v. Binns, 193 Ga. App. 554 (1989).

Even the time limit can and indeed must be set aside on a showing of excusable neglect. Jernigan v. Collier, 234 Ga. 837, 218 S.E.2d 556, 1975 Ga. LEXIS 1301 (1975); Anderson v. Southeastern Capital Corp., 243 Ga. 498, 255 S.E.2d 12, 1979 Ga. LEXIS 959 (1979).

The only case I was able to find that discusses issues other than timing bearing on the present motion is McCarley v. McCarley, 246 Ga. App. 171 (2000), which suggests there may be fact issues relating to the status of a purported legal representative for an estate. Absent such issues, however, substitution appears to be mandatory.

It is here undisputed that the defendant in this matter is dead; a copy of his death certificate is attached to the present motion as an exhibit and his death is suggested by opposing counsel on the record. A copy of our creditor's petition is attached to the motion as Exhibit B, and a copy of Mr. Hinton's Oath of Adminstration is attached to the motion as Exhibit C. {I believe Mr. Hinton is here today and he can speak to his authority}

Moreover, it's undisputed that the present motion was filed within 180 days of the date of filing of the suggestion of death. In fact, that period is arguably not even running as of yet, because there is no record of service of the suggestion on the non-party administrator. See Bledsoe v. Sutton, 174 Ga. App. 248 (1985), which holds that when a party files a suggestion, it has to be personally served on the administrator. Again, it's not even clear that Ms. Bowen Higgens had the authority to file a suggestion at all.

lhuggins@hallco.

Court should order substitution and allow amendment of the pleadings and personal service of this action on the administrator of the Decedent's estate, who would then be able to raise any issues relating to his status as defenses, if there is something about which our office is unaware.

Mr. Hinton did receive notice of the motion by mail service, and my office did notify him that there would be a hearing today. He hasn't been personally served with anything to my knowledge, and he is not as of yet a party to this case.
