_Tiffany Leigh Deane v. Patsy Jo Savage_, Superior Court of Dawson County, 2019-CV-0535 J. Kathlene F. Gosselin, Wayne Tartline and Joseph Lee Bovis Kyle. Medical $44,600.93 as of 2020-01. Auto-Owners has 100k, SafeAuto has 25k add-on UM and is out. $40,000 offer. 100k offer of settlement {limited release?} authority NOT YET. trial - Need MIL re "referral" from our office. They are going to hammer her on the gap in treatment; no discussion re surgical recommendation. SOL defense withdrawn by amendment, still denies liablilty.

LICENSE EXPIRED SINCE 2008, MAYBE PROBLEMATIC IN 2006 PRIOR ACCIDENT

Answer filed 2020-01-07 by Wayne Tartline and Joseph Lee Bovis Kyle,
denial of liability. UM (Safe Auto Insurance Company) answer by Ashley
Rice and Maya De Foor, Waldon Adelman Castilla Heistand & Prouot
2020-01-30 no concerning defenses.

$44,600.93 in medical as of 2020-01, finger fracture and cervical and
thoracic issues. Varying Dxs and probable preexisting issues. Delay in
treating and then Georgia Spine ran up a big bill. 8 month gap in
treatment. Failure to yield, fair amount of damage, airbags deployed.

Dr. Cabot 2020-02-03 Not a fan of the potential surgery suggestion in
the record, need more information for better dx. Everything seems to
stem from the automobile accident.

LI is 100k Auto Owners, UM is 25k add on Safe Auto, CS thought it was
worth only 60-75.

Would you tell me your social security number off the record?
252-96-1956

---

* accident and/or neck

Tiffany Deane replied to her own comment.
Group: Focus On Dawson
Ive have neck and mid back injuries i am having treated from a car accident but whew i need some motivation too!
Oct 6, 2019, 1:59 PM

Tiffany Deane posted in Focus On Dawson.
Thank you to the calming lady who helped my daughters this morning in the car accident that was caused by an illegal u- turn on 400 & 53. It pains me that I wasn't there for them and I want to thank you for guiding them to safety (even after people were yelling at you all). Thank you.
Updated Sep 20, 2019, 10:52 AM
Published on Sep 19, 2019, 2:05 PM
Sep 19, 2019, 11:55 AM

Tiffany Deane(to:Vita Fish)
No they had friday mon and tues off and Haley got in her accident thurs so they missed school
Sep 26, 2019, 4:08 PM

Tiffany Deane (to:Kevin Stocks)
Hey! Was in a double impact car accident over a year ago. Just recently found out it fractured my neck bc they didnt mri my neck initially in hospital. Totalled out my month old car :( but ive done therapy, Chiro, needling, massage, pain meds, even had injections and going for next round directly to neck. Next phase is to sear the nerve to cut off feeling from the problem area. If that doesnt work surgery. Totally sucks a nut
Mar 27, 2019, 3:06 PM

Tiffany Deane (to:Diana Bell Wentz)
Hey lady! I just had an mri done and it showed a fracture in c6 and disc bulges in c4,5,6 and getting mri done on mid spine to see what issues are there. My neck has been hitching and killing me after my accident last december so now im finally getting answers though not what i wanted to hear
Jan 6, 2019, 11:18 AM

Tiffany Deane commented on Sherri Ketcherside's post.
Group: Pickleball Forum
Anyone have any great suggestions for dd with a neck fracture... Ive tried so many and the pressure from most on my shoulder bring major neck pain
Apr 21, 2020, 1:43 AM

Tiffany Deane replied to her own comment.
Group: Focus On Dawson
Ive have neck and mid back injuries i am having treated from a car accident but whew i need some motivation too!
Oct 6, 2019, 1:59 PM

Tiffany Deane (to:Andrea Gnepper)
Thank you so so much! Heath mentioned you guys had an inversion table (?) Do you know if that helps with neck or just spine related? Ive been on one before with no relief
Mar 27, 2019, 11:10 AM

Diane Foxx
Hi, Tiffany. Hope you are feeling some better.

Kenny and I are leaving today for an overnight trip tonight to see the 5 area waterfall parks. We should be home by late afternoon tomorrow. Could the girls watch Kaly? Sorry I have not paid them for the other day. I will let you know when I get home from tennis later and one of them can come pick it up. Just let me know what I owe them.

Thanks and try and take care of that neck.
Jun 27, 2019, 8:20 AM

David Perruchon
Hey you. What's going on? What's wrong with your neck
Jun 20, 2019, 12:04 PM

Tiffany Deane (to:Laurie Head)
Earnhardt was known not to wear his neck brace bc he didnt feel comfortable
Feb 17, 2020, 8:58 PM

Tiffany Deane (to:Kevin Stocks)
Sheesh! I have the c5 fracture, bulges in c4-c6. Herniated discs l3-l7. Totally sucks i feel ya. Im trying some cbd oil in hopes itll work but kinda doubtful. What pain relief have you tried
Mar 27, 2019, 3:31 PM

Tiffany Deane (to:Kevin Stocks)
Whats your neck issues caused from
Mar 27, 2019, 3:06 PM

[photos available online]
