* Response to Statement of Material Facts

PLAINTIFF'S RESPONSE TO DEFENDANTS DONALD GERTEISEN AND LINDA GERTEISEN'S STATEMENT OF UNDISPUTED MATERIAL FACTS IN SUPPORT OF THEIR MOTION FOR SUMMARY JUDGMENT

Pursuant to Fed. R. Civ. P. 56 and L.R. 56.1, Plaintiff responds to Defendants' individual enumeration of fact purportedly showing that no genuine issues exist for trial as follows:

A. The Property

1. At the time of the Incident alleged in the Complaint, Defendants owned a two-bed, two bath cabin home near Helen, Georgia located at 515 Two Johns Way, Sautee Nacoochee, Georgia 30571 (the “Property”). (Deposition of Linda Gerteisen (“Ms. Gerteisen Depo.”), attached hereto as Exhibit “A,” p. 10:19-24).
RESPONSE: Not controverted.

2. The Property was built in 1997 by Mr. John Kubler. (Deposition of Donald Gerteisen (“Mr. Gerteisen Depo.”), attached hereto as Exhibit “B,” p. 12:7-14; Affidavit of John Kubler (“Kubler Aff.”) ¶ 3), attached hereto as Exhibit C.
RESPONSE: Not controverted.

3. The Property was built as a spec house pursuant to a Southern Living design plan and no modification to the Southern Living plan were made. (Kubler Aff. ¶ 4).
RESPONSE: Not controverted.

4. Mr. Kubler never received or was made aware of a notice or citation regarding any code violations at the Property prior to the sale of the Property to Defendants in 2002. (Kubler Aff. ¶ 5).
RESPONSE: Not controverted.

5. Prior to the sale to Defendants, the Property was permitted, passed all county inspections, and received a certificate of occupancy. (Kubler Aff. ¶ 6-7).
RESPONSE: Not controverted.

6. At the time of the Incident, the Property was a rental property that was managed and rented through Vacasa Vacation Rentals (“Vacasa”). (Ms. Gerteisen Depo. pp. 15:25-16:5; Mr. Gerteisen Depo. pp. 19:22 to 20:3; 18:12 to 19:5).
RESPONSE: Not controverted.

7. Prior to using Vacasa, Defendants utilized other rental management companies, including Tanglewood Cabin Rentals. (Mr. Gerteisen Depo. pp. 16:6- 10).
RESPONSE: Not controverted.

8. The Property features a wooden staircase that connects the main floor to the
upstairs bedrooms. (Deposition of Betty Denson (“Plaintiff Depo.”) - Exhibit 5, attached hereto as Exhibit “D”).
RESPONSE: Not controverted.

9. The staircase turns before the bottom two steps using two “winder” steps, or
triangle shaped platform steps. (Plaintiff Depo. – Exhibit 5).
RESPONSE: Plaintiff admits that the citation is a reference to a photograph of the staircase at issue in this matter; the referenced material does not support the contention that the stairs may be described by any particular architectural term or the implication that this is a standard or appropriate architectural feature.

10. At the time Defendants purchased the property, Mr. Kubler represented to Defendants that he was unaware of any issues with the property or staircase, including any violations of building codes or zoning regulations. (Kubler Aff. ¶ 3- 7).
RESPONSE: Not controverted.

11. The independent inspection of the Property completed at the time of the sale
of the Property did not reveal any issue with the staircase. (Mr. Gerteisen Depo. pp. 23:18 to 24:13).
RESPONSE: Plaintiff admits that an inspection was conducted and did not identify any issues; the referenced evidentiary material does not support the implication that there were no issues with the staircase at the time of this inspection that might have been identified.

12. The Property is managed and maintained exclusively by Vacasa, which includes cleanings after every guest, providing towels, sheets, and amenities for guests, and alerting Defendants for the need for any repairs. (Mr. Gerteisen Depo. p.18:4-21; Ms. Gerteisen Depo. p. 15:25 to 16:6).
RESPONSE: Denied. Plaintiff admits that the property was rented pursuant to a contract with Vacasa. The referenced material does not support the contention that Vacasa had exclusive control of the premises or the implied legal conclusion that Defendants delegated their duties as premises owners to Vacasa. (See Plaintiff's Statement of Material Facts Showing Genuine Issues Exist for Trial at ¶ 17.)

13. Defendants live in Florida and do not occupy the Property. (Ms. Gerteisen Depo. p. 11:16-21; Mr. Gerteisen Depo. p. 6:8-11; 8:13-21).
RESPONSE: Not controverted.

14. Inspections of the Property are not performed by Defendants, and Vacasa only inspects the Property after a guests stay has been completed. (Ms. Gerteisen Depo. p. 16:16-20; Mr. Gerteisen Depo. pp. 18:12 to 19:5; 19:22 to 20:3).
RESPONSE: Denied. Plaintiff admits that the property was rented pursuant to a contract with Vacasa. The referenced material does not support the contention that Vacasa had exclusive control of the premises or the implied legal conclusion that Defendants delegated their duties as premises owners to Vacasa. (See Plaintiff's Statement of Material Facts Showing Genuine Issues Exist for Trial at ¶ 17.)

15. Defendants sold the Property on November 1, 2018. (Ms. Gerteisen Depo. p. 13:5-6).
RESPONSE: Not controverted.

16. During their ownership of the Property, Defendants did not modify or alter the Property’s staircase. (Mr. Gerteisen Depo. p. 14:14-17).
RESPONSE: Not controverted.

17. During the 16 years that Defendants rented the property, they were never
notified by any guest of any issue with the staircase. (Ms. Gerteisen Depo. p. 14:13- 19; Mr. Gerteisen Depo. 15:3-13).
RESPONSE: Not controverted.

18. During the 16 years that Defendants rented the Property, they were never
notified by Vacasa or any other rental company managing the Property of any issue with the staircase. (Mr. Gerteisen Depo. 15:3-13; 19:3-5).
RESPONSE: Not controverted.

19. During the 16 years that Defendants owned the Property, they never personally had or observed any issue with the staircase. (Ms. Gerteisen Depo. p. 14:13-16; Mr. Gerteisen Depo. 14:25 to 15:2).
RESPONSE: Not controverted, however, the reference evidence does not support the legal conclusion that no issue existed during that period, nor does it controvert the legal conclusion that they should have observed (or by inspection identified) an issue with the staircase.

B. The October 8, 2019 Incident

20. Plaintiff, an 81-year old resident of Alabama with a history of falling and unstable knees, rented the Property for a stay with her husband, daughter, son-in- law, and family dog. (Plaintiff Depo., attached hereto as Exhibit “E,” p. 8:20-21; 36:25 to 37:9).
RESPONSE: Not controverted.

21. Plaintiff arrived at the Property and took her belongings upstairs without issue. (Deposition of Sidney Denson (“Mr. Denson Depo.,” attached hereto as Exhibit “F,” p. 16:6-24).
RESPONSE: Not controverted.

22. Later that evening, Plaintiff walked down the stairs and fell while traversing down the staircase. (Plaintiff Depo. p. 46:13-25).
RESPONSE: Not controverted.

23. Plaintiff does not know how she fell.
Q: Okay. Ms. Denson, what do you think caused you to fall?
A: I really don't know. I know how I think it happened, but I don't
know -- I don't know why. (Plaintiff’s Depo. p. 48:8-12).
RESPONSE: Denied. See Plaintiff's Depo. at 45-49.

24. Plaintiff is uncertain as to which step contributed to her fall:
Q: Which [step]?
A: I really don't know which one. Not really.
(Plaintiff’s Depo. p. 46:13-15).
RESPONSE: Not controverted. However, Plaintiff's testimony was that she fell near the bottom of the stairs when her foot missed one of the steps where they became narrow around the turn. (See Plaintiff's Depo. at 45-49.)

25. There were no witnesses to Plaintiff’s fall. (Plaintiff’s Depo. p. 46:20-21).
RESPONSE: Not controverted.

26. Plaintiff reported to her physicians a month prior to the incident that she felt “unsteady on her feet.” (Plaintiff’s Depo. p. 24:5-19).
RESPONSE: Not controverted.

27. Plaintiff has a history of chronic knee pain and knee instability, to the extent her physicians noted she “required 24/7 care due to the pain and the fact that her knee is unstable. (Plaintiff’s Depo. p. 32:6 to 33:8, Plaintiff’s Depo – Exhibit 3, attached hereto as Exhibit “G”; Deposition of Dr. Melissa Gray “Gray Depo.,” attached hereto as Exhibit “H,” p. 42:7-23).
RESPONSE: Not controverted; however, the referenced discussion is a discussion of Plaintiff's condition in 2015.

28. Due to the instability in her knees, Plaintiff could not get up, prepare meals or use the bathroom by herself. “She was just really unsteady on her feet at that time.” (Gray Depo. p. 42:18-23).
RESPONSE: Not controverted; however, the referenced discussion is a discussion of Plaintiff's condition in 2015.

29. Dr. Gray’s notes reflect that Plaintiff has had at least three falls in 2015 and advised Plaintiff to use some type of walking assistance tool (Gray Depo. 42:7-23; 50:22-25).
RESPONSE: Not controverted.

30. As of October 8, 2018, Plaintiff still suffered from the same chronic knee condition and unsteadiness of her feet:

Q: And at this September 4th, 2018, visit Ms. Denson was still complaining of the same chronic knee pain she had for years?
A.: Yes.
Q: And she was still complaining that she felt unsteady on her feet? A: Yes.
(Gray Depo. p. 54:20 to 55:2).

RESPONSE: Plaintiff admits that she was suffering from chronic knee pain and unsteadiness of her feet at the time of her doctor's visit on September 4, 2018. The referenced material does not support the contention that her condition was exactly the same as it had been three years prior in 2015.

31. As of October 8, 2018, Plaintiff remained prescribed for Norco, a pain medication, three times a day, which increased her risk of fall. (Gray Depo. p. 29:15- 19; 51:1-7; 54:16-19).
RESPONSE: Plaintiff admits that she was prescribed Norco at various times. However, the referenced material does not support the conclusion that Plaintiff was under the influence of Norco at the time of her fall; Plaintiff's testimony is that she was not under the influence of any medications at the time of her fall. (See Plaintiff's Depo. at 49.)

32. As a result of the fall, Plaintiff alleges she sustained an injury to her head.
(Plaintiff Depo. p. 40:9-25).
RESPONSE: Not controverted.

* Plaintiff's Statement of Material Facts

PLAINTIFF'S STATEMENT OF MATERIAL FACTS SHOWING GENUINE ISSUES EXIST FOR TRIAL

Pursuant to Fed. R. Civ. P. 56 and L.R. 56.1, Plaintiff submits the following statement of additional facts she contends are material and present a genuine issue for trial.

1. Betty Denson ("Denson") is a resident of Alabama. (Deposition of Betty Denson ("Denson Depo."), attached as Exhibit A hereto, at 8.)

2. Denson has five children with her husband of almost 50 years, Sidney Denson. (Denson Depo. at 14-15.)

3. On October 18, 2018, Denson was staying in a vacation rental property located at 515 Two Johns Way, Sautee Nacoochee, Georgia ("Premises") with her husband, her daughter, and her son-in-law. (Denson Depo. at 16, 36-37.)

4. Denson fell while going downstairs from an upstairs bedroom to turn off a television that had been left on in the living room downstairs (the "Fall" on the "Staircase"). (Denson Depo. at 39-40.)  

5. Prior to the Fall, Denson had traversed the Staircase one time only, going upstairs. (Denson Depo. at 41, 45.)

6. The lights were on, and Denson did not slip on a substance or trip over an object on the Staircase; she was wearing tennis shoes. (Denson Depo. at 47-48.)
   
7. Denson recalls that she stepped down and it felt like there was "nothing to put [her] feet in to go down," because the Staircase treads narrow as they turn near the bottom instead of coming to a landing. (Denson Depo. at 45, 48-49.)

8. The Staircase is built so that its treads narrow to zero width around a turn, which is the area of the Staircase where someone would be attempting to step if they were holding on to the railing. (Staircase Photo, Exhibit 5 to Denson Depo., attached hereto as Exhibit B.)

9. Denson hit her head, was bleeding, and went and out of consciousness after the Fall; she was hospitalized for two weeks. (Denson Depo. at 50-52.)

10. Denson had knee replacement surgery prior to the Fall. (Denson Depo. at 18-19.)

11. At the time of the Fall, however, Denson had recovered from her knee surgery and did not require the use of assistive devices to walk. (Denson Depo. at 19.)

12. Plaintiff's expert, Timothy Satterfield, provided a report regarding the Staircase and is qualified to do so. (Deposition of Timothy Satterfield ["Satterfield Depo."] at 8-30, transcript attached as Exhibit C hereto.)

13. In the opinion of Mr. Satterfield, the Staircase was in violation of applicable codes and standards due to improper handrail dimension, improper handrail height (specifically the abrupt transition in height where the Staircase turns) and a common walkline with too small of a minimum inside tread width along the side of the Staircase where the handrail is. (Satterfield Depo. at 75-95, 103-106.)

14. At the time of the Fall, Defendants were the owners of the Premises. (Defendants' Statement of Material Facts ("Defs. SMF") at ¶ 1.)

15. Defendants did not construct the home; they purchased it from a predecessor in title. (Defs. SMF at ¶¶ 2, 4, and 10.)

16. The Premises were rented to Denson and her family as a short tern vacation rental pursuant to an agreement between Defendants and Vacasa Vacation Rental ("Vacasa"). (Defs. SMF at ¶ 6.)

17. The agreement between Defendants and Vacasa provides:

"Nothing in this Agreement changes Owner's title to, or general rights and obligations of ownership in, the Home. Except as expressly provided in this Agreement, Owner is and shall at all times remain fully responsible for all physical, legal, and financial matters pertaining to the Home whether it is rented or not, including responsibility for: the cost of all repairs, maintenance, and replacement of any and all furnishings, fixtures and equipment necessary to maintain the Home in a suitable condition for rental occupancy; financial matters associated with ownership of the Home; and ensuring that the Home is in compliance with applicable law, and regulation, deed restriction, or homeowners' association bylaw or rule." (Vacasa Agreement, attached hereto as Exhibit C, at Part II.A.3.)

18. The Premises were insured by a policy of insurance that identified the Premises as a secondary residence of Defendants with short term rental only, with Vacasa as a named insured. (Proof of Insurance, attached hereto as Exhibit D.)

* Brief

PLAINTIFF'S BRIEF IN OPPOSITION TO SUMMARY JUDGMENT

Plaintiff opposes summary judgment in this matter as follows:

I. Fact Statement

Plaintiff Betty Denson ("Denson") is a resident of Alabama. (Deposition of Betty Denson ("Denson Depo."), attached to Plaintiff's Statement of Material Facts ["Pl. SMF"] as Exhibit A thereto, at 8.) She has five children with her husband of almost 50 years, Sidney Denson. (Denson Depo. at 14-15.)

On October 18, 2018, Denson was staying in a vacation rental property located at 515 Two Johns Way, Sautee Nacoochee, Georgia ("Premises") with her husband, her daughter, and her son-in-law. (Denson Depo. at 16, 36-37.) During her stay, she fell while going downstairs from an upstairs bedroom to turn off a television that had been left on in the living room downstairs (the "Fall" on the "Staircase"). (Denson Depo. at 39-40.)  

Prior to the Fall, Denson had traversed the Staircase one time only, going upstairs. (Denson Depo. at 41, 45.) The lights were on, and Denson did not slip on a substance or trip over an object on the Staircase; she was wearing tennis shoes. (Denson Depo. at 47-48.) Specifically, she recalls that she stepped down and it felt like there was "nothing to put [her] feet in to go down," because the Staircase treads narrow as they turn near the bottom instead of coming to a landing. (Denson Depo. at 45, 48-49.) The Staircase is built so that its treads narrow to zero width around a turn, which is the area of the Staircase where someone would be attempting to step if they were holding on to the railing. (Staircase Photo, Exhibit 5 to Denson Depo., attached to Pl. SMF as Exhibit B thereto.)

Denson hit her head, was bleeding, and went and out of consciousness after the Fall; she was hospitalized for two weeks. (Denson Depo. at 50-52.) She had knee replacement surgery prior to the Fall. (Denson Depo. at 18-19.) At the time of the Fall, however, She had recovered from her knee surgery and did not require the use of assistive devices to walk. (Denson Depo. at 19.)

Plaintiff's expert, Timothy Satterfield, provided a report regarding the Staircase and is qualified to do so. (Deposition of Timothy Satterfield ["Satterfield Depo."] at 8-30, transcript attached as Exhibit C hereto.) In the opinion of Mr. Satterfield, the Staircase was in violation of applicable codes and standards due to improper handrail dimension, improper handrail height (specifically the abrupt transition in height where the Staircase turns) and a common walkline with too small of a minimum inside tread width along the side of the Staircase where the handrail is. (Satterfield Depo. at 75-95, 103-106.)

At the time of the Fall, Defendants were the owners of the Premises. (Defendants' Statement of Material Facts ("Defs. SMF") at ¶ 1.) They did not construct the home; they purchased it from a predecessor in title. (Defs. SMF at ¶¶ 2, 4, and 10.) The Premises were rented to Denson and her family as a short term vacation rental pursuant to an agreement between Defendants and Vacasa Vacation Rental ("Vacasa"). (Defs. SMF at ¶ 6.)

The agreement between Defendants and Vacasa provides:

"Nothing in this Agreement changes Owner's title to, or general rights and obligations of ownership in, the Home. Except as expressly provided in this Agreement, Owner is and shall at all times remain fully responsible for all physical, legal, and financial matters pertaining to the Home whether it is rented or not, including responsibility for: the cost of all repairs, maintenance, and replacement of any and all furnishings, fixtures and equipment necessary to maintain the Home in a suitable condition for rental occupancy; financial matters associated with ownership of the Home; and ensuring that the Home is in compliance with applicable law, and regulation, deed restriction, or homeowners' association bylaw or rule." (Vacasa Agreement, attached hereto as Exhibit C, at Part II.A.3.)

The Premises were insured by a policy of insurance that identified the Premises as a secondary residence of Defendants with short term rental only, with Vacasa as a named insured. (Proof of Insurance, attached hereto as Exhibit D.)

Argument and Citation of Authority

A. Standard of Decision

The Court grants summary judgment if, but only if, the movant is able to show that there is "no genuine dispute as to any material fact and the movant is entitled to judgment as a matter of law. Fed. R. Civ. P. 56(a). Summary judgment is a "drastic remedy" that should be awarded "sparingly." Screen Advertising Film Fund Corp. v. Buena Vista Distribution Co., Inc., 100 F.R.D. 14, 16 (N.D. Ga. 1983). 

B. OCGA § 44-7-14 Does Not Insulate Defendants from Liability

1. Defendants Were Not "Out-of-Possession Landlords"

The question of whether OCGA § 44-7-14 applies in a vacation rental context appears to be an issue of first impression in Georgia. Plaintiff submits that the use of this property as a short term vacation rental is more akin to that giving rise to a status as innkeeper or depository for hire, see OCGA § 43-21-1 et seq. See also Hart v. Brasstown View Estates, Inc., 234 Ga. App. 389, 391 (1998) (owner of cabin rented for a weekend was an innkeeper, not a landlord).

This conclusion makes sense as a matter of policy. Treating vacation rental owners as "landlords" would have consequences that might seem perverse in the contemporary economy such as, for example, requiring property owners to evict overstaying guests. On the other hand, viewing the owner in a short-term rental relationship as a landlord limits liability to transient guests, who may have less ability to protect themselves than in a traditional landlord-tenant relationship and are less likely to be responsible for the creation of hazards on the premises. See generally Matthew Rosenthal, iTenant: How the Law Should Treat Rental Relationships in the Sharing Economy, William & Mary L. Rev. 59:2, 732-770.

Even assuming that they were "landlords," they retained rights and obligations with respect to the property inconsistent with the requirement of OCGA § 44-7-47 that they be "out-of-possession." The contract between Vacasa and Defendants defines the continuing duties of Defendants as follows:

"Nothing in this Agreement changes Owner's title to, or general rights and obligations of ownership in, the Home. Except as expressly provided in this Agreement, Owner is and shall at all times remain fully responsible for all physical, legal, and financial matters pertaining to the Home whether it is rented or not, including responsibility for: the cost of all repairs, maintenance, and replacement of any and all furnishings, fixtures and equipment necessary to maintain the Home in a suitable condition for rental occupancy; financial matters associated with ownership of the Home; and ensuring that the Home is in compliance with applicable law, and regulation, deed restriction, or homeowners' association bylaw or rule." (Vacasa Agreement Part II.A.3, attached to Pl.'s SMF as Exhibit C thereto.)

Finally, it is worth noting that this property, and Defendants' personal property within the premise, was insured by Defendants as a secondary/seasonal residence with short-term rental, and the policy provides coverage for premises liability. (See Proof of Insurance, attached to Pl. SMF as Exhibit D thereto.) 

Unlike other cases where the appellate courts have considered the question and found that the owner had entirely relinquished possession and control of the premises to the tenant (compare Ray v. Smith, 259 Ga. App. 749, 749-51 (2003)), the Defendants in this action expressly retained all of the rights and obligations of ownership of the property, including responsibility for any and all repairs to and maintenance of the premises. Compare Ladson Investments v. Bagent, 151 Ga. App. 24, 25-26 (1979) (finding that a jury issue existed as to whether landlord fully parted with possession based on relatively limited repair and maintenance obligations). They were not out-of-possession landlords for purpose of the question whether OCGA § 44-7-14 applies to their relationship to Plaintiff.

2. Even If Defendants Were Landlords, They May Be Held Liable for Negligent Construction or Failure to Repair

OCGA § 44-7-14 limits the tort liability of landlords who have "fully parted with possession and the right of possession" to cases of defective construction or failure to repair. In general, a landlord is not liable for defective construction unless the landlord constructed the premises. However, it is well established that an out-of-possession landlord can be held responsible for defective construction by a predecessor in title if "the landlord knew or by the exercise of reasonable diligence could have known of its improper construction before the tenancy was created." Flagler Co. v. Savage, 258 Ga. 335, 337 (1988) (quoting Ross v. Jackson, 123 Ga. 657, 659 (1905)). 

Minor defects in a staircase, the discovery of which would have required an inspector to carefully measure minor differences in tread height and landing width across numerous staircases in a large commercial complex, are not the sort of defects that should, with reasonable diligence, have been discovered by an inspector. Rainey v. 1600 Peachtree, L.L.C., 255 Ga. App. 299, 302 (2002). Here, to the contrary, the testimony of Plaintiff's expert is that the defects in the staircase where Plaintiff fell were of a sort that should have been discovered by a competent inspector, because they should have been apparent immediately on visual inspection; the fact that they were not identified in the inspections that were conducted does not remove this case from the province of the jury. The owner of premises is on constructive notice of defects that would have or should have been uncovered in a "reasonable inspection," Riggs v. Highland Hills Apartments, LLC, 334 Ga. App. 247, 251-52 (2015) (constructive notice of need to repair by landlord a issue for the jury). See generally Clark v. City of Atlanta, 322 Ga. App. 151, 153 (2013) ("The question of constructive notice ordinarily is for the jury, except in the absence of any evidence.")

The questions presented under theories of negligent construction or failure to repair is, under the facts presented here, essentially the same. Either way, even assuming for the sake of argument that Defendants had a relation of landlord and tenant with Plaintiff, which Plaintiff denies, the Court should nonetheless deny summary judgment and allow this matter to proceed to trial. 

C. Plaintiff Did Not Have Superior Knowledge of the Hazard

In Robinson v. Kroger 268 Ga. 735,493 S.E.2d 403 (1997), the Georgia Court of Appeals overruled a large number of Georgia Court of Appeals decision in which the lower appellate court had held that the plaintiff's failure to observe a visible hazard was itself a basis for summary judgment, i.e., that the plaintiff's claim was barred as consequence of the plaintiffs own purported negligence in failing to be sufficiently observant. Robinson 268 Ga. at 738-39.

Disapproving and overruling this line of cases, the Robinson court framed the issue as follows:

"[B]y routinely adjudicating as a matter of law questions of the plaintiffs and defendant's negligence, proximate cause, and the exercise of ordinary care, these decisions have made commonplace what is, in reality, an unusual circumstance in tort law, since as a general proposition issues of negligence, contributory negligence and lack of ordinary care for one's own safety are not susceptible of summary adjudication."

This line of authority respecting premises liability in Georgia following Robinson includes cases involving staircases. In Aggeles v. Theater of the Stars, Aggeles v. Theater of the Stars, 235 Ga. App. 57 (1998) (physical precedent only), for example, the Georgia Supreme Court remanded for reconsideration in light of Robinson a case in which the lower court had upheld summary judgment in favor of the Fox Theater where a patron fell in a stairwell because the railing stopped five or six steps above the end of the staircas. On reconsideration, the Court of Appeals reversed summary judgment, despite the fact that the patron-plaintiff was elderly, needed to utilize railings in staircases, and had actually used an identical railing during a prior traversal on the opposite side of the staircase where she fell. See also Murray v. W. Bldg. Materials, 243 Ga. App. 834 (2000) (physical precedent only) (relying on Aggeles in a case involving similar facts). Recently, see Stewart v. Brown, 343 Ga. App. 190 (citing Murray with approval in a case that is not physical precedent only).

Moreover, and in any event, Georgia law also provides that a landlord is responsible for injuries arising from breaches of duty imposed by the building code, including the absence of a hand rail, regardless whether the plaintiff had equal knowledge of the hazard. Bastien v. Metropolitan Park Lake Associates L.P., 209 Ga. App. 881, 882 (1993) ("The landlord...cannot avoid duties created by housing codes.") (citing  Thompson v. Crownover, 259 Ga. 126, 129 (1989)). 

D. Plaintiff's Prior Traversal Does Not Entitle Defendants to Summary Judgment

Georgia bars plaintiffs from suing property owners regarding open and obvious hazards that they have successfully traversed in the past. However, this “prior traversal rule” only applies to open and obvious hazards and is, accordingly, simply a consequence of the general rule preventing recovery by a party who had equal knowledge of a hazard. See Gervin v. Real Property Trust, 840 S.E.2d 101, 104 (2020) (“The rule imputing knowledge of a danger to a person who has successfully negotiated an alleged dangerous condition before applies only to cases involving a static condition that is readily discernible to a person exercising reasonable care for his own safety.”) (quoting Strauss v. City of Lilburn, 329 Ga. App. 361, 364 (2014)).

Here, it is inconsistent for Defendants to argue that the hazard at issue was "open and obvious," given that they also testify that they did not notice it and no prior guest noticed it. Moreover, the nature of the hazard was different depending on which direction one was traversing the stairs. Walking up and in the center (or closer to the outside wall), Denson would have been less likely to note a problem than she would be walking down, using the handrail, along the side with the narrow tread. See also Aggeles, cited above.

E. Assumption of the Risk Is a Question for the Jury

Defendants concede that assumption of the risk is a defense supporting summary judgment only in cases that are "clear, plain and palpable." Again, Defendants are inconsistent in contending that the danger in this case should have been obvious to any person of ordinary intelligence, when it apparently was not obvious to them. Moreover, in the case of a code violation, "the facts supporting [the defense of assumption of the risk] will not be plain or indisputable" as a matter of both law and public policy. Johnston v. Ross, 264 Ga. App. 252, 255 (2003). The fact that Plaintiff was elderly does not change this analysis; in fact, a person renting premises to elderly guests or tenants should arguably be held to a higher standard, as a matter of public policy, in ensuring that the premises are safe. 

III. Conclusion

Betty Denson was seriously injured in a fall on premises owned and maintained by Defendants for use as a short term rental. The hazardous condition of the Staircase is readily apparent on visual inspection once the faults in its construction are pointed out by a safety expert, but would not necessarily be readily apparent to a person of ordinary knowledge and expertience. They should have been uncovered on inspection, but were not.

As in any premises liability case, there are routine issues of comparative fault involved in this case. However, those are questions for the jury. This is not the type of case in which summary judgment for the defense would be appropriate. The pending motion for summary judgment lacks merit and should be denied.

WHEREFORE, Plaintiff respectfully prays that Defendants' Motion for Summary Judgment be denied and that the Court grant such other and further relief as it deems proper and just.

---

in an abundance of caution`
