* Jim Hardman

This is the deposition of Jim Hardman, taken pursuant to notice and agreement of counsel under the Georgia Civil Practice Act for all allowable purposes, including discovery and cross-examination, with the understanding both that objections will be reserved until the first lawful use of the transcript and that the witness may be sworn remotely in this videoconference deposition. Are these counsel's understanding as well?

Signature?

Please swear the witness.

** Introduction

Good morning, Mr. Hardman. My name is Paul Menair and I represent Barbara Estes in a lawsuit against three business entities, Jim Hardman Autos, Inc., Jim Hardman Buick GMC, Inc., and Atlantic Leasing LLC.

Could you start by telling me what your relationship is with those entities?

Your deposition has not been noticed as a 30b6 deposition, which means that your testimony today is on behalf of yourself and not the business entity. I have noticed a deposition of the business separately. Do you understand that distinction?

Will you also be testifying today as the company represenative?

{I am going to try not to be repetitive, but it may happen that I have the same questions for you individually and as a corporate representative. So that we're clear, though, I will be asking you questions individually first, then I'll let you know when I switch over to asking you questions in a different capacity. Okay?}

Have you ever been deposed before?

It's a fairly simple process, I ask you questions, and you answer them under oath. The only real wrinkle is that there is someone trying to make a verbatim transcript of what we say, so it's important to speak clearly and try not to talk over each other. This is a videoconference, so she can only hear one of us at a time.

If you want to take a break at any time, just ask, I will only ask that you respond to any question that's on the table before we go on mute, sound fair?

The companies I am talking about today are the defendants in this case, Jim Hardman Autos, Inc, Jim Hardman Buick GMC, Inc., and Atlantic Leasing, LLC. My understanding is that one or more of these companies operates a car dealership in Gainesville at a location where my client was injured. Can you walk me through these entities and what their relationship is to the dealership business, as you understand it.

I'm going to try to be clear about which entity I'm talking about, but I may from time to time just refer to "the Dealership" if I am talking generally about the business at that location. If I do that I'm probably not asking a question where the distinction between the three entities is important, but if there is ever any confusion in your mind as to what I mean, and that's entirely possible because I don't always ask perfect questions, please let me know you don't understand and ask me to rephrase, okay?

If you do answer a question, I will assume you thought about the question and are giving me a truthful and complete response to the question I asked, okay?

Are you ready?

Is there anything that might interfere with your ability to give me truthful and complete responses to my questions today, like an illness or some sort of medication you are on?

Please state your full name for the record.

** Background

What is your date of birth?

Could you tell me what your physical address is?

Do you have any relatives in Hall County, Georgia?

Do you have any social connections in Hall County, like a church or rotary club membership, anything that would connect you to someone who might show up to serve on a jury in Hall County? 

Where did you go to high school?

Did you graduate? What year?

Any college? Where? Degree?

Walk me quickly through your work experience.

** JHB

Do you have any official job titles at any of the entities we talked about earlier?

The Georgia SOS has you listed as CEO and CFO of both Jim Hardman Buick GMC and Jim Hardman Autos, is that correct?

Also according to the SOS, you are secretary of Jim Hardman Auto but Adelaide Hardman is secretary of Jim Hardman Buick. Is that your wife? Why one company and not the other?

I don't see any officers listed for Atlantic Leasing, are there officers for that entity?

You are listed as registered agent of all three entities, correct?

What does your work entail on a day to day basis.

Any other employment?

Are their directors or managers for these entity? Who?

Who are the owners? Shareholders, members?

How many people report to you at the company?

Is your office physically located at the dealership?

The dealership is located at 1592 Browns Bridge Road.

How many people work there, on a given day?

If my client was injured on December 19, 2019, which I'll represent for the record was a Wednesday, would you be able to tell me who was working that day?

Do you have records you could use to figure that out for me?

Who is James Robert Anderson?

What do you think he knows that is relevant to this case?

** Invitee

To your personal knowledge, is Jim Hardman Buick GMC, Inc. the company that operates a dealership at 1592 Browns Bridge Road?

The property there is owned by Atlantic Leasing, LLC, correct?

And leased by Jim Hardman Buick?

Which entity had day to day operational control of the premises, in your opinion.

Jim Hardman Buick GMC, Inc. was responsible for all maintenance? Repair? Insurance? Utilities?

And the dealership was open for business on the day my client fell.

And as part of that business, Jim Hardman Buick, GMC, Inc. invites members of the general public to come in and purchase automobiles.

And you have no reason to believe that my client was there for any purpose other than to potentially purchase an automobile, correct?

Is it your understanding that Jim Hardman Buick GMC, Inc. has a duty to take reasonable and appropriate measures to make the premises of the dealership premises safe for members of the general public.

Do either of the other entities have any responsibilities regarding upkeep of the premises or safety, in your personal opinion?

** Personal Knowledge

How did you become aware that my client was injured on your property?

Were you there that day?

Did you ever interact with or talk to my client?

I'm going to ask you some questions about who you talked to and when, and before I do, I just want to say, I don't want to know anything about anything you said to your lawyers, okay?

Who did you talk to about the fall? What did they say?

Who have you talked to since?

Did you notify your insurance carrier? When?

Were you served with copies of the complaint in this lawsuit? Three copies?

Have you personally inspected the area where my client fell?


On days when it rains, is there anything different that happens, as far as inspection of the premises for slip hazards is concerned?

And in #15, it says that Mr. Catarino was the person ultimately responsible for monitoring, maintaining, and cleaning in the premises on the day my client fell, correct?

*** Cameras

In #18, you say that there are cameras on the premises, but only in "employee areas."

Could you be more specific about where the cameras are.

So your testimony is that there is no video footage of my client's fall.

Any cameras in the parking lot? Why not?

*** Other Incidents

In #19, you say that you do not recall any other incidents where people slipped or fell at the restaurant within the past five years.

The restaurant got built out in 2004, correct?

Any slip and fall incidents at the restaurant that you can recall, sitting here today, at any time?

I'm showing you a document that I'm going to ask the court reporter to mark as Exhibit 4.

I'll represent that this is a document that we got from 911 in Lumpkin County.

Does this refresh your recollection about another fall that happened in 2015?

Tell me about this incident?

What steps did she fall on? {details}

Was there a lawsuit arising from this incident?

Was any insurance money paid? How much?

** Incident

Let's talk about the incident where my client fell.

How did you find out about it? {Details}

What did he say, exactly? {Details}

Have you talked to anyone else?

Have you ever talked to my client

Have you put anything in writing about the fall anywhere? Including social media?

Are you aware of anything in writing, like in a memorandum or on social media, other than what we've looked at?

What do you believe caused my client to fall?

What do you base that belief on?

Is there anything you can think of that could have been done by your employees to prevent my client's fall?

Anyone else who could have prevented the fall?

In your opinion, was my client solely responsible?

What could she have done to avoid the fall?

What else?

** Franchise Agreement

I'm going to show you what we'll mark as Exhibit 5

This is the franchise agreement for the restaurant, correct?

And you signed this personally as a direct party to this agreement, correct?

Are those your initials?

And is this your signature on p. 27?

On p. 28 it identifies you as a 49% owner of VJM on June 28, 2004.

Was that accurate on that date?

Is it still?

Is this a complete and accurate copy of the franchise agreement between y'all and Captain D's, LLC, subject to the redactions your counsel has made to remove some confidential information?

On p.5, at Section 7, it talks about standards, business practices, and policies. Is that correct?

What is your understanding of what this portion of the agreement generally means, in simple terms?

How are these policies communicated from Captain D's to VJM?

VJM's employees?

Are you aware of any policies or procedures promulgated by Captain D's under this provision of the franchise agreement relating to the prevention of slip and fall or trip and fall incidents at the restaurant?

Do you agree with me as a general matter that Captain D's would have the authority to promulgate such policies under this provision, within reason?

So if Captain D's had, for example, a policy that required daily inspection of the premises for fall hazards, VJM would be bound to implement that policy?

Is there such a policy?

Should there be?

Are there policies regarding, for example, food safety?

Are you aware of any policies that would require the city or county to inspect the premises for hazards?

Were there any such inspections?

You were involved in the construction of the premises, correct?

And you stay involved in the day to day business?

So you would be aware of any city or county inspections, yes?

What about insurance audits, relating to safety?

You would agree that the safety of your customers is important, correct?

And VJM has a duty, not to ensure their safety, but to take reasonable precautions to make the premises safe for customers or potential customers, yes?



** Personal

Have you ever been arrested?

Have you ever been convicted of a crime?

Have you ever been bankrupt?

Do you think you've understood my questions today?

Have you given me truthful, accurate, and complete testimony today?

Have you left anything out?

Is there anything relevant to this case that we haven't thought about, that you think a jury might want to know in deciding whether VJM is liable to my client?

** Thank You

