* Estes, Barbara v. Jim Hardman

  /Barbara Estes v. Jim Hardman Autos, Inc., Jim Hardman Buick GMC, Inc., Atlantic Leasing, LLC, State Court of Hall County/

IN THE STATE COURT OF HALL COUNTY
STATE OF GEORGIA

BARBARA ESTES,

Plaintiff,

v.

JIM HARDMAN AUTOS, INC,
JIM HARDMAN BUICK GMC, INC., and
ATLANTIC LEASING, LLC,

Defendants.

JURY TRIAL DEMANDED

COMPLAINT

COMES NOW the plaintiff captioned above ("Plaintiff" or "Estes") and files her Complaint, showing the following:

Jurisdiction and Venue

1. Plaintiff is a citizen of the State of Georgia submitting herself hereby to the jurisdiction and venue of this Court, and she may be served pursuant to OCGA ยง 9-11-5 by her undersigned attorney.

2. Jim Hardman Autos, Inc. is a Georgia corporation and it may be served by its registered agent, James D. Hardman, at 1592 Browns Bridge Road, Gainesville, Hall County, Georgia 30501.

3. Jim Hardman Buick GMC, Inc. is a Georgia corporation and it may be served by its registered agent,  Jim Hardman, at 1592 Browns Bridge Road, Gainesville, Hall County, Georgia 30501.
   
4. Atlantic Leasing, LLC is a Georgia limited liability company, and it may be served by its registered agent, James D. Hardman, at 1592 Browns Bridge Road, Gainesville, Hall County, Georgia 30501.
  
5. This action for damages for personal injuries arising from a trip and fall incident is within the subject matter jurisdiction of the state court.

6. Venue is proper in Hall County pursuant to Georgia Constitution Art. VI, Sec. II, Para. IV and VI.

Facts Common to All Counts

7. On December 18, 2019, Estes visited the Jim Hardman Buick location located at 1592 Browns Bridge Road in Hall County, Georgia (the "Premises").

8. The purpose of her visit was to drop off paperwork associated with a vehicle purchase.

9. The business at the Premises is operated by Jim Hardman Autos, Inc. and/or Jim Hardman Buick GMC, Inc.

10. The Premises are owned by Atlantic Leasing, LLC and leased to Jim Hardman Autos, Inc. and/or Jim Hardman Buick GMC, Inc.

11. At all times relevant hereto, Estes was visiting the Premises for a commercial purpose associated with the business of the Defendants herein and for the mutual benefit of Estes and said Defendants.

12. At all times relevant hereto, Estes was an invitee on the premises.

13. Estes tripped and fell at the Premises, incurring substantial personal injuries ultimately requiring surgery;.

COUNT I - Premises Liability

14. Defendants had a duty of ordinary care pursuant to OCGA ยง 51-3-1 or other applicable law to keep the premises and approaches safe for business invitees such as Estes.

15. Defendants breached said duty of care by installing, maintaining, and failing properly to inspect and remdiate the walking surfaces and curbs in its parking areas.

16. Defendants had superior knowledge of the hazard.

17. As a direct and proximate consequence of Defendants' breach of duty, Estes suffered personal injuries for which she should be entitled to recover damages, including special damages for her past and future medical expenses, which continue to accrue, in the amount of at least $106,384.25, as well as general damages for her pain, suffering, and emotional distress.

COUNT II- Ordinary Negligence

18. Defendants had a duty to exercise ordinary care in the construction, maintenance, inspection, and repair of the Premises.

19. Defendants breached said duty of care as set forth above.

20. As a direct and proximate consequence of Defendants' breach of duty, Estes suffered personal injuries for which she should be entitled to recover damages, including special damages for her past and future medical expenses, which continue to accrue, in the amount of at least $106,384.25, as well as general damages for her pain, suffering, and emotional distress.

WHEREFORE, Plaintiff respectfully prays that summons issue and be served as provided by law on each defendant, that six months of discovery be had, that the matter be tried to a jury on all counts so triable, that judgment be entered in favor of Plaintiff and against Defendants, that the Court cast the costs of this action on said Defendants, and that the Court grant such other and further relief as it deems proper and just.

   
