* 6.4

Wesley,

I reviewed your client's discovery responses and have the following concerns:

Interrogatory 8: This interrogatory is a contention interrogatory directly premised on your pleading, which alleges violation of building codes. It is perfectly legitimate and does not call for legal "conclusions." If your clients are going to expressly allege violation of legal codes, they are going to have to be able to articulate their contention. See Donahay v. Palm Beach Tours & Transp., Inc., 242 F.R.D. 685 (S.D. Fla. 2007) ("Plaintiff is entitled before he takes depositions in this case to be informed concerning the Defendants' theory [of how the law applies to the facts of the case].")

Interrogatory 14: While I appreciate your clients' position that their damages continue to accrue, I am somewhat troubled by their unwillingness to provide a calculation of damages incurred to date. Please supplement this response.

Request to Produce 5a: We asked for a copy of your clients' agreement with your firm. The response was that this is "privileged." However, your clients are claiming that they have incurred and should be reimbursed for attorney fees. The nature of their agreement with counsel is put at issue by that claim. Moreover, the attorney-client privilege is limited to confidential communications involving the provision of legal advice, and I am unaware of any authority providing that they are shielded by the privilege when placed in issue in the case, which it will be your burden to show. Similarly, referencing Request to Produce 4, if your client is claiming damages in the nature of attorney fees, documentation in the form of invoices presented to them for payment would be relevant and discoverable in response to that request.

I look forward to hearing from you regarding these issues. I am discussing the matter you called about with my client, and I would suggest we wait at least a couple of weeks before we start scheduling depositions and site visits. In the meantime, I hope to hear back from you in response to this letter by close of business on Wednesday, June 14, 2023.



* Answer

ANSWER

COMES NOW the above defendant, Luke Fugich ("Fugich" or "Defendant") and files, showing the following:

Answer

Defendant asserts the following affirmative defenses, reserving the right to amend and supplement:

The Complaint of the above plaintiffs (collectively the "Clarkes" or "Plaintiffs") fails to state a claim upon which relief may be granted.

The action may be barred in whole or part by an applicable statute of limitations.

Plaintiffs have failed to comply with conditions precedent to this action under OCGA ยง 8-2-38.

The action may be barred in whole or part by Plaintiffs' failure to mitigate their damages.

The action may be barred in whole or part by the doctrines of waiver or estoppel.

The action may be barred in whole or part by Defendants' anticipatory repudiation of the contract.

The action may be barred in whole or part by Defendants' acceptance of the work performed.

Defendant's alleged conduct was not the proximate cause of any injury to Plaintiffs, or such injury was caused by non-parties or Plaintiffs' own negligent conduct.

Plaintiffs have failed to plead their special damages with sufficient specificity.

Plaintiffs have failed to elect their remedy.

Defendant responds to the individually numbered paragraphs in the Complaint as follows:

1. Admitted.

2. Admitted.

3. Admitted.

4. Upon reasonable inquiry, Defendant is unable to admit or deny the allegations in Paragraph 4 which, accordingly, stand denied.

5. Admitted.

6. Denied.

7. Denied.

8. Upon reasonable inquiry, Defendant is unable to admit or deny the allegations in Paragraph 8 which, accordingly, stand denied.

9. Upon reasonable inquiry, Defendant is unable to admit or deny the allegations in Paragraph 9 which, accordingly, stand denied.

10. Upon reasonable inquiry, Defendant is unable to admit or deny the allegations in Paragraph 10 which, accordingly, stand denied.

11. Denied.

12. Denied.

13. Denied.

14. Denied.

15. Upon reasonable inquiry, Defendant is unable to admit or deny the allegations in Paragraph 15 which, accordingly, stand denied.

16. Denied.

Defendant generally denies the allegations in the Complaint to the extent not specifically admitted herein, including any that might be contained in the "Wherefore" clause.

Defendant's First Interrogatories to Plaintiff

1. State the name, address, telephone number, and employer of all witnesses with knowledge relevant to the issues of liability, causation, or damages in this matter, stating the substance of what you believe each such person knows.

2. Identify any and all photographs, motion pictures, maps, diagrams, drawings, measurements, surveys or other representations pertaining to the issues involved in this matter.

3. Identify any statements, written or otherwise, obtained from anyone, including the parties, interviewed or questioned by or on your behalf in connection with this matter, including the names, addresses, home telephone numbers, places of employment, job titles or capacities, and present whereabouts of all persons giving such statements, dates on which they were obtained, and the location and present custodian of any documents memorializing such statements.
   
4. State the names, residence and business addresses, and residence and business telephone numbers of all persons whom you expect to call or may call as expert witnesses at trial, and identify any documents or opinions that were produced by or provided to these persons.

5. State the name, address, telephone number, occupation, job, or profession of any expert who has been retained or specially employed by you or, to your knowledge, by anyone else, in anticipation of this litigation or in preparation for trial, and who is not expected to be called as a witness upon the trial of the case, and identify any documents or opinions that were produced by or provided to these persons.

6. State whether you have ever been a party in any other legal action, either as a plaintiff or as a defendant and, if so, give the date and place of each such lawsuit, the name of the court, the name of the other parties and the attorneys representing each party, and describe the nature of the lawsuit and the result of the lawsuit.

7. State whether you were provided coverage under any policy of liability insurance or other form of indemnification for the damage you allege in this action and, if so, state for each such policy of insurance, including but not limited to, primary, excess, umbrella, co-insurance or any other policy:
(a)	The name of the insurance carrier;
(b)	The policy number;
(c)	The effective dates of the policy;
(d)	Your complete limits of liability;
(e)	Whether there has been any denial of coverage, reservation of rights, or non-waiver agreement pertaining to said insurance;
(f)     The amount claimed; and
(g)     The amounts paid.

8. Identify any statute, rule, regulation, standard, or ordinance, if any, which you claim Defendant violated which relates in any way to the subject of this lawsuit, including, without limitation, but "applicable building codes" referenced in Paragraph 12 of your Complaint

9. State whether you have ever pleaded guilty to or nolo contendere to or been convicted of any crime (including traffic offenses). If so, state the nature of the offense, the date, the county and state in which you were tried, and the sentence.

10. State in detail the legal and factual basis for your contention, in Paragraph 5 of your Complaint, that you "contracted with" this Defendant, stating what you believe the terms of the contract to be and the manner of its formation, and identifying each and every document you contend constitutes or in any way memorializes this contract, whether or not you concede or contend the document itself constitutes a written contract.

11. Identify the amount of each and every payment made to this Defendant relevant to this matter, identifying any document that records, reflects, or memorializes said payment.

12. State in detail the legal and factual basis for your contention, in Paragraphs 7 and 12-14 of your Complaint, that Defendant improperty constructed improvements on your property or that his work was "substandard," identifying any and all documents that support this claim.

13. State in detail the legal and factual basis for your contention, in Paragraph 14 of your Complaint, that remediation was not possible and it was necessary to demolish and reinstall improvements, identifying any and all documents that support this claim

14. Provide a complete and detailed itemization or estimate of your damages, identifying any and all documents that support your claim.

15. State in detail the legal and factual basis for your contention that this Defendant has been stubbornly litigious, has acted in bad faith, or has caused unnecessary trouble and expense.

16. Identify any social media accounts you use, including your username.

REQUEST FOR PRODUCTION OF DOCUMENTS

1. Produce each and every document relied upon or identified by you in part or in whole in your effort to respond to the preceding interrogatory responses.

2. Produce any and all documents identified by you in response to the preceding interrogatories.

3. Produce any photographs or video of the work performed by Defendant or any remediation work and, if they were taken in color, please ensure the copies are also in color.

4. Produce documentation of your damages, including, without limitation, documents that record, reflect, or memorialize payments to Defendant, payments to third parties for remediation or other work, and payments to your attorneys.
   
5. Produce a copy of any document that records, reflects, or memorializes an agreement with any person relating to this litigation, including:
   a. your agreement with Defendant;
   b. your agreement with experts retained relevant to this matter;
   c. your agreement with persons or entities that performed inspections, demolition, remediation, or replacement work; and
   d. your agreement with counsel relating to this suit and any pre-suit demands.

6. Produce documents that record, reflect, or memorialize inspections of the work.

7. Produce correspondence with any person, including email and electronic messages, relating to this litigation including, without limitation, the work performed by Defendant, inspection of the work, and the demolition and reinstallation work alleged in your complaint. Please exclude any communications with your attorneys for the purpose of obtaining legal advice.

8. Produce a privilege log describing all material withheld from production pursuant to a claim of privilege.

9. Produce copies of any memoranda or or other written documents prepared by you relevant to this matter, including social media posts, diary entries, or the like.
       
10. Produce a copy of any document provided by you to any expert witness retained relevant to this action.

11. Produce any and all expert reports, including drafts or preliminary documents.

12. Produce a curriculum vitae, retainer agreement, and invoices relating to any expert retained by you in relation to this litigation.

13. Produce any and all documents relevant to this action not otherwise produced in response to the above requests including, without limitation, any documents you intend to produce at trial.

14. Produce any documents obtained by you in your investigation of Defendant.

REQUEST FOR ENTRY UPON LAND

COMES NOW Defendant Luk Fugich and hereby requests pursuant to OCGA 9-11-34(a)(2) that Plaintiffs permit representatives of said Defendant to enter upon the property described in Plaintiffs' Complaint for the purpose of inspection and measuring, surveying, photographing, testing, and/or sampling the property at such time as may be mutually agreed upon by the parties. 





