* Complaint

IN THE STATE COURT OF FULTON COUNTY
STATE OF GEORGIA

Frankie Shane Hatcher,

Plaintiff,

v.

Alexis Antonio Susana, 
Impact Transport, LLC and
Progressive Mountain Insurance
Company

Defendant.

JURY TRIAL DEMANDED

COMPLAINT

COMES NOW Plaintiff Frankie Shane Hatcher ("Hatcher" or "Plaintiff") and files his Complaint, showing the following:

Jurisdiction and Venue

x. Plaintiff is a resident of the State of Georgia submitting himself hereby to the jurisdiction and venue of this Court, and he may be served pursuant to OCGA ยง 9-11-5 by his undersigned attorney.

x. Defendant Alexis Antonio Susana ("Susana") is a citizen of Barrow County, Georgia, and she may be served sith summons and complaint in this matter at 31 West Williams Street, Apartment B, Winder, Georgia 30680.

x. Defendant Impact Transport, LLC ("Impact") is a Georgia limited liability company, duly authorized by the Georgia Secretary of State to transact business in the State of Georgia, and it may be served with summons and complaint in this matter by its registered agent, Alexis Antonio Susana, at 31 West Williams Street, Apartment B, Winder, Georgia 30680.

x. Defendant Progressive Mountain Insurance Company ("Progressive") is an Ohio insurance company and it may be served with summons and complaint in this matter by its registered agent, CT Corporation System, at 289 South Culver Street, Lawrenceville, Gwinnett County, Georgia.

x. The state court has subject matter jurisdiction of this action for money damages arising from a traffic collision.

x. Progressive has an agent or place of doing business in Fulton County, Georgia.

x. Venue is proper in Fulton County pursuant to Ga. Const. Art. VI, Sec. II, Para. IV and VI and OCGA ยง 33-4-1(2) or other applicable law.

Facts Common to All Counts

x. On April 28, 2020, Hatcher was traveling westbound in a motor vehicle on State Route 9, East May Street, near its intersection with South Williams Street, in Winder, Barrow County, Georgia.

x. Susana, operating a 2018 Dodge Ram 3500 with a gross vehicle weight in excess of 10,000 pounds, was backing his vehicle and trailer out of a parking lot locate at 92 East May Street.

x. Susana was operating a vehicle owned by Impact Transport, LLC, which is registered with the USDOT and operates under USDOT number 3288138, interstate and for hire.

x. The vehicle was insured by Progressive pursuant to a policy of insurance registered with the USDOT.

x. The vehicles driven by Hatcher and Susana collided.

x. Hatcher was injured in the collision including, inter alia, a rotator cuff injury for which he subsequently underwent surgery.

COUNT I - Negligence

x. Susana had a duty to operate a motor vehicle with due care on April 28, 2020.

x. Susana breached that duty by, without limitation, entering into a roadway without yielding the right of way.

x. As a direct and proximate consequence of Susana's breach of duty, Hatcher suffered injuries for which Susana should be held liable to pay damages, including, without limitation, special damages for his past and future medical expenses in an amount of at least $155,175.50, which continue to accrue, lost income in the amount of at lease $8,518.38, which also continues to accrue, and general damages for his pain, suffering, emotional distress, and loss of capacity to labor, in an amount to be determined at trial.

COUNT II - Negligence per se

x. Susana had a duty to operate a motor vehicle in compliance with Georgia law on April 26, 2020.

x. Susana breached that duty by, without limitation, entering into a roadway without yielding the right of way in violation of OCGA ยง 40-6-73.

x. As a direct and proximate consequence of Susana's breach of duty, Hatcher suffered injuries for which Susana should be held liable to pay damages, including, without limitation, special damages for his past and future medical expenses in an amount of at least $155,175.50, which continue to accrue, lost income in the amount of at lease $8,518.38, which also continues to accrue, and general damages for his pain, suffering, emotional distress, and loss of capacity to labor, in an amount to be determined at trial.

COUNT III - Vicarious Liability

x. Susana was acting in the scope and course of his employment by Impact at the time of the collision at issue herein.

x. Impact should be held vicariously liable for Susana's conduct.

COUNT IV - Negligent Entrustment, Hiring, Training, Retention, and Supervision

x. Impact was, in the alternative, negligent in the hiring, training, retention, and supervision of Susana.

x. Impact was also negligent in entrusting Susana with a motor vehicle.

x. As a direct and proximate consequence of Impact's breach of its duties of care, which constituted negligence, Impact should be held liable to pay damages, including, without limitation, special damages for Hatcher suffered injuries and Impact should be held liable to pay damages, including, without limitation, special damages for his past and future medical expenses in an amount of at least $155,175.50, which continue to accrue, lost income in the amount of at lease $8,518.38, which also continues to accrue, and general damages for his pain, suffering, emotional distress, and loss of capacity to labor, in an amount to be determined at trial.

COUNT V - Direct Action

x. Pursuant to OCGA ยง 40-2-140(d)(4), Plaintiff may join in this action both Impact and its insurance carrier, Progressive.

x. Pursuant to said statute, Progressive may be held directly liable for Susana and/or Impact's negligence.

WHEREFORE, Plaintiff respectfully prays that summons issue and be served with the foregoing complaint as provided by law, that six months of discovery be had, that the matter be tried to a jury as to all issues so triable, that the Court enter judgment in favor of Plaintiff and against all defendants as set forth above, that the cost of this action be cast upon the defendants, and that the Court grant such other and further relief as it deems proper and just.

