* ante-litem

via certified mail
Wade Demron, Director
Risk Management Services
Department of Administrative Services
200 Piedmont Avenue, Suite 1220, West Tower
Atlanta, Georgia 30334

{address may be Suite 1804, please call and confirm where to send ante-litem}

via certified mail
Stacey Suber-Drake, General Counsel
Georgia Department of Education
205 Jesse Hill Jr. Drive, Suite 2052 E
Atlanta, Georgia 30334

{please call or email to confirm that she is the person designated for notice pursuant to OCGA 50-21-26(a)(2) - get it in writing if you can}

RE: Grayson Hensley, Ante-Litem Notice

On the morning of September 27, 2021, Grason Hensley ("Hensley"), a seven-year-old, was traveling by bus from his school in Dawson County, Georgia, to a program/facility administered by The FUTURES Program ("FUTURES"). FUTURES is part of the Georgia Network for Educational and Therapeutic Support ("GNETS"), and provides support to local school systemss in provision of services to students with disabilities. http://www.thefuturesprogram.com/about-us.html. It is administered and funded by the Georgia Department of Education, a state government entity. https://www.gadoe.org/Curriculum-Instruction-and-Assessment/Special-Education-Services/Pages/Georgia-Network-for-Special-Education-and-Supports.aspx. 

While on the bus, the bus driver, Carl Cox ("Cox"), struck Hensley with Hensley's belt, injuring and traumatizing yhim. Since the incident, he {{XXX}}

The location of the incident was near the city limits of the City of Cornelia, Georgia. Accordingly, I am writing this letter pursuant to OCGA 50-21-26 as ante-litem notice to preserve any and all claims by or on behalf of Hensley against the Department of Education of the State of Georgia arising from this incident, including, without limitation, claims for negligent hiring, supervision, training, and retention, as well as vicarious liabillity for Cox's conduct to the extent he was acting as an employee or agent of the State of Georgia. To date, Hensley has incurred $XXX in medical expenses directly arising from the incident. Given the fact that his evaluation is ongoing, and in view of the nature and extent of his emotional distress and psychological trauma arising from the incident, we are demanding $XXX in settlement of this claim.

Please do not hesitate to contact me to discuss this claim.
