* Hopkins Notes

** medical

Went for an MRI, Maloon talks about post-concussive. Concussion case, treating with Maloon on lien, only neuro sypmtom per Maloon is headache, dizziness. Client has a genetic syndrome.

Kutcher: Standard ER --> Maloon shortly after, again standard as to presentation, but lack of documented memory difficulties, etc. [SKL - people around him noticed the problems, wife and team members] Normal brain MRI doesn't rule out injury but close, don't see progression, is it new mormal or getting worse? [SKL was getting worse, maybe calmed down recently. stabilizing but still not as strong] Case for it being purely TBI is weak. Reality in these cases is seldom black and white though. Yes concussion. "Post-concussion syndrome" was made up by insurance companies as a billing category for symptoms past injury that are chronologically tied to a concussion. Super common, real issue, not a TBI. Genetic issue is separate, spinal cord pathology. If we were talking about spasticity e.g. there might be some interaction, but brain stuff no. Park City or Detroit, talk to Courtney. Probably needs a neuropsych too, get one prior.

Crabtree is not convinced re HSP.

** liability

Presuit demands in file. Medpay 1,000 exhausted. NB we have plenty of body cam. No disposition on file. Seems like it's clearly a failure to yield though, and we have an expert.

Baldwin admits scope of employment, ownership of vehicle, denies direct negligence. Their driver denies liability, admits failure to yield but claims Hopkins was speeding and changed lanes suddenly, striking him. Safety manuals produced, no drug testing, they admit that was a mistake.

NB you can see the closure in police video

----

contruction zone Forsyth accident SOL 2024-01-30. Nelson and Baldwin answered 12/9 with no concerning defenses. Vertical Earth served 10/7, default opened.  wages: vague lost income claim in complaint, not fleshed out any better in the not going to settle, move it, talk to expert, SKL calling Yaeger, fu scheduling VE [jennifer getting dates week of 11/13, even though Alevy?], Nelson, r discovery production, r file, depos driver, Evans, maybe do supervisor, Agan, Dulong -- prior incident records -- talk to expert -- supplement med -- mediation, demand 480,000 phone number of passenger is 678-502-6514 last address is from incident report VE disco no witnesses, they got a reservation of rights letter prob bc of the indemnification issue, refuse to provide other legal action information, surveillance, safety director is Frank Dievbieere, Elliott Batts responded to rogs, no industry pubs. policy overly broad. no insurance claim docs, privilege per documents created, lots of issues but not clear how much they are a target.









