* /Catherine Howell v. Lawrence Cotton, State Court of DeKalb County, Civil Action No. 20A80888, J. Dax Lopez/

SOL [[2020-06-27]] or [[2020-09-27]] disposition

** Notes

Cate Howell 404-408-0970 CateTHowell@gmail.com

Facebook: Cate Howell
Instagram Cate_Howell

Rogs:

3. Gary Bedgood was a witness to the accident; he can be reached at 678-770-6631.
   Brian Howell, Plaintiff's son, has information relevant to her damages in this matter and may be contacted through counsel.

19. {supplement medical if appropriate}
(b) in addition to her direct loss of income, Plaintiff has had to incur penalties from premature use of funds from a 401k {amount?}

{any addl documentation of lost income other than the tax documents previously produced?}

** Statement

From: Cate Howell
[[mailto:catethowell@gmail.com][catethowell@gmail.com]] Subject: Impact
Statement - Car Accident Date: May 13, 2020 at 2:16:52 PM EDT To:
meghan@leibel.com Cc: Cate Howell
[[mailto:CateTHowell@gmail.com][CateTHowell@gmail.com]]

Meghan, Please see my Impact Statement from the car accident. I have not
written an imlact statement like this before, and not sure if this
reflects the full scope of what is needed. Please advise.

Thanks, Cate

On 6/27/2018 I was driving home and as I was getting onto I-285 West
from I-85 North, I suddenly felt a hard impact to my car, held tight to
the steering wheel, looked to the right, and saw a car seemingly against
the right side of my car, but the driver himself was facing backwards as
we were traveling westbound at about 50 mph. It was surreal - his car
was facing backwards (eastbound as we were travelling westbound)!

I soon learned that the other driver had been traveling southbound on
I-85 and was on the ramp merging into the right lanes (I was in the far
left of 4 lanes). He hydroplaned as he was traveling too fast and was
out of control. He spun, and while spinning he hit me while he was
moving westbound at a faster rate (50+ mph) than I was going (since he
came up from behind me.)

He caused me to go from about 50 mph to a quick stop (my wheels could no
longer turn due to the damage) as well as a hard hit to the right side
of my car.

In addition to the incredible mental and emotional shock, this resulted
in being "thrown" inside the car by a tremendous jolt of his car hitting
me. Apparently I braced myself with my left leg and my right arm and
hand and was physically "tossed" inside the car, of course with my
seatbelt on.

The driver who had been travelling behind my car pulled ahead of me and
stopped on the left shoulder to assist me, repeatedly offered to call an
ambulance for me due to the level of impact, and stayed to talk with the
Police as a witness. He also told me he thought he was the one who would
be hit by the car spinning out of control, but that car had such fast
forward motion, that it caught up to me, as I was traveling at approx 50
mph, and he hit me.

I was on the scene of the accident for over 3 hours waiting for the
police and tow truck, in the dark, in the rain, on I-285. My car was not
drivable. It was literally dragged from the far left lanes to the right
shoulder by the emergency response vehicle, and then I had it towed to
my house while waiting for further instructions.

Impacts: I went to Dr Ramón Sanchez, Neurologist, (Peachtree Neurology
Associates), and to Dr Roy Sweat, Chiropractor, on the first available
dates that I could. Dr Sanchez stated that I should have gone to the
emergency room due to the impact, speed, etc. He was concerned about an
injury to my brain, whether there was a hard physical impact to my head
against the car or not.\\
My symptoms that day included headaches, "foggy brain", dizziness, etc
that were not occurring before the car accident. As Dr Sanchez stated,
the full symptoms of a brain injury sometimes show at a later date, and
may not start until 4-6 months after the impact. Dr Sweat indicated that
the car accident did cause injury to my neck.

I also had pain in my left hip and ankle. I went to my GP, Suburban
Medical Group, who referred me to an Orthopedist, and I then went to
Emory Orthopedist for care. They also referred me to Emory Physical
Therapy where I had treatment for my hip and ankle.

Due to the distance to Dr Sanchez' office and the out of pocket
expenses, I changed to a different Neurologist, and started seeing Dr
Kukaswadia at Gwinnett Concussion Center, and am still under his care.

At the time of the accident, I was on the job market. I secured a
contract to do Process Consulting and Documentation work starting in
October 2018. By that time, my dizziness and cognitive challenges had
increased, and the only difference in my life had been the car
accident.\\
The job requirements were so basic considering the caliber of work that
I had previously done, yet I was so challenged that I struggled to
perform adequately and almost lost the job.\\
My challenges included cognitive challenges and effective
communications.\\
I also had vertigo conditions return which I had had from a previous
injury almost two years prior, and had not had any vertigo for quite a
while. The vertigo was so intense that I had to often brace myself when
walking, and it lasted for weeks.

I reported the challenges to Dr. Kukaswadia who ordered tests (EEG, MRI,
MRV, etc).

This also took billable hours away from work and took a scheduling toll
on my work days.

At work, I had to break down my work into very simple steps, spend an
excessive amount of time doing simple tasks, work many extra hours, and
significantly minimize my communications with others which was critical
to my business role.\\
Over time (months), I was able to compensate and adjust, but the car
accident took a toll and threatened my Contract and earnings, and
demanded many more hours to accomplish basic work. It also caused a lot
of stress and anxiety in my confidence to work and sustain myself.

I had flashbacks for months and I continue to have small anxiety attacks
when traveling along that part of I-85 / I-285 which is a common route
for me in Atlanta, especially in the rain.

At this time, my hip and ankle are ok but I continue to have cognitive
issues.

My cognitive issues are better but I still have trouble focusing and
staying on task for ANYTHING which I did not have prior to the accident.
I am still under the care of Dr Kukaswadia for my brain challenges.

I also had to replace my car which was paid for and In great condition,
with another car, and due to not having a job at the time (I often
contract), I am paying high interest rates which is costing me an
additional financial burden that I would not have otherwise incurred if
my car had not been hit and totalled.

Cate Howell

