* Notes

Angelia Huber 770-403-1025

[ ] model serial
[ ] timeline, treatment
[ ] estate what issues (children, brother), can I call Shelly
[ ] medical expenses, lifetime p&s

Frank Huber (850) 762-4126
Angela Huber (770) 788-0377

CPAP for sleep apnea neurologist
lung damage, smoker but quit 2011, before dx tonsil cancer, 2013 cancer free, no problems for quite a while. Continued to work. Worked until 2017 as a propane driver. Unidentifed neurology problems. Autonomic neuropathy, orthostatic hypotension. Blackouts --> neuro. Dr. Lesch. Cardiologist got involved re blood pressure. Around 2018 other health issues, not pulmonary, BP, low sodium. Noticing 6-7 months prior to hospitalizations in Dec 2020. Five times. First NEGMC in May, all during COVID. Discharge after Xmas - o2
2d April, ambulance, sounded like asthma
Sleeping with CPAP, o2 during the day
Used CPAP about 2 yrs
Last May 22 2021
vacumned lungs
July 27 passed in his sleep, lots of weight loss
Coughs started in 2020. 

[ ] COVID testing lots of tests; propane little exposure; smoking
[ ] model serial
[ ] estate

Brother is okay, Oxford Georgia

No idea where the children are, first marriage is Justin, in jail a lot, disinherited. Not in Georgia, may be in Florida.

Daughter Angela was legally adopted at marriage to second wife. Divorced after 3 years, paid child support, estranged.

Dr. B.

Look at May admissions, pulmonology.

770-403-1025

Angela Leann Huber

l/k/a per Lexis is 1658 Flat Rock Road, Stockbridge, Henry County, Georgia 30281, no such address per tax records. CA RN license with that address for Angela Huber Forrest. Registered with GA nursing as just "Stockbridge, GA." Looks like there's a house at 569 Knollwood Dr. owned by David Perry and Gloria Lowery Forrest.

Frank Justin Peter Huber

l/k/a 21202 NW Palm Beach Dr., Altha, Calhoun County, Florida 32421; that property is listed as belonging to Brian Simpson, it's a ten acre lot with a couple of destroyed buildings and what looks like a double-wide. Lexis has extensive criminal record. Fl DOC has him released as of 2015. He isn't on the jail roster for Calhoun County.

James David Huber is executor, Rosemary Akers is alternate, Randy Greene is yet another alternate. He gets 50% if Angelia predeceases.

Traci Michelle Ledbetter, the other 50%. If both predecease the estate goes in trust to the son. This is a fricking mess.

James David Huber is at 1102 Emory Street, Oxford, Newton County, Georgia 30054 per tax assessor.

Tracy [sic] Michelle Ledbetter is at 2300 Lowry Road, Monroe, Walton County, Georgia 30655 [owner Marty Tolman Ledbetter]

Rosemary Akers
Randy Greene

Petition to Probate with Will Annexed

Dawson County
Estate of Frank Peter Huber
Petitioner Angelia D. Huber
physical and mailing addr: 127 Irvin Dr., Dawsonville, Ga 30534
[same domicile of decedent]
Date of Death: 2021-07-27
Date of Will: 2003-01-03
Named Executors: James David Huber and Traci a/k/a Tracy Michelle Ledbetter.

Heirs at law:
Angelia D. Huber over 18 127 Irwin Dr., Dawsonville, Georgia Spouse
Frank Justin Peter Huber over 18 21202 NW Palm Beach Dr., Altha, FL 32421 Son
Angela Leann Huber over 18 1658 Flat Rock Road, Stockbridge, Georgia 30281 Daughter

4. The Petitioner was married to the Decedent at the time of his death. Frank Justin Peter Huber and Angela Leann Huber are his only children; no children predeceased him. The addresses given are their last known addresses.

5. Angelia D. Huber over 18 127 Irwin Dr., Dawsonville, Georgia Spouse

6. {INITIAL D - WE NEED TO GET RENUNCIATIONS FROM THE NOMINATED EXECUTORS IN THE FOLLOWING FORM:

IN THE PROBATE COURT OF DAWSON COUNTY
STATE OF GEORGIA

   IN RE: ESTATE OF FRANK PETER HUBER
   
   I {James David Huber/Rosemary Akers/Randy Greene}, having been named as the Executor of the Last Will and Testament of the above named decedent, do hereby renounce any and all duties and obligations as Executory of the Last Will and Testament of Frank Peter Huber, and decline to serve in said capacity.

   /s/
   /notary/}

7. initial (b)(2)

8-9. initial nothing

10. initial (a)

10. initial (c)

11. Decedent's assets transferred to Petitioner outside the estate. However, it appears necessary to file a tort action on behalf of the decedent's estate, which Petitioner anticipates will be the only asset of the estate.



* Huber Complaint

IN THE UNITED STATES DISTRICT COURT
FOR THE NORTHERN DISTRICT OF GEORGIA
GAINESVILLE DIVISION

Angelia Huber, individually and as wrongful death claimant,

v.

Philips North America, LLC,
Koninklijke Philips N.V.,
Philips Holding USA, Inc., and
Philips RS North America LLC,
f/k/a Respironics, Inc.

TO BE TRANSFERED TO MDL 3014 E.D. Pa.

COMPLAINT

Preliminary Statement

1. This is a wrongful death action in which the plaintiff captioned above alleges that her husband died as a proximate consequence of his use of a device designed, manufactured, and/or sold by the above defendants (the "Device"); said plaintiff anticipates that it will be transferred to multi-district litigation pursuant to {{ORDER}}.

Jurisdiction and Venue

x. Plaintiff is a citizen of the State of Georgia.

x. Defendant Koninklijke Philips N.V. ("Royal Philips") is a Dutch corporate entity established in The Netherlands and having its principal place of business at Breitner Center, Amstelplein 2, 1096 BC Amsterdam, The Netherlands. It may be served with summons and process in this matter pursuant to the Convention on the service Abroad of Judicial and Extrajudicial Documents in Civil or Commercial Matters (the "Hague Service Convention"). {Joni - see https://www.haguelawblog.com/2017/01/serve-process-netherlands/}

x. Defendant Philips North America LLC ("Philips NA") is a Delaware limited liability company with its principal place of business at 222 Jacobs Street, Floor 3, Cambridge, Massachusetts 02141. The sole member of Philips NA is Philips Holding USA, Inc., which is a Delaware corporation with its principal place of business at the same address. Philips NA may be served with summons and complaint in this action through its registered agent, Corporation Service Company, at 2 Sun Court, Suite 400, Peachtree Corners, Georgia 30092.

x. Defendant Philips Holding USA, Inc. (“Philips Holding”) is a Delaware corporation with its principal place of business at 222 Jacobs Street, Floor 3, Cambridge, Massachusetts 02141. Philips Holding may be served with summons and complaint in this action through its registered agent, Corporation Service Company, at 2 Sun Court, Suite 400, Peachtree Corners, Georgia 30092.

x. Defendant Philips RS North America LLC f/k/a Respironics, Inc. (“Philips RS”) is a Delaware limited liability company with its principal place of business at 6501 Living Place, Pittsburgh, Pennsylvania 15206. Philips RS is wholly owned by a single member, Philips RS North America Holding Corporation, a Delaware corporation with its principal place of business in Cambridge, Massachusetts. Philips RS may be served with summons and complaint in this action through its registered agent, Corporation Service Company, at 2 Sun Court, Suite 400, Peachtree Corners, Georgia 30092.

x. Royal Philips, Philips NA, PHUSA, and Philips RS are hereinafter collectively referred to as “Philips” or the “Defendants.”

x. At all times relevant to this Complaint, Defendants were and are engaged in the
business of designing, manufacturing, and selling devices for the treatment of obstructive sleep apnea, including, without limitation, the Device.

x. Defendants are and were mere alter egos of each other, operating as a single enterprise, equally controlled by one another, commingling their assets and funds, generally disregarding corporate formalities, and using each other as corporate shields to defeat justice and evade contractual and/or tort liability.

x. Defendants act and have acted as agents or apparent agents of one another, in concert, and as a joint undertaking, with mutual control over one another, in designing, manufacturing, and selling the Devices.

x. Defendants regularly transact business in Georgia, derive substantial revenue from transactions in Georgia, and have purposely availed themselves of the privilege of doing business in Georgia, including, without limitation, by registering themselves with the Georgia Secretary of State and maintaining a registered office in Georgia.

x. Defendants’ actions in marketing and selling their devices in Georgia should have led them to reasonably anticipate engaging in litigation in Georgia.

x. Defendants have sufficient “minimum contacts” with Georgia that subjecting them to personal jurisdiction in Georgia does not offend traditional notions of fair play and substantial justice.

x. As detailed below, Plaintiff's husband, the decedent herein, suffered injuries in Dawson County, Georgia, and Plaintiff alleges said injuries to be the proximate consequence of either a tort committed in the State of Georgia or a tort committed outside of the State of Georgia that caused injuries in the State of Georgia.

x. Personal jurisdiction over Defendants is authorized under Georgia’s Long Arm Statute, O.C.G.A. § 9-10-91.

x. This Court may also obtain personal jurisdiction over Philips NA, Philips Holding, and Philips RS premised on their systematic and continuous contacts with Georgia as well as their maintenance of a registered agent for service of process in Georgia.

x. This Court has personal jurisdiction over Royal Philips because of its systematic and continuous contacts with Georgia.

x. This Court has original jurisdiction in this matter pursuant to 28 U.S.C. §1332(a)(1) and §1332(a)(2), as there is complete diversity between Plaintiff and Defendants and the amount in controversy exceeds $75,000.

x. There is complete diversity between Plaintiff and all Defendants, including all members comprising Philips NA and Philips RS.

x. This division is a proper venue for this civil action pursuant to 28 U.S.C § 1391(b)(2) and 28 U.S.C. § 90(a)(2), as the event giving rise to the Plaintiff’s claims occurred in Dawson County, Georgia.

Facts Common to All Counts

x. 
