* Cindi Brooks

This is the deposition of Cindi Brooks, taken pursuant to notice and agreement of counsel under the Georgia Civil Practice Act, with all objections except to form and responsiveness reserved until the first lawful use of the transcript, and with the understanding that the witness will be under oath despite the remote administration of the oath. Is that agreeable to counsel?

Please swear the witness.

Ms. Brooks, my name is Paul Menair and I represent Mary Cunningham in a lawsuit against Ingles and certain other entities. Good morning.

I expect that you met with counsel to prepare for today's deposition, and I don't want to know anything about what was said in that meeting, but could you please tell me whether you reviewed any documents to prepare for today and, if so, which ones?

Did you meet with anyone other than your lawyers to get ready for your deposition today?

Is this your first deposition?

I'm going to ask you a series of questions which you will answer under oath. It's important for us to try not to talk over each other. Okay?

If you don't understand a question, please let me know, and please don't hesitate to ask if you need a break for whatever reason, okay?

Could you state your full name and address for the record?

Are you employed by Ingles Markets, Inc.?

In what capacity?

For how long?

You have a Masters degree from the University of Tennessee, correct?

In what discipline?

What year?

Who is your direct supervisor?

Where is your office located?

I'm going to show you a document that we'll mark as Exhibit 1 to this deposition.

Have you seen this document before today?

This is a notice that requires Ingles Markets, Inc. to designate a representative to testify on its behalf at a deposition, and my understanding based on a response to this notice that was filed on October 8 is that you are the person designated to testify on some, but not all, of these topics. Is that correct?

And specifically, my understanding is that you are not here to testify regarding topics 4 or 5 and that you are prepared to answer questions regarding other topics subject to certain objections that have been filed into the record of this case.

Are you prepared to testify regarding these topics, subject to the response and objections that have been filed?

Do you understand the distinction between testifying on behalf of a company and testifying on your own behalf?

If it's ever not clear whether I'm asking you for corporate testimony or personal testimony, please let me know, okay?

Is it okay if we refer to Ingles Markets, Inc. as just "Ingles"?

I'm going to show what we'll mark as Exhibit 2,

Are you familiar with this document?

I'll represent that this is a copy of the responses Ingles filed to a set of written questions we provided called interrogatories.

I'll further represent that responses to interrogatories are generally verified under oath, but I do not believe we ever received any verification of these.

Let's look at the response to the first question.

This response provides a list of witnesses with information relevant to the case, to be contacted through Ingles' counsel, yes? {investigation}

Sitting here today, is Ingles aware of any other witnesses with information relevant to this case?

I believe some names were mentioned in last week's deposition of Ingles employees who might know something about the incident. Does Ingles intend to investigate and supplement this response if appropriate?

Are there any witnesses to the incident or its immediate aftermath that Ingles is not disclosing, for whatever reason?

Please look at question 4 and the response.

Has there been any denial of coverage, reservation of right, or non-waiver agreement pertaining to coverage relating to my client's husband's fall?

Let's look at response 6.

What is the name of the cleaning contractor?

Does Ingles have any reason to believe that the condition of the floor or cleaning of the floor relate in any way to my client's husband's fall?

Let's look at 9.

Are there any photographs or video files that have not been produced, for any reason?

This response refers to "inspection of the table." Last week some question arose as to whether the table that was taken out of service and subsequently inspected was, in fact, the correct table. Were you aware of that?

Has Ingles conducted any investigation to determine whether it took the correct table out of service?

Sitting here today, does Ingles take any position as to whether it has preserved the correct table for inspection?

What has Ingles done to ensure that it preserved the correct table?

What happened around the time of the incident?

Number 10 references a statement made by Plaintiff to Toni Rose.

Who is Toni Rose.

What is Constitution State Services?

What does Ingles believe my client said to Ms. Rose?

Does Ingles intend to take the position that my client made any admissions in that statement.

[] Toni Rose depo?

[] emails with our client

Is Ingles aware of any complaints having been made regarding these tables?

Does Ingles do anything to ensure that the furniture in its cafe areas is safe for customers?

Including disabled or elderly customers?

Whose responsibility was it to ensure that the cafe area was safe for customers?

What policies and procedures?

In writing? All we have is the "Store Hazard Recognition Policy"

Anything relating specifically to stability of chairs and tables?

There have been no other incidents regarding the tables at this store since they were purchased in 2012.

How about tables overturning at other stores?

I'm showing what's been marked Ex 3.

Is this a true and correct copy of a document that is maintained by Ingles in the ordinary course of business and constitutes a policy of the corporation?

And it is the only relevant written policy, correct?

[4=sweeplog]

I'm showing 5, which is a response to what we call requests for admissions. Have you seen this document?

Let's look at #12.

Invitee is a legal term of art, and I'm not going to ask you for a legal opinion, okay?

Does Ingles have any reason to believe that Mr. Cunningham was on the premises that day for any reason other than to shop?

It appears that he purchased food from the deli, correct?

And sat at the seating area to eat that food, correct?

And the tables in the seating area are provided by Ingles for that purpose, correct?

And the area where he was sitting was open to the public for the commercial purpose we just described, selling people food for consumption on the premises, correct?

Does Ingles believe these tables were appropriate for use in a tiled floor area?

Ingles still uses the same tables, other than the one that was taken out of service, correct?

---

[ ] all the tables are still available

* Joe Manno

This is the deposition of Joe Manno, taken pursuant to notice and agreement of counsel and subject to the same stipulations as the deposition of Ms. Brooks conducted earlier today, if that's agreeable to counsel.

Swear witness.

Mr. Manno, my name is Paul Menair and I represent the plaintiff in a lawsuit against Ingles and some other companies arising from an incident where a table flipped over. Good morning.

Is this your first deposition?

We need to try not to talk over each other, okay?

Please feel free to ask me to rephrase a question if you don't understand it, and feel free to ask for a break at any time, although I don't expect this will take long.

Could you please state your full name for the record and spell your last name.

You have been designated to testify on behalf of Ingles Markets, Inc. regarding the selection, purchasing, and receiving of the table we're here about today, as well as its assembly at the store, is that correct?

And you understand the difference between testifying on behalf of the corporation and testifying just on your own behalf, yes?

I expect I will mostly be asking for your testimony as a fact witness today, but I may have questions for the company also on the topics for which you've been designated, and if so I'll try to make that clear, okay?

If it's not clear to you which hat I want you to wear, please let me know, okay?

Are you presently employed by Ingles Markets, Inc.?

In what capacity?

Who do you report to?

How many direct reports do you have?

All right, you were personally involved in the purchase of the table or tables that we're here about today, correct?

Tell me about that.

Robert Ingle was still around at that time, yes?

He saw these tables at a restaurant or similar facility in 2010 and liked the style? Tell me about that.

Were you with him when he first saw the Ellipse tables in action?

[ ] Greg Wilson

How did you get involved?

Tell me about Ingles' relationship with Hefco. How long? How many transactions per year? Still using them?

Is Hefco the only company that Ingles bought cafe furniture from? Regionally?

Apparently y'all worked with Hefco regarding color selection? How did that process work? Who?

Were you provided with a catalog?

Did you go see the tables in person in a showroom?

Did you ever attend any conventions or similar events relating to the furniture industry?

You were the person who purchased these tables, yes? How? Who?

How did the actual purchase happen? Phone? Email?

Were you ever aware of or involved in any discussion about the fact that these tables would be used in a tiled floor area?

Do you believe they were appropriate for use on that flooring?

Were you purchasing just for this store, or for multiple stores?

Hefco sent a purchase order to GRCC and sent Ingles an invoice, yes?

Do you recall the name of the contractor doing the remodel?

Is there a way we could work that out?

Any idea, sitting here today, who assembled the table?

Whether it was an Ingles employee or a contractor?

Any way we could work that out?

Were you ever personally aware of any issues with these tables, prior to my client's husband's fall?

What about wobbling?

Were you personally involved in the installation in any way?

Did you inspect the tables after delivery? Did anyone?

Were any safety inspections performed in the cafe seating area between the time of the remodel and the incident involving my client's husband, to your knowledge?

Ingles still uses the same table, other than the one that was taken out of service, correct?

Some questions for Ingles:

Does Ingles concede that the table that was taken out of service was incorrectly assembled?

Does Ingles concede that improper assembly might have contributed to the table flipping over?

---

[ ] email with Hefco

---

You received an invoice from Hefco.
There may have been a packing list and bill of lading shipped with the chair.
You're not aware of any other documents that might have given directions about assembly.

Has anyone inspected these tables for safety since my client's husband's fall?





