

* Complaint

IN THE STATE COURT OF GWINNETT COUNTY
STATE OF GEORGIA

Geoffrey Kridel,

Plaintiff,

v.

McDonald's Corporation,
McDonald's USA, LLC,
McDonald's Real Estate Company, and
Northeast Georgia, Inc.

Defendant.

JURY TRIAL DEMANDED

COMPLAINT

COMES NOW the above plaintiff ("Krider" or "Plaintiff") and files his Complaint, showing the following:

Preliminary Statement

x. This is an action for money damages arising from a slip-and-fall incident.

Jurisdiction and Venue

x. Plaintiff is a citizen of the State of Georgia submitting himself hereby to the jurisdiction and venue of this Court.

x. Defendant McDonald's Corporation ("MCD") is a foreign profit corporation with its principal office located at 110 N Carpenter, Chicago, IL 60607, and it may be served with summons and complaint in this action by its registered agent, Corporation Service Company, at 2 Sun Court, Suite 400, Peachtree Corners, Gwinnett County, Georgia 30092.

x. Defendant McDonald's USA, LLC ("MCD USA") is a foreign limited liability company with its principal office located at 110 N Carpenter, Chicago, IL 60607, and it may be served with summons and complaint in this action by its registered agent, Corporation Service Company, at 2 Sun Court, Suite 400, Peachtree Corners, Gwinnett County, Georgia 30092.

x. Defendant McDonalt's Real Estate Company ("MCD Real Estate") is a foreign profit corporation with its principal office located at 110 N Carpenter, Chicago, IL 60607, and it may be served with summons and complaint in this action by its registered agent, Corporation Service Company, at 2 Sun Court, Suite 400, Peachtree Corners, Gwinnett County, Georgia 30092.

x. Defendant Northeast Georgia, Inc. ("Northeast") is a domestic profit corporation with its principal and registered office located at 209 Boulevard, Gainesville, Hall County, Georgia 30501, and it may be served with summons and complaint in this matter at that address by its registered agent, Robert Swoszowski.

x. The state court has subject matter jurisdiction of this tort action for money damages.

x. Venue is proper in Gwinnett County, Georgia pursuant to Ga. Const. Art. VI, Sec. II, Paras. IV and VI and OCGA ยง 14-2-510(b)(1).

Facts Common to All Counts

x. MCD Real Estate is the owner of certain real property located at 36 Mountain Drive in Lumpkin County, Georgia (the "Premises").

x. Northeast operates a McDonald's restaurant at the Premises as a franchisee for MCD and/or MCD USA, pursuant to policies and procedures established by those entities.

x. On or about August 5, 2021, Krider was a business invitee at the premises, having entered into the premises for the purpose of engaging in a commercial transaction with the defendants herein (collectively the "Defendants").

x. Krider slipped and fell in the vestibule of the restaurant, either because the floor there was wet or because he had walked through a portion of the parking lot that was wet due to power washing of the exterior of the Premises.

x. Krider had no reason to anticipate or be aware of a slip hazard in the area where he fell, and no warning signs were present.

x. Krider suffered and injury in his fall.

COUNT I - PREMISES LIABILITY

x. The Defendants had a duty as owners or occupiers of the Premises to exercise ordinary care to keep said premises and the approaches thereof safe for business invitees.

x. The Defendants breached said duty as described above.

x. As a direct and proximate consequence of their breach of duty, Krider suffered an injury for which the Defendants should be held liable to pay damages, including special damages in the form of medical expenses in the amount of at least $78,639.03, which continue to accrue, as well as general damages for Krider's pain, suffering, and emotional distress in an amount to be determined at trial.

COUNT II - ORDINARY NEGLIGENCE (VICARIOUS LIABILITY)

x. The hazard on the premises was created by the ordinary and active negligence of an employee or agent of the Defendants, acting in the course and scope of employment, which employee or agent had a duty to exercise ordinary care in the operation of pressure washing equipment at a commercial establishment.

x. As a direct and proximate consequence of said breach of duty, Krider suffered an injury for which the Defendants should be held liable to pay damages, including special damages in the form of medical expenses in the amount of at least $78,639.03, which continue to accrue, as well as general damages for Krider's pain, suffering, and emotional distress in an amount to be determined at trial.

x. Defendants may be held vicariously liable for the conduct of their employees or agents as described herein.

WHEREFORE, Plaintiff respectfully prays that summons issue and be served as provided by law on all defendants, that six months of discovery be had, that the matter be tried to a jury as to all issues so triable, that judgment issue in favor of Plaintiff and against Defendants, that the costs of this action be cast upon the Defendants, and that the Court grant such other and further relief as it deems proper and just.

















