* McKinney

** file review

   Issues: Comp? Proper parties? Jxn? Experts? K's re indemn etc? TN SOL is 1y. Estate. Loss of consortium. ORR? Insurance? Bobtail etc?

   Facts: Forklift operator was removing load from truck and crushed driver. Driver was [employed] by Clearshine Logistics, incident happened at MBCL Jenkins & Stiles, Knoxsville, Knox Co TN. Load at METL-SPAN. United Rentals?

***  Clearshine Logistics, LLC

   {client and decedent listed as organizers}

   7251 Maddox Rd, Lithonia, GA, 30058, USA
   Date of Formation / Registration Date: 2/13/2020
   State of Formation: Georgia
   Last Annual Registration Year: 2021
   Registered Agent Name: Alberta Perry

*** Jenkins & Stiles, LLC

    {GC - Contend they are not the owner of the premises or the forklift}

    {see spoliation letter from them!!}
    
    {"Project" per BOL

    Status: Active
    Initial Filing Date: 04/07/2006
    Formed in: TENNESSEE
    Principal Office: 10617 DEERBROOK DR
    KNOXVILLE, TN 37922-1942 USA    
    Registered Agent: STEVENS, ESQ., KEVIN C.
    Agent Address: 	550 W MAIN ST
    FL 4
    BANK OF AMERICA BUILDING
    KNOXVILLE, TN 37902-2515 USA

*** Metl-Span

    6001 Quality Way
    Prince Georgia, VA 23875

    NCI Group, Inc. d/b/a Cornerstone Building Brands
    NCI GROUP, INC. (NV) 
    Principal Office Address: 10943 N Sam Houston Parkway W, HOUSTON, TX, 77064-5758, USA
    Date of Formation / Registration Date: 7/28/1995
    Jurisdiction: Nevada
    Registered Agent Name: Cogency Global Inc.
    Physical Address: 900 Old Roswell Lakes Parkway, Suite 310, Roswell, GA, 30076, USA
    County: Fulton

See also in VA F1338039 METL-SPAN (PRINCE GEORGE CO) as DBA for NCI Group, Inc., lots of useful info at: https://cis.scc.virginia.gov/EntitySearch/BusinessInformation?businessId=279815&source=FromEntityResult&isSeries%20=%20false

*** MBCI

    {customer per BOL} - another Cornerstone brand, see above, F1338039 	MBCI (ALEXANDRIA CI) Fictitious Name	Stock Corporation 10943 N Sam Houston Pkwy W, Houston, TX, 77064 - 5758, USA COGENCY GLOBAL INC.

*** Environmental Transportation

    {Carrier per BOL}

    Bill of Lading lists Expedite Las Vegas Corp. at the expeditor and gives and email address @ eton.me, which is Environmental Transportation of Nevada, at the same address. 3426 Losee Road
    
*** Amerco Real Estate Company

    {owner?} --     {U-Haul Karns project}
    http://tn-knox-assessor.publicaccessnow.com/PropertyLookup/PropertyDetails.aspx?p=091++00106&a=97457
    
    AMERCO REAL ESTATE COMPANY
    2727 NORTH CENTRAL AVE
    PHOENIX AZ 85004 



    AMERCO REAL ESTATE COMPANY (NEVADA)
    Principal Office Address: 2727 N CENTRAL AVE, Phoenix, AZ, 85004, USA
    Date of Formation / Registration Date: 6/14/1993
    Jurisdiction: Nevada
    Registered Agent Name: C T Corporation System
    Physical Address: 289 S Culver St, Lawrenceville, GA, 30046-4805, USA
    County: Gwinnett

*** Team Fortune Trucking
    
*** ---

OSHA file?

Need to find the forklift driver, subcontractor. File suit asap. DOL is 2021-04-15.



7640 Oak Ridge Highway, Knoxville, TN 37931

   prob not:
   MBCL Trucking LLC 	Control Number: 	20217609
Business Type: 	Domestic Limited Liability Company 	Business Status: 	Active/Compliance
NAICS Code: 	Transportation and Warehousing 	NAICS Sub Code: 	Mixed Mode Transit Systems
Principal Office Address: 	1311 RICHARD RD, DECATUR, GA, 30032, USA 	Date of Formation / Registration Date: 	10/8/2020
State of Formation: 	Georgia 	Last Annual Registration Year: 	2021
Registered Agent Information
Registered Agent Name: 	Cameron Longshore
Physical Address: 	1311 RICHARD RD, DECATUR, GA, 30032, USA
County: 	Dekalb
   
** client interview re estate  Alberta Louise Perry

  3995 Evening Shade Dr. Douglasville GA 30134
  same mailing

  Douglas County

  Vincent Bernard McKinney

  April 15, 2021

  Vincent Bryton McKinney 24
  Chantry Lewis 28

  stepchildren

  Byson's mother Stephanie McKinney ended don't know when

  no parents

  assets 5 motorcycle collection title in his name, value unknown, over 10
  vehicles were jointly owned

  USAA and Wells Fargo separate, unknown

  Business is an asset BB&T

  F350, and 40' trailer titled in business

  look at operating agreement

  NC address for son

  
  lutherj1@nationwide.com
  



  
