* Complaint

Kelly Lucas, individually and as Natural Guardian of Ansley Peacock, a minor,

Plaintiff

v.

Twin Creeks Timber, LLC,
John David Ussery, and
April Hayes,

Defendants.

JURY TRIAL DEMANDED

COMPLAINT

COMES NOW the above Plaintiff ("Plaintiff" or "Lucas") and files her Complaint, showing the following:

Jurisdiction and Venue

x. Plaintiff is the mother and natural guardian of Ansley Peacock ("Peacock"), a minor child; she is a citizen of Georgia submitting herself hereby to the jurisdiction and venue of this Court, and she may be served pursuant to OCGA § 9-11-5 by her undersigned attorney.

x. Defendant Twin Creeks Timber, LLC ("Twin Creeks, LLC") is a Delaware limited liability company with its principal place of business in Seattle, Washington, duly authorized to transact business in the State of Georgia, and it may be served by its registered agent, CT Corporation System, at 289 S Culver Street, Lawrenceville, Georgia 30046.

x. Defendant John David Ussery ("Ussery") is a citizen of Dodge County, Georgia, and he may be served with summons and complaint in this matter at his residence, 15 4th Avenue, Milan, Dodge County, Georgia 31060.

x. Defendant April Hayes ("Hayes" is a citizen of Dodge County, Georgia, and she may be served with summons and complaint in this matter at 15 4th Avenue, Milan, Dodge County, Georgia 31060.

x. The state court has subject matter jurisdiction of this civil action for monetary damages.

x. Venue is proper in Gwinnett County, Georgia, pursuant to Ga. Const. Art. VI, Sec. II, Paras. IV and VI; OCGA §§ 14-11-1108 and 14-2-510.

Facts Common to All Counts.

x. Twin Creeks is the owner of certain real property located in Dodge County, Georgia, near the town of Milan (the "Property").

x. On March 15, 2020, Peacock was operating in Honda Pioneer SXS1000 ATV (the "ATV") on Leonard Jones Road near Latitude 32.0407265 Longitude -83.0601118333333 (the "Location") in Dodge County, Georgia.

x. Peacock, a minor, was not licensed to operate a motor vehicle in the State of Georgia.

x. The ATV was not registered and could not legally be operated on public roads in the State of Georgia.

x. Leonard Jones Road is a dirt road and passes through the Property at the Location.

x. The ATV was uninsured.

x. The ATV was the property of Ussery and was entrusted to Peacock by Ussery and Hayes.

x. Peacock lost control of the ATV at or near the Location.

x. Five passengers, including Peacock, were ejected from the vehicle.

x. Peacock was seriously injured in the accident and was transported by air ambulence to Navicent Health Center.

COUNT I - Premises Liability (Twin Creeks)

x. Twin Creeks owned and/or controlled the Property at or adjoining the location.

x. Twin Creeks permits use of the Property for hunting and recreation.

x. On information and belief, Twin Creeks was on notice of the use of the Property at or adjoining the location in a manner that was dangerous, specifically by the use of unlicensed and inherently dangerous off-road vehicles by minors, and willfully or maliciously failed to guard or warn against such use. See OCGA § 51-3-25.

x. In the alternative, Twin Creeks breached a duty under OCGA §§ 51-3-1 or 51-3-2.

x. As a direct and proximate consequence of said breach or breaches of duty, Peacock suffered an injury for which Lucas should be entitled to recover special damages in the form of medical expenses in the amount of at least $XXX, which continue to accrue, as well as general damages for Peacock's pain, suffering, and emotional distress in an amount to be determined at trial.

COUNT II - Negligent Entrustment and Supervision (Ussery and Hayes)

x. Ussery and Hayes had a duty of ordinary care in the supervision of a minor child and the entrustment of the ATV on March 15, 2020.

x. Ussery and Hayes breached their duty or duties and, as a direct and proximate consequence, Peacock suffered an injury for which Lucas should be entitled to recover special damages in the form of medical expenses in the amount of at least $XXX, which continue to accrue, as well as general damages for Peacock's pain, suffering, and emotional distress in an amount to be determined at trial.

x. Said breaches of duty also constituted a violation of Georgia law and, accordingly, were negligence per se.

WHEREFORE, Plaintiff respectfully prays that summons issue and be served with the foregoing Complaint as provided by law, that six months of discovery be had upon Defendants' answer, that the matter be tried to a jury and judgment entered in favor of Plaintiff, that the costs of the actio be cast upon the Defendants, and that the Court grant such other and further relief as it deems proper and just.
