* Medical:

Almost 50 yo, spine and concussion with pre-existing.

2020-08-26 Per Wellstar ER no LOC but hit head, complains back, hand, and leg pain post roll over MVC, Hx lumbar fusion, no acute Fx or traumatic dislocation in CT, some degenerative, "no obvious traumatic injuries," ordered fu unrelated cardiology findings. Oriented and no distress, tender to palp. NB client already on pain management.

Maloon treated for concussion, vestibular dysfunction and mild hearing impairment, tinnitus, migranes, cognition. MRI shows white matter changes but consistent with age, no significant abnormality. Later records note he is treating ortho for neck and shoulder pain, but initial visit reported pain in lumbar spine as exacerbation of previous condition. Anxiety etc. Notes amnesia re the actual event.

Per Maloon He's pretty level, at status quo or "MMI if you like," but still with lots of deficits, no further testing required. Need to move on, no more management, cognitive impairment and headaches and vestibular.

AOI did injection and then total arthroplasty C5-6 Op note shows osteophytes compressing cord, consistent with our claim per SKL but note no misalignment in ER CT.

2008 on job back injury, treating with narcotics ever since, losts of prior and post. Guy takes a LOT of pain medication.

Urology related? Look prior.

* Liability

** Skiles depo:

TN resident, TN license
SSN not given at deposition
CDL April 2019
no formal driver training, read the CDL manual
some ACPA training re operation of a concrete truck
but formal training was mostly re job site
NBIS training POST accident, insists not remedial
driving training not much more than some informal with other drivers
start with PP July 2018
not full time driver, sometimes works a "line pump"
Jason Pitt is direct supervisor - regional operations manager
medically qualified
Route Chatanooga --> Cumming or Canton --> accident
gave a ticket for the job, doesn't handle billing
pre-trip inspection paperwork
Caleb Nelson was his supervisor at the time, no longer employed 423-991-2438
Day started at probably 5a
pled no contest
admits fault, no contrib fault

* Experts

** Named

Navarro 
McCord 
Gingris 
Reiss

** Treating

Maloon
French
Kornfield [pain]
Ellner [pain]
Malcom

** NOT IDENTIFIED

Buchanan
mikenapier@truckingexpert.com 478-501-3272 cell

* todo

** Medical

[ ] Urology and intimacy issues unrelated? He denies related but it's unclear in my opinion.

[ ] Review Combier timeline etc

[ ] Review records with SKL re expert designations

** [ ] 6.4


  [ ] fu denial of smj in rfas? denial based on information and belief - what is the basis for the insurer's argument against direct action?

* [ ] misc other issues:

Policy re admit responsibility
Know anyone ever disciplined
Dash cam?  Why not?
Conversations with insurance.
Crabtree finding woman in the video?
other insurance
SS records, Hinrich was waiting on

Important to Steve

11 log
invoice
safety guy left

joint and several

30b6 of the insurance company on underwriting, audits, coverage
who did surveillance

[ ] long memorandum in file re FF

[ ] Review Combier timeline and summary

[ ] we got copies of non-party records, do we need to get them reviewed, record is very complicated

[ ] look at private carrier issue




