* Sarai Last Will

LAST WILL OF SARAI AGUAYO

I, Sarai Aguayo, also known as Sarai Aguayo Garcia and Sarai G. Aguayo, a resident of White County, Georgia, being of sound and disposing mind, declare this to be my last will and hereby revoke and cancel all prior wills and codicils.


1.	I am not married.

2.	I have two living children, the issue of my former marriage, which terminated in divorce, as follows:

Name					Date of Birth

SABRIAN KHALIL HOWARD                   April 15, 1999
NAMIAH UDAY HOWARD                      April 24, 2002

3.	Notwithstanding any provision of this will to the contrary, I specifically direct that under no circumstances shall any part or interest in my estate vest in or be taken by Namiah Uday Howard. It is my wish, but not my direction, that Sabrian Khalil Howard provide for and care for his brother Namiah, including by sharing in the proceeds of my estate, as he deems appropriate.

4.	Accordingly, I give, bequeath, and devise all of my properties, real, personal, and mixed, wherever located, and all rights and interests which I may be entitled to devise and bequeath, to Sabrian Khalil Howard, or to his issue, per stirpes.

5.      I make this will in contemplation of the possibility of a subsequent marriage and the birth or adoption of additional children, and do not intend for this will to be revoked by my marriage, remarriage, divorce, or the birth or adoption of children. I intentionally have not provided for my spouse by any marriage, or for children born or adopted after the execution of this will.

6.	In the event SABRIAN KHALIL HOWARD predeceases me with no issue, I direct that my estate be distributed to my heirs according to the laws of Georgia relating to intestate succession, except that, as set forth above, I direct that no part or interest in my estate vest in or be taken by Namiah Uday Howard, or any other current or former husband, who shall for all purposes herein be deemed to have predeceased me.

7.	I direct that all my debts, including funeral expenses and expenses of my last illness, be paid as soon as it is legally possible to do so, provided that no debts barred by the statutes of limitation or discharged in bankruptcy are to be paid.

8.	I nominate and appoint my son, SABRIAN KHALIL HOWARD, as the executor of this will, to serve without bond. 

9.	The executor shall not be liable for any loss, cost, damage, or expense sustained through any error of judgment or in any other manner except for and as a result of the executor’s bad faith or gross negligence.

10.	In the administration of my estate, I authorize my executor:

a.	To retain, purchase, or otherwise acquire without restriction or limitation, any stocks, bonds, notes, or other securities, or any other variety of real or personal property, including interests in investment trusts, the holding of which he deems in the best interest of my estate, even though such property would not otherwise be of a character suitable for investment by fiduciaries, or is unsecured, unproductive, speculative, or of a wasting nature;
b.	To sell, lease, pledge, mortgage, transfer, exchange, convert, or otherwise dispose of, or grant options with respect to, any real or personal property at any time forming a part of my estate, in such a manner, at such times, for such purposes, for such prices, on such terms, and subject to such conditions as he may deem advisable;
c.	To manage, operate, repair, maintain, and improve any real property at any time forming a part of my estate in such a manner as he may deem in the best interests of my estate;
d.	To borrow money whenever, in his judgment, he deems it advisable for the protection, preservation, or improvement of my estate, and correspondingly, to mortgage or pledge as security any property forming part of my estate;
e.	To compromise, settle, or otherwise adjust any claims or demands in favor of or against my estate;
f.	To exercise any of the powers conferred on executors under the laws of the State of Georgia, and
g.	To perform any other act which he may deem necessary or desirable for the execution or discharge of any powers or duties granted to or imposed upon him, whether by the terms of this will, or by law.

11.	I declare that in the event that, for any reason, any part of this will or any provision of this will is construed to be invalid, the invalidity of any such part or provision is not to be considered or held to impair any other disposition of my property in this will.

12.     In addition to revoking prior testamentary instruments, I hereby also and expressly revoke The Aguayo Family Trust of July 1, 2013, pursuant to Art. V Sec. 5.A of that document. As Trustee of said living trust, I acknowledge delivery of this revocation and waive further formalities relating to revocation, if any. All property funded to that trust, real or personal, wherever found, shall be and is hereby delivered to me and transferred to my own name and ownership.

In witness, I hereby sign my name to this my last will on this _____ day of __________, _____, at Dahlonega, Lumpkin County, Georgia, in the presence of _________________ and ________________, attesting witnesses, who sign their names here at my request and in my presence.



____________________
Sarai Aguayo

Attestation

On the date last written above, Sarai Aguayo, known to us to be the person whose signature appears at the end of this will, declared to us, the undersigned, that this instrument was her will. She then signed the will in our presence, and at her request, in her presence and in the presence of each other, we now sign our names as witnesses.
  


_____________________,  residing at  __________________________________       
[Signature]                        		     [Street, city, state] 



_____________________,  residing at  __________________________________      
[Signature]                   			    [Street, city, state] 



Self-Proving Affidavit

STATE OF GEORGIA

COUNTY OF DEKALB

Before me, the undersigned authority, on this day personally appeared to me Sarai Aguayo, _______________, and _______________, known to me to be the testator and witnesses, respectively, whose names are subscribed to the annexed or foregoing instrument in their respective capacities, and, all of said individuals being by me duly sworn, Sarai Aguayo, testator, declared to me and to the witnesses in my presence that said instrument is the last will and testament or a codicil to the last will and testament of the testator and that the testator had willingly made and executed it as a free act and deed for the purposes expressed therein.  The witnesses, each on oath, stated to me in the presence and hearing of the testator that the testator had declared to them that the instrument is the testator’s last will and testament and that the testator executed the instrument as such and wished each of them to sign it as a witness; and under oath each witness stated further that the witness had signed the same as witness in the presence of the testator and at the testator’s request; that the testator was 14 years of age or over and of sound mind; and that each of the witnesses was then at least 14 years of age.



_______________________					
Testator						

_______________________			
Witness
							
_______________________			
Witness


Subscribed and sworn before me by the said Sarai Aguayo, testator, and by the said ______________ and _____________, witnesses, this ___ day of ____. _____.



[seal]
____________________
Notary Public

My commission expires:

