* Complaint

IN THE STATE COURT OF FORSYTH COUNT
STATE OF GEORGIA

Steven Leibel, P.C.,

Plaintiff,

v.

Progressive Premier
Insurance Company of
Illinois,

Defendants.

MOTION FOR INJUNCTIVE RELIEF AND SANCTIONS PURSUANT TO OCGA 9-15-14

COMES NOW the above Plaintiff and files his Motion for Sanctions Pursuant to OCGA ยง 9-15-14, showing the following:

x. Plaintiff filed his Complaint in the above matter on March 9, 2021. Service was perfected on Progressive Premier Insurance Company of Illinois ("Progressive") on or about March 12, 2021. See Sheriff's Entry of Service, filed March 16, 2021.

x. Progressive filed its Answer and Cross-Claim on April 9, 2021.

x. On information and belief, on or about August 6, 2021, Progressive filed a certificate of service in this matter.

x. Plaintiff did not receive service as provide in OCGA ยง 9-11-5 but discovered the filing only on checking the docket to see if a notice of hearing had been filed on the pending motion regarding the default in this matter.

x. On review of Odyssey to see whether there was a problem in the system that might have prevented the document from being served, Plaintiff's counsel noted that the service contact entered into the system by the filing party, ie., Progressive, was "sleibel@ihateleibel.com."

x. Plaintiff's counsel notified counsel for Progressive. See Email from Joni Shoemaker to Lowell Fitts, October 28, 2021, attached as Exhibit A.

x. Counsel for Progressive did not apologize and, instead, disclaimed any responsibility for this improper and impliedly defamatory entry into the electronic filing system, claiming that it was "set up in Odyssey," ie., blaming either Plaintiff's counsel or the staff at Odyssey for the problem. See Email from Lowell Fitts to Joni Shoemaker, October 29, 2021, attached as Exhibit B.

x. As of the date of filing of this motion, the issue has not been corrected; counsel for Progressive has simply added the proper service contacts to the record. See screenshot, attached as Exhibit C.

x. This Court has the authority under OCGA 

x. The Court should order Counsel for Progressive to correct the improper service address in the Odyssey system and sanction this conduct pursuant to OCGA ยง 9-15-14, its inherent contempt powers, or other applicable law.
