* 30b6

This is the deposition of Beri Orlando, as corporate representative of Walmart Stores East, LP, taken pursuant to notice and agreement of counsel under the Georgia rules of civil practice for all purposes including discovery, cross-examination, and use at trial consistent with those rules. Under the federal rules and by stipulation of the parties, objections will be reserved until the first lawful use of the transcript of these proceedings, except as to privilege, form of the question, and responsiveness of the answer. We have also agreed to take this deposition by videoconference, with the officer administering the oath in a different physical location than the witness. Is all that agreeable, and do you want to make a record regarding signature?

Please swear in the witness.

Good morning, XX, my name is Paul Menair and I represent Madeline Young in a lawsuit against Walmart Stores East, LP and some other entities arising from a slip and fall incident at a Walmart store. If I say "Walmart" today, I will most likely be refering to either the physical location where my client fell or to Walmart Stores East, LP, or both, but if there is any confusion please ask me to clarify, okay?

I'll also note that we have counsel here for one of the Coca-Cola bottling companies and for convenience I may just refer to that entity as Coke, okay?

And you understand that you are here as the designated corporate representative of Walmart Stores East, LP, correct?

And that means you will be testifying on behalf of the company today, correct?

I may ask you questions about you personally, and I will try to make it clear when I am asking you to speak on behalf of yourself as opposed to the company. For example, in the beginning I will be asking some questions about who you are and what you do for Walmart. But if there is any confusion here, again, feel free to ask me to clarify a question. 

Could you please state and spell your full name for the record.

What is your position with Walmart?

What company name is on your paycheck, is it Walmart Stores East, LP?

Who do you report to? Title?

How many direct reports do you have? What are their names?

Tell me a little bit about how you came to work for Walmart, and how you got to be where you are today with the company?

I know you probably met with counsel to prepare for today's deposition, and I don't want to know anything that was said in that meeting, but I do want to know if you reviewed any documents, either in that meeting or in general, to prepare for today?

Did you meet with anyone other than counsel to get ready for today's deposition?

Let's start with my client's fall, which happened in March of 2018. How, personally, did you come to learn about my client's fall?

Who have you talked to about the fall?

We'll come back to this in detail later, but what is your understanding of what happened?

Are you aware of any other falls that may have happened at that store hear a Coke cooler?

Are you able to tell me anything about those?

What about a fall near the reverse osmosis machine?

Cheese counter?

Any other falls that have happened at that store that you can tell me about?

Do either of those entities have anything to do with the day to day operation of the store where my client fell?

There were interrogatory responses filed on behalf of a number of Walmart  entities. Were you involved in preparing those responses? Who else was? Did you review them for today?

Delores Rider
Danny Norris
Austin Dalton
Robin Seabolt
Colton Major

Who are they, what do they know? Still employed? Help us find?

Is there someone who worked at the Walmart around that time named Tammy Larson?

Could she also have been a witness?

Does she still work for Walmart? Help us locate her?

[] LKA

I understand that there was an internal investigation by Walmart Claims Services, conducted via telephone, and I don't want to know the details of what happened with the investigation of this incident after it got to risk management. But can you please tell me what triggers that notification, and how it generally works?

We asked about statements and there was a response over objection that identified and provided statements. Do you know whether any statements were withheld pursuant to objection?

4x4

Let's get to some more detail about accident prevention. My understanding is that all of the employees at Walmart are expected to inspect for and clean up spills and other hazards. Correct?

Tell me how that works.

Does Walmart maintain any records of those daily activities, cleaning the stores?

Is there also cleaning overnight?

Tell me about that?

[ ] logs

And Walmart does not use any third party vendors for routine cleaning of floors or daily inspection and maintenance, correct?

Are there any employees specifically assigned to floor cleaning during the day?

How often are sweeps conducted?

Is there any way we could reconstruct when sweeps happened on the day my client was injured?

How are they conducted?

What happens when a spill is identified?

Have you viewed the videotape of the fall?

Let's take a look.

It looks to me like she slipped, as opposed to tripping over herself. Does it look that way to you?

Identify people responding.

Talk to me about what's going on in the video.

What investigation was conducted regarding the condition of the floor? Would have been conducted?

Was cleaning conducted?

Was there any warning to Wal-Mart prior to my client's fall of the condition, whatever it was, that caused her fall? When?

So the fall was Wal-Mart's first indication that there might be a problem?

Does Wal-Mart know of anything that should have put my client on notice that there was a hazard she might slip on?

What could my client have done to avoid the fall?

Contributory negligence.

Do we have any way of knowing where that water came from?

What do you think, personally?

[ ] Andrea

Do you know who owns the real estate where this store is located?

Is there an actual lease or rental agreement?

There was no wet floor sign that day prior to the fall, correct? Or any other specific indications of a hazard in that area?

Do you know how long the water had been on the floor?

Is there general signage at Wal-mart stores telling people to be careful how they walk, or where they walk?

The area where my client fell was an area where she was permitted to be, correct?

And this is an area where Walmart employees pass through while performing their duties, correct?

And they are generally required, as part of those job duties, to be on the lookout for hazards like water on the floor, correct?

What does "SAFE" stand for? Tell me about that safety program?

Who receives the monthly "topic" publications regarding the SAFE program?

Tell me about the "Safety Sweep" page. How often?

Any way to know whether any safety sweeps happened the day of my client's fall, and when?

The area where my client fell was a high traffic area, correct?

Any way to know how often those sweeps happened on the day of my client's fall?

Was Walmart on notice of any issues with those Coke coolers?

Did Walmart ever notify Coke about issues with those coolers?

Was the area where my client fell slip resistant? Why not?

Tile floor?

What is the Towel in Pocket program?

Are there any people we haven't talked about who might have direct knowledge relevant to this case, witnesses or people who interacted with my client or the floor she fell on? People who knew about the Coke cooler or anything else that might have caused the water on the floor?



Ever any issues with condensation?

Where are the various documents we've talked about maintained? Claims management? Do they also have the video of the fall? Asset protection office.
Asset protection manager. Brandon Enclsey

Authenticate witness statements. Is this a complete and accurate copy of a record maintained by Wal-Mart Stores, LP as part of its regular business? Was it made in the ordinary course and regular practice of Wal-Mart's business? Was it created close in time to the incident when my client fell? And you are not aware of any other statements relevant to this case?

Authenticate photos. Who took them?

Other than the folks we've talked about, do you, personally and/or on behalf of Walmart, know of anyone who might know anything about my client's fall, how it happened.

Do you, personally and/or on behalf of Walmart, know of any third-party vendors or other persons or entities, other than Coke, who might have some involvement in the events leading up to my client's fall.

I asked for a list of other incidents, and we were agreeable to a protective order. I don't remember if one has been entered yet, but subject to that, will you produce?

I'm going to ask about affirmative defenses. Walmart denies that it was negligent in any manner in its tenth defense. How do you know? What's the factual basis for that defense?

What's the factual basis for the 8th and 9th defenses, which allege contributory negligence by my client?

Same question, 11th defense, assumption of the risk

Statute of limitations?

Laches?



* Witnesses

Intro, what did you do to prepare, what did you look at.

Statement

Is that your handwriting?

Is that your signature?

Is this an accurate copy of the statement you made on X date?

Is it complete? Were there any other documents you generated?

Any facts you left out.

Are you currently employed by Wal-Mart?

On the day my client fell, what was your job title?

This is about a fall, correct?

Were there any other falls that day?

Describe the person who fell.

It says... 

Did you look to see if you could find what this person fell on?

Do you know how she fell? Did you ask her? Did you ask anyone else?

What can you tell me about her physical condition immediately after the fall.

Walmart policy requires you to be on the lookout for slip hazards, correct? Tell me about that.

Photographs

Do you know who took these photographs?

Is there anything visible in these photographs that might help explain the fall?

Do these photographs refresh your recollection about the fall>

Did you do any other investigation?

Was anyone with you while you prepared your statement?

Did anyone help you decide what to right?

Is there anything you intentionally left out?

What are the names of any other people who might know something about this fall, employees of Walmart or otherwise.

Do you know who took my client's statement?

Who have you talked to about the fall, other than counsel or claims management.

Have you provided any other statements relating to this case, written or recorded?

Video

Is there anything that we haven't talked about relevant to this fall?


