* Walmart

MADELINE YOUNG v. WALMART, INC. F/K/A WAL-MART STORES, INC., WAL-MART
STORES EAST, LP (DELAWARE), THE COCA-COLA COMPANY, COCA-COLA BOTTLING
COMPANY UNITED, INC., AND DAHLONEGA GROUP, LLC, State Court of Fulton
County, Civil Action No. 20EV001511, J. Diane E. Bessen

Delores Rider, Danny Norris, Dalton Austin, Robin Seabolt, Colton Major

Witness list 2020-08-10

Donna Gamblin 706-973-7478
Tanner Young 706-429-2958




Colton Major (678) 963-6874

Robin Seabolt - lots of them in GA, without more I'm just cold calling.


Protective order



offer of settlement 750k?

Apparently they changed the coolers - they initially admitted liability - get log of calls to her - bad faith letter?

Delores Rider, Colton Major, Dalton Austin, Robin Seabolt, Danny Norris, Walmart and KO 30b6

jxn, venue, and SOL defenses (served inside statute) but no defense to
service? Wait on discovery responses.

Delores Rider Cashier 1. Danny Norris Asst Manager 3. Dalton Austin Asst
Manager Robin Seabolt Asst Manager Colton Major Associate 2.

Did we get the confidential docs? Did we get the proper substitutions of
party done?



Rider and Walmart 30b only on 7/22. Hold on 7/29? Discovery runs 7/1.

---

Prior incident (he's got them mixed up)

Times wrong, or he has them mixed up. African american young woman.

2017 new bottling company
opposite side Subway is where *2d* happened

Tammy Larson potential witness

up to mgt to notify KO

prior incident water trail
repairs to cooler after first time, maintenance did come
talked to him about the leaking

uniform / PRIOR BOTTLING COMPANY

DIFFERENT STORY

Drip from flowers...

different coke machines, first got fixed, etc.

[ ] review records re other falls
