#+title:      Bromaghim
#+date:       [2023-12-29 Fri 09:21]
#+filetags:   :casenotes:
#+identifier: 20231229T092133
---

** /Notes/:

Don't use Todd. DO NOT use comp file.

No records found re phone.

FF Melissa Bromaghim 210-842-5432 [other two kids don't talk to her]

Excess policy of 1MM, what OCN had to settle on 2020-04-14 was 80k, they sent a 100k offer of settlement right after.

NB Responses talk about client abusive behavior at scene and "changed behavior" ie. faking when EMS got to the scene.

Rear end collision,

Charge of discrimination filed 2019-05-29. We do not represent her on this.

[ ] redact expert depositions

[ ] redact medical records



---

CONFIDENTIAL MEDIATION MEMORANDUM

This is tort case arising from a rear-end collision. Our client was stopped in a left turn lane waiting to turn and struck from behind. We filed suit in January of 2019 against the defendant driver and the vehicle owner in state court. We dismissed the vehicle owner. Then we dismissed the entire case at the threshold of trial, immediately before jury selection. We subsequently refiled in federal court, where there is jurisdiction because my client now lives in Tennessee.

In state court, the Defendant submitted an offer of settlement for $100,000 in 2020. A year later we sent them an offer of settlement at $295,000, then two years after that immediately before the state court trial they sent an offer for $150,000. No offers of judgment have been exchanged in federal court.

Stephanie was transported from the scene of the accident in significant pain. She had preexisting fibromyalgia and psoriatic arthritis. Due to the accident she was unable to continue her former treatment for those conditions. We concede she had medical issues prior to the wreck, but her condition significantly worsened after the collision. She has been unable to work and has spent the years since the collision in significant pain and psychological distress. Her related medical expenses are $295,666.66.

Sitting here today, we could not resolve this matter for $295,000.00. Since we sent our $295,000 offer, it has become clear that my client's condition is unlikely to significantly improve and she will be disabled for the remainder of her life. They have $1,500,000 in coverage, and our inclination is to open mediation with a policy limits demand. However, we are willing to negotiate below that amount.

We have been unable to get opposing counsel to meaningfully discuss settlement since this case was refiled, so we contacted the court as suggested by the local rules to get this case into mediation. We believe there is significant value in this case, but we also understand there is potential risk as some jurors may be inclinded to disbelieve or may be unsympathetic to a plaintiff with a chronic pain syndrome.

We look forward to working with you to resolve this matter.
