#+title:      williams julie
#+date:       [2024-04-09 Tue 12:38]
#+filetags:   :casenotes:
#+identifier: 20240409T123822

** /Representation/:

Counsel for Plaintiff: [[https://www.gabar.org/MemberSearchDetail.cfm?ID=MzY0NjQ3][Joseph A. Homans, Joseph A. Homans, PC]]

* RECORD APPENDIX TO DEFENDANT'S MOTION FOR SUMMARY JUDGMENT
A. Complaint for Damages
B. Affidavit of Chad Williams with exhibits
1. Georgia Secretary of State - Lamplighter Inc.
2. Trade Name Registration - Lamplighter, Inc
3. Warranty Deed 205 Rainhill Station
4. Tax Record 205 Rainhill Station
C. Affidavit of Julie Williams with exhibits
1. Lease
2. Photograph of Kitchen
3. Letter from Homans to Edelberg Sept. 9, 2023
4. Letter from Homans to Edelberg Sept. 26, 2023
5. Security Deposit Refund
6. Move Out Report
7. Letter from Edelberg to Homas Oct. 23, 2023
D. Plaintiffs' Response to Defendant's First Interrogatories to Plaintiff
* DEFENDANT'S MOTION FOR SUMMARY JUDGMENT AND ATTORNEY FEES
COMES NOW Defendant Julie Williams, erroneously captioned as "d/b/a Sellers Realty of Dahlonega" and files her Motion for Summary Judgment, pursuant to OCGA § 9-11-56, respectfully requesting that the Court grant summary judgment as to this entire matter on the ground that she is not a proper party to the action or, in the event she is a proper party, on Plaintiffs' claims in their entirety. In support of this motion, Defendant is contemporaneously filing her Brief in Support of Defendant's Motion for Summary Judgment, a Record Appendix to Defendant's Motion for Summary Judgment containing exhibits to the motion, and her Statement of Material Facts Showing No Genuine Issues Exist for Trial. As shown in her brief of authorities, Defendant further submits that this action is frivolous, ie., that it consists entirely of claims with respect to which "there exist[s] such a complete absence of any justiciable issue of law or fact that it could not be reasonably believed that a court would accept the asserted claim" (OCGA § 9-15-14(a)) or "[lack] substantial justification" (OCGA § 9-15-14(b)).
WHEREFORE, Defendant respectfully prays that judgment be entered as a matter of law dismissing the case in its entirety or, in the alternative, in favor of Defendant on Plaintiffs' claims in their entirety, that the Court find Plaintiffs' claims to have been frivolous and order a hearing at its earliest convenience to determine an award of attorney's fees and expenses of litigation, and that the Court grant such other and further relief as it deems proper and just.
* BRIEF IN SUPPORT OF DEFENDANT'S MOTION FOR SUMMARY JUDGMENT
COMES NOW the Defendant Julie Williams, improperly identified as "Julie Williams d/b/a Sellers Realty of Dahlonega," ("Williams" or "Defendant") and files her Brief in Support of Motion for Summary Judgment, showing the following:
** Facts
This civil action was filed on January 18, 2024 in the Magistrate Court of Lumpkin County, Georgia. (Complaint for Damages ["Complaint"], Records Appendix to Defendant's Motion for Summary Judgment ["Appx."] Ex. A.) In the Complaint, Plaintiffs Howard Stanley King, Jr. and Karrie King (the "Kings" or "Plaintiffs") allege that Williams operates an unincorporated business under the trade name "Sellers Realty of Dahlonega" (Id. at ¶ 1), that she leased certain property located in Dawsonville Georgia (the "Premises") to the Kings (Id. at ¶ 2), and that she improperly retained certain funds following a fire at the Premises (Id. at ¶¶ 3-7). In the action, they seek $7,295.00, some portion of which would be treble damages for funds they allege were improperly withheld from a security deposit, plus their attorney fees. (Id. at ¶ 8.)
Sellers Realty of Dahlonega
The initial premise of this claim is, in fact, inaccurate. Williams is the employee and officer of an incorporated business entity named Lamplighter, Inc. ("Lamplighter") (Affidavit of Chad Anthony Williams ("Chad Williams Aff."), Appx. Ex. B, at ¶ 3; Affidavit of Julie M. Williams ("Julie Williams Aff."), Appx. Ex. C, at ¶ 2.) The trade name "Sellers Realty of Dahlonega" is a properly registered trade name of Lamplighter. (Chad Williams Aff. at ¶ 4; Julie Williams Aff. at ¶ 2.) Williams does not conduct and has not ever conducted her personal business under that trade name. (Chad Williams Aff. at ¶ 5; Julie Williams Aff. at ¶ 4.) Accordingly, she is not a proper party to this action.
The Premises
The Premises at issue in this action are located at 205 Rainhill Station Drive in Dawsonville, Georgia. (Chad Williams Aff. at ¶ 7. The owner of the Premises is 43 Summer Street LLC, and entity that neither Lamplighter, Inc. nor Julie Williams has any legal or equitable interest in. (Chad Williams Aff. at ¶ 7-8; Julie Williams Aff. at 3.) 43 Summer Street LLC is a client of Lamplighter, which is a rental management company. (Id.)
The Lease (Formation and Parties)
The Kings entered into a lease with respect to the Premises on August 13, 2022, subsequently amended on May 17, 2023 (hereinafter collectively the "Lease"). (Complaint at ¶ 2 and Exhibit A thereto; Julie Williams Aff. at ¶ 5 and Exhibit 1 thereto.) The Lease is signed by Sellers Realty of Dahlonega as Landlord, Listing Broker, and Leasing Broker (on behalf of the tenant as customer not client); with Williams signing the Lease only in her capacity as the "Broker/Affiliated Licenscee." (Julie Williams Aff. at ¶ 6.) The Lease identifies Sellers Realty of Dahlonega as both the Manager and as the "person authorized to act for and on behalf of the Owner." (Julie Williams Aff. at ¶ 7.) Williams was authorized to sign the Lease on behalf of Sellers Realty of Dahlonega. (Julie Williams Aff. at ¶ 8.) The responsibility of a broker and its affilliated licensees and employees to a tenant is strictly limited by the Lease to what is expressly provided for in the Brokerage Relationships in Real Estate Transactions Act, OCGA § 10-6A-1 et seq. (Lease § B.24.a.)
The Lease (Terms)
As amended, the Lease provided for a monthly rent in the amount of $2,690.00 and was to terminate on July 31, 2024. (Lease at Amendment #1.) Rent was to be paid in advance. (Lease at §§ A.3.b and B.3.) The Lease also provides for a security deposit. (Lease §§ A.4 and B.4.) The holder of the security deposit has the right to deduct from it the cost of cleaning if the Premises are left unclean at the termination of the Lease. (Lease § B.4.e.) The Lease provides a schedule of fees for such cleaning but places the tenant on notice that these fees are "SUBJECT TO CHANGE WITH ACTUAL COSTS OF MATERIAL AND ADDITIONAL LABOR CHARGES." (Lease at Additional Page 1.) The Lease provides for termination on notice by the tenant in the event that the Premises are rendered uninhabitable by fire. (Lease at § C.7.) However, the tenant has no rights under the lease to hold over past its expiration or termination, and in the event of holdover occupation, the Lease provides for a holdover fee of $100.00. (Lease §§ A.14 and B.14.)
The Fire
A fire of unknown origin occurred in the kitchen at the Premises on September 9, 2024; it originated in a gas stove. (Julie Williams Aff. at ¶ 9.) In responding to the fire and extinguishing it, chemical fire extinguishers were used which left a substantial amount of chemical dust residue. (Julie Williams Aff. at ¶ 10 and Ex. 2 thereto.) Instead of cleaning up this residue, the Kings vacated the Premises to stay in a hotel, leaving their belongings. (Julie Williams Aff. at ¶ 11.)
On September 20, 2023, Julie Williams received via email correspondence from Joseph Homans, attorney for the Kings, asserting that the Premises were uninhabitable due to "substantial damage" associated with the fire and demanding rent abatement as of September 9, 2023. (Julie Williams Aff. at ¶ 12 and Ex. 3 thereto.) The Kings subsequently agree to a termination date of September 16, 2023. (Julie Williams Aff. at ¶ 13 and Ex. 4 thereto.) However, the Kings' property remained in the Premises and was not fully removed until September 30, 2023. (Julie Williams Aff. at ¶ 14.) Lamplighter was not aware that the Kings had vacated the premises until October 3, 2023, at which point they immediately entered and took possession on behalf of the owner. (Julie Williams Aff. at ¶ 15.)
In their memorandum on return of the security deposit, Lamplighter applied seventeen days of holdover tenancy to the $2,500 security deposit and also assessed feeds for carpet cleaning, rekeying, fridge cleaning and trash removal, for a total of $2,400 paid to the Owner; $100 was returned to the Kings. (Julie Williams Aff. at ¶ 16 and Ex. 5 thereto.) Lamplighter also rebated 15 days of prepaid rent (the amount prepaid for September 16 through 30) to the Kings, in the amount of $1,345.00, for a total payment to them of $1,445.00. (Id.) A substantial amount of cleaning was necessary to make the Premises fully habitable but it was subsequently re-let without issue. (Julie Williams Aff. at ¶ 18.)
All statutory conditions precedent to withholding a portion of the security deposit were complied with, specifically the preparation of a move out inspection report (OCGA § 44-7-33(b)(1); Julie Williams Aff. at 19-20) and presentation of a statement and the amount due within 30 days (OCGA § 44-7-37; Julie Williams Aff. at 21). The funds in this case were properly withheld and the proper amount due was returned to the Kings. As set forth in more detail below, Defendants seek either dismissal of the action or summary judgment on Plaintiff's claims in their entirety.
** Argument and Citations of Authority
*** Standard of Decision
Summary judgment is appropriate where no genuine issues of material fact exist for determination by a jury and it appears that a party is entitled to judgment as a matter of law. OCGA § 9-11-56. Construction of a ctract is a question of law. OCGA § 13-2-1.
*** Julie Williams Is Not a Proper Party to this Action
Under the express terms of the lease, Ms. Williams' only personal role in the relationship with the Kings was as the affilliated licenscee of a broker, and her liability, if any, would be limited to what is provided for in OCGA § 10-6A-1 et seq., which establishes duties relating to the initial brokerage and formation of lease agreements and not the subsequent management of the property. Regarding the transactions and occurances giving rise to this action, Ms. Williams' relevant relationship was as an officer of the property manager. It is a fundamental principle of Georgia law that a corporation is a separate legal entity and, absent a proper showing to disregard the corporate the corporate form, its owners or principals are not proper parties to a proceeding that should be against the corporation. Global Diagnostic v. Diagnostic Imaging, 284 Ga. App. 66, 68-69 (2007). Although an officer or agent of a corporation may be liable in appropriate circumstances for independent tortious conduct, the breach of a contract is not itself a basis for liability in tort. See Wrigley v. Nottingham, 111 Ga. App. 404 (1965). To the extent that the claims in this action are premised on a statute and not simply the lease itself (ie. OCGA § 44-7-35), that statute plainly provides that the landlord is the proper party, and Ms. Williams plainly is not the landlord.
*** The Amount Tendered to Plaintiffs Was Proper and Justified
The Kings claim that they should have been paid $3,845 instead of $1,345 but do not appear to be contesting Lamplighter's calculation of the rent abatement portion of the payment. (Complaint at ¶ 8.)[fn][The amount of security deposit they allege is $2,595 but this appears to be a scrivener's error as the actual amount was $2,500. {CITE}) Accordingly, their objection appears to be to the amount withheld from the security deposit, which they object to in its entirety. However, those funds were properly withheld.
To begin with, the Lease plainly authorizes a holdover fee. Although the Kings would apparently construe the Lease as permitting them to terminate on a date certain but continue to use the property as storage for their personal property, this is nonsensical. They continued to occupy the premises as holdover tenants, for the simple reason that their property was there and, accordingly, the landlord was unable to take possession, clean, and relet to the property. Absent a showing of delivery of possession, the Kings were holdover tenants for every day after the termination of the Lease, by its plain language.
Moreover, the cleaning fees assessed were also justified under the Lease. The Premises were in need of cleaning, and Defendant anticipates that the Kings will not dispute this. Although the Lease provides for specific fees, it plainly states that those fees are subject to adjustment, and Defendant submits the adjustment at issue here was reasonable under the circumstances.
*** Plaintiffs' Claim Under OCGA 44-7-35 Also Lacks Merit
OCGA § 44-7-35(c) provides that a landlord who improperly fails to return a portion of a security deposit may be liable to the tenant for treble damages plus attorney fees. Assuming for the sake of argument that Ms. Williams is a proper party to such a claim, which she denies, this claim lacks merit. To begin with, the amounts were properly assessed under the Lease, as set forth above. Moreover, the other statutory conditions precedent, a move out inspection and delivery of a statement and the amount due to the Kings, were complied with. OCGA §§ 44-7-33 through 44-7-35.
*** This Action Is Frivolous
Plaintiffs brought this action against the wrong party. By way of answer, this Defendant immediately put them on notice that she was not the proper party. The trade name "Sellers Realty of Dahlonega" is a duly registered trade name and has been for decades. The property at issue in this case clearly does not belong to Ms. Williams, and even if there was difficulty in determining who the owner or the property manager were (both matters or public record), this information has been available to Plaintiffs since Defendant answered on February 26, 2024. However, instead of attempting to join the proper party, Plaintiffs have insisted on pursuing what appears to be a vendetta against Ms. Williams personally. Their pleadings and discovery responses provide no basis for an allegation of piercing the corporate veil or attributing tort liability to Ms. Williams personally. The action is so lacking in merit as to be frivolous and an award of fees is justified.
** Conclusion
Julie Williams is not the proper party to the claims or the counterclaims in this action, which were asserted in an abundance of caution only in view of the possibility that the Court might somehow find a genuine issue of material fact as to whether she was leasing the Premises on her own account. The case should be dismissed in its entirety. Moreover, even in the event the Court were to determine that she is somehow the proper party, Plaintiffs' claims should still be subject to dismissal because they lack merit as set forth above.
* Chad Williams Aff.
AFFIDAVIT OF CHAD ANTHONY WILLIAMS
PERSONALLY APPEARED before the undersigned officer, duly qualified to administer oaths, CHAD ANTHONY WILLIAMS, who, on being sworn, deposed and testified as follows:
1. My legal name is Chad Anthony Williams, and I am over twenty-one years of age and otherwise competent to testify in the above matter, which I do of my own personal knowledge.
2. I am the Chief Executive Officer of Lamplighter, Inc. ("Lamplighter"), a Georgia Profit Corporation with its principal and registered offices in Lumpkin County, Georgia, which has been doing business in said county and in the State of Georgia since 1998. A true and correct copy of the entity's registration information as obtained from the website of the Georgia Secretary of State is attached as Exhibit 1 hereto.
3. Julie M. Williams, the Defendant in the action captioned above, is an employee and officer of Lamplighter.
4. Lamplighter has been operating under the properly registered trade name "Sellers Realty of Dahlonega" since 1998. A certified copy of the record of this registration with the Superior Court of Lumpkin County, Georgia is attached as Exhibit 2.
5. Julie M. Williams is not authorized to conduct her personal business under that trade name and to my knowledge has never done so.
6. The business of Lamplighter d/b/a Sellers Realty of Dahlonega is leasing and management of rental properties on behalf of property owners.
7. The property at issue in the above captioned civil action, located at 205 Rainhill Station Drive, Dawsonville, is owned by 43 Summer Street LLC. True and correct copies of the warranty deed and current tax record are attached as Exhibits 3 and 4, respectively.
8. Neither I nor Lamplighter have any legal or equitable interest in 43 Summer Street, LLC., which is simply a client of Lamplighter.
* Julie Williams Aff.
AFFIDAVIT OF JULIE M. WILLIAMS
PERSONALY APPEARED before the undersigned officer, duly qualified to administer oaths, JULIE M. WILLIAMS, who, on being sworn, deposed and testified as follows:
1. My legal name is Julie M. Williams, and I am over twenty-one years of age and otherwise competent to testify in the above matter, which I do of my own personal knowledge.
2. I am an employee and officer of Lamplighter, Inc., a Georgia profit corporation that does business under the registered trade name "Sellers Realty of Georgia."
3. I do not have any legal or equitable interest in 43 Summer Street, LLC, the owner of 205 Rainhill Station Drive, Dawsonville, Georgia (the "Premises"); that entity is a client of Lamplighter.
4. I do not and have never conducted personal business under the fictitious name "Sellers Realty of Dahlonega."
5. On August 13, 2022, Howard Stanley King, Jr. and Karrie King (the "Kings") entered into a lease agreement respecting the Premises, which was subsequently amended on May 17, 2023 (hereinafter collectively the "Lease"). A true copy of the Lease is attached as Exhibit 1 hereto and is also attached to Plaintiff's Complaint for Damages in this matter as Exhibit A thereto.
6. The Lease is signed by Sellers Realty of Dahlonega as Landlord, Listing Broker, and Leasing Broker (on behalf of the tenant as customer not client); my personal signature is on the Lease only in my capacity as the "Broker/Affiliated Licenscee." (Lease at ¶ 24 and p. 12.)
7. The Lease further identifies Sellers Realty of Dahlonega as the Manager and as the "person authorized to act for and on behalf of the Owner." (Lease at ¶ 26.)
8. I was authorized to sign the Lease on behalf of Sellers Realty of Dahlonega.
9. A fire occurred at the Premises on September 9, 2024; it originated in a gas stove in the kitchen of the Premises and its origin or cause is unknown.
10. In responding to the fire and extinguishing it, chemical fire extinguishers were used which left a substantial amount of chemical dust residue in the Premises. A copy of a photograph produced in discovery by the Kings is attached as Exhibit 2, and I am able to testify that it truly and accurately depicts the condition of the kitchen of the Premises immediately or a short time after the fire, which I personally observed.
11. Instead of cleaning up after the fire, the Kings vacated the Premises to stay in a hotel, leaving their belongings.
12. On September 20, 2023, I received via email correspondence from Joseph Homans, attorney for the Kings, asserting that the Premises were uninhabitable due to "substantial damage" associated with the fire and demanding rent abatement as of September 9, 2023. A true copy of said correspondence is attached as Exhibit 3.
13. The Kings subsequently agree to a termination date of September 16, 2023. See Correspondence of September 26, 2023 from Joseph Homans to Joy Edelberg, attached as Exhibit 4.
14. However, the Kings' property remained in the Premises and was not fully removed until September 30, 2023.
15. Lamplighter was not aware that the Kings had vacated the premises until October 3, 2023, at which point they immediately entered and took possession on behalf of the owner.
16. Lamplighter applied seventeen days of holdover tenancy to the $2,500 security deposit and also assessed feeds for carpet cleaning, rekeying, fridge cleaning and trash removal, for a total of $2,400 paid to the Owner; $100 was returned to the Kings. A copy of the Security Deposit Refund document is attached as Exhibit 5.
17. Lamplighter also rebated 15 days of prepaid rent (the amount prepaid for September 16 through 30) to the Kings, in the amount of $1,345.00, for a total payment to them of $1,445.00. Id.
18. In my opinion Lamplighter could legitimately have charged more for cleaning. However, the property was fully habitable upon being cleaned and has been subsequently re-let without issue.
19. A move out sheet was prepared within three days of the date when Lamplighter took possession of the premises as provided by OCGA § 44-7-33(b)(1) and prior to return of a portion of the security deposit to the Kings. See Move Out Report, attached as Exhibit 6.
20. To my knowledge, no request was made by the Kings to inspect the premises or the list and, in any event, the premises were vacated without notice.
21. Further written notice of the intent to retain a portion of the security deposit was provide to the Kings through their counsel. See correspondence from Joy Edelberg to Joseph Homans, October 23, 2023, attached as Exhibit 7.
* RULE NISI
Defendant having filed her Motion for Summary Judgment in the above captioned action, and same having been read and considered, the parties are hereby ordered to appear at ______ a.m./p.m. on the _____ day of ___________________, 2024, in Courtroom ___ and show cause why the relief sought in said motion should not be granted.
