#+title:      nelson curtis
#+date:       [2024-04-17 Wed 15:10]
#+filetags:   :casenotes:
#+identifier: 20240417T151048

** /Representation and Coverage/:

LI:  $2,000.000.00, Zurich American Insurance Co.

mediation offer was 87.5 

** /Notes/:

-->  analyze medical (crush injury), skl to call david atkins, medicset aside? PPD? UPDATE MED   

Christopher Tubbs, former Toyo employee, 479-562-2249


Discovery responses from ATS: They identify Bonine and Michael Woff (Environmental Health & Safety Manager). Refuse to answer re "inspection" as too vague. They contend Toyo "retained management and control responsibilities at the facility as well as instruction to its employees regarding use of the equipment at the facility." They did repair it, but Toyo maintained it? They contend we did not follow "established protocols for repair and maintenance of the curing press." Other incidents overly broad. Will supplement re procedures but contend that curing press power supply should have been deactivated. Contend no malfunction. They may have reports withheld for privilege. No material "relating to prevention of injury from a curing press." Confidentiality requirement for K with Toyo.
  
Get photographs

Tire tiering press

when tire is curing, different areas in mold pulls air out, when clogs happen there are issues, when into the press, fix anomalies, that was his duty that day

spring vents, little rubber hairs vent out of mold, rubber closes valve, inside of the mold, valve gets stuck down, vibrate ultrasonically

training in mold shop, start on cold molds

"mold shop bike guy"

500 curing presses

also cleaning and assembling and installing molds

bladder inside tire while it molds

bladder valve faulty, heated nitrogen, let in pressure, blew off clamp, came up around legs and burned them

molds designed by Toyo, container is made by another company, curing press itself made by another company - kitsuno?

Advance Technology for maintenance, changed in January went in house

Faulty check valve beneath curing press

Told past issues, assume work orders, not fixed

---

safety Bonine, formerly ATS, now curing supervisor

redness and scarring, inflammation, static feelings and pain

- Adjuster problem -

  Per Moskowitz still going to burn specialist, appointment coming up, they are sending records, next appointment May 23, no permanent yet. Working but some issues, not full duty but within restrictions. Per SKL pain and suffering only bc covered by comp.

  Tire tiering press

when tire is curing, different areas in mold pulls air out, when clogs happen there are issues, when into the press, fix anomalies, that was his duty that day

spring vents, little rubber hairs vent out of mold, rubber closes valve, inside of the mold, valve gets stuck down, vibrate ultrasonically

training in mold shop, start on cold molds

"mold shop bike guy"

500 curing presses

also cleaning and assembling and installing molds

bladder inside tire while it molds

bladder valve faulty, heated nitrogen, let in pressure, blew off clamp, came up around legs and burned them

molds designed by Toyo, container is made by another company, curing press itself made by another company - kitsuno?

Advance Technology for maintenance, changed in January went in house

Faulty check valve beneath curing press

Told past issues, assume work orders, not fixed

---

safety Bonine, formerly ATS, now curing supervisor

redness and scarring, inflammation, static feelings and pain


Ken Davis Mechanical Engineer
Christopher Tubbs Technician
Jeff Turgeon EHS

[can't find] Tyler Byass Shift Supervisor
[can't find] Michael Wolff,
[can't find] Brent Combs, maintenance supervisor

[former] Michael Bevins, Maintenance Supervisor

[ ] "original exhibits retained by" ffs





Talk to witness re complaints relating to check valve
