#+title:      sewell marcus
#+date:       [2024-04-18 Thu 09:24]
#+filetags:   :casenotes:
#+identifier: 20240418T092418


* /Experts/

Harben IME
Eisenman Neuropsych (complaint with recommendations psych and speech therapy?)
McCusker Speech
Leatherman

Burns, McCord

* /Damages/

Medical 2025-04-14 $366,131.13

Patient is disabled from TBI and spine, as well as potentially heart issues. Severe headaches, memory issues, moderate cognitive impairment, back pain. Fainting episodes. Unremarkable MRIs. Radiculopathy. Prior L5-S1 fusion and laminectomy and lots of degenerative changes. Injections and blocks. Back seems complicated, TBI seems clear.

D expert states that initial treatment for concussion was indicated but nothing in the imaging suggests permanent damage to the brain or spine. Note that Gwynn provides a reasonably good hostile summary of the records up to August 2023.

Per our experts, postconcussive syndrome and right sacroiliac joint dysfunction, with myofascial pain.

We have one liability expert and are working on a second, working up Gingras and McCord, and treaters.

Lost income is significant.

FF identified, no experts identified in initial response, Zembik and Harben subsequently ID'd with rule reports, McCord disclosed but he did not provide a report yet. Rowan as a treating, no other treating yet. We have not supplemented past 137867.02

* /Notes/:

[ ] experts

[ ] contact ex employees, other rider?

[ ] lots of diary and rss, need to sit down with Steve and figure out what to produce IF ANYTHING

** Choice of Law

Doe v. Willis, 8:21-cv-1576-VMC-CPT (M.D. Fla. Apr. 5, 2023)

portion of an accident case, useful discussion:
https://www.govinfo.gov/content/pkg/USCOURTS-ilnd-1_19-cv-01844/pdf/USCOURTS-ilnd-1_
19-cv-01844-1.pdf

A federal district court is required to apply the "choice of law" rules of the state in which it sits. Klaxon Co. v. Stentor Elec. Mfg. Co., 313 U.S. 487, 496 (1941).

notes, fu em to counsel, r file, fu depos etc, non-party   
contacting Daniel Forbing, no 6.4, finalize expert disclosures, get PO docs and info, McCord, setting up depositions
Revisit email, social media, visa business
Fu re getting SS docs
Ads for lifeguards
Recruiting person, / social media person
-- Frankel, Pahalovich, Feinsilber, Roderiguez, Buchanan (report) |
-- D by 10/10, plus 30 days for rebuttal experts, Daubert to be filed and all evidentiary discovery to be concluded and statuts report filed by [2025-11-10 Mon]. 2/6/26 for pretrial disclosures, PTO (must circulate by 1/23), MIL, for trial 3/10 SEE SCHEDULING ORDER FOR OTHER DEADLINES


https://www.linkedin.com/in/daniel-forbing-96b80b236/
https://bluegrass.kctcs.edu/education-training/program-finder/emergency-medical-technician.aspx
https://www.facebook.com/bluegrassctc/posts/917869930342491/
https://www.truepeoplesearch.com/find/person/px88rn600u0luunr02lu8
https://qpublic.schneidercorp.com/Application.aspx?AppID=944&LayerID=18493&PageTypeID=4&PageID=8245&Q=124216999&KeyValue=08-082-01
