#+title:      krebs-bensch-allison
#+date:       [2024-03-12 Tue 11:39]
#+filetags:   :casenotes:
#+identifier: 20240312T113933



Cameil,

Please supplement your client's previous interrogatory responses to provide a verification and update any information previously requested. Please also provide dates for a corporate representative of Allstate to testify on the following topics:

1. Coverage provided to the plaintiff in the above referenced civil action on the date of the collision alleged therein;
2. Allstate's pleadings and discovery responses in this case;
3. Authentication of any documents produced by Allstate in this action.

I look forward to working with you to complete discovery in this case. Please feel free to reach out to me on my cell phone at 813-486-6637 if you want to discuss this case.



Request No. 1. Plaintiff was insured by you at the time of the vehicle collision at issue in this matter, which insurance included at the timfe of the collision UM/UIM limits of $500,000 per accident. (see Uninsured Motorist Carrier, Allstate Insurance Company's Response to Plaintiff's First Interrogatories and Request for Production of Documents to Allstate Insurance Company, attached as Exhibit A, at p. 2, Interrogatory 2.)

Request No. 2. This coverage was "add on" not "reduced by at fault" coverage. (See Dec Page, attached as Exhibit B.)

Request No. 3. Accordingly, Plaintiff maintained uninsured motorist coverage at the time of said collision as defined by OCGA § 33-7-11.

Request No. 4. Because Plaintiff maintained uninsured motorist coverage, State Farm has a contractual obligation to pay damages recovered by Plaintiff at trial as provided by the terms of said coverage, in the event that damages are awarded and the defendant driver was underinsured or uninsured.

Request No. 5. There are no other uninsured/underinsured policies applicable to this case.

Request No. 6. There are no umbrella, excess, homeowners, or other insurance policies applicable to this case.

Request No. 7. Defendant Trinity George had automotive liability insurance coverage relating to this collision from USAA in the amount of $50,000.

Request No. 8. Defendant Trinity George had no other automotive insurance available to provide coverage for this collision.

Request No. 9. USAA tendered, and Plaintiff accepted, its limits of $50,000, subject to a limited release to allow Plaintiff to proceed to the extent of other coverage.

Request No. 10. Defendant Trinity George was not carrying out any duties for an employer at the time of the collision.

Request No. 11. Defendant Trinity George did not reside with anyone who had a policy of automobile insurance other than the policy that provided liability coverage for this collision.

Request No. 12. There was no commercial automobile liability insurance that would cover this car crash.

Request No. 13. Defendant Trinity George’s negligence caused the car crash.

Request No. 14. The personal injuries suffered by Plaintiff were the result of Defendant Trinity George’s negligence.

Request No. 15. There are no conditions precedent to the bringing of this action that Plaintiff has failed to perform.

Request No. 16. In the event that the defendants in this action are found to be liable in excess of $50,000, you will be responsible under Plaintiff's policy of insurance with you to pay that excess, up to the total amount of $500,000, less a setoff for $10,000 paid by you as medical payments coverage.

Request No. 17. In the event that the defendants in this action are found to be liable in excess of $50,000, Defendant will have been the driver of an "uninsured motor vehicle" as defined in OCGA § 33-7-11(b)(1)(D).

-------

DO NOT fix name, do D depo, working on buttoning up medical

---

Driving to work with twins, hit while going through a green light, D turning in front of her.

Car next gave card, Elizabeth Oliver

thought nose was broken

teenage girls got out of car, "we had a green light"

Driver was 16

hand broken, disc herniations, TBI

wore boot, nerve issues down arm

Hx back?

** direct claim rss

Standard Guaranty v. Hulsey confirms the UM claim is “contingent upon the claimant’s securing a judgment against the alleged tort‑feasor,” yet the case went forward precisely because the insurer had been drawn into the litigation.  ￼  Moss v. Cincinnati illustrates the practical effect: once the carrier answers in its own name it is a “named party which could contest its liability for coverage.”  And Lewis v. Cherokee teaches that although a judgment is a condition precedent to recovering bad‑faith penalties, it is not a prerequisite to making a demand or asserting the contractual claim.

** /Discovery/

[ ] admit caused the impact in answer but unable to admit or deny in RFAs, deny family purpose, July statute, 28k medical settled with LI and now looking for UM, looks like we served the right people

They admit liability, not clear if they admit family purpose, discovery responses are all messed up with boilerplate and nonsense but not sure it matters






