#+title:      white neal
#+date:       [2024-05-14 Tue 12:11]
#+filetags:   :casenotes:
#+identifier: 20240514T121105


Ty Robinson [restaurant] 706-973-9239, no written lease agreement
Probably don't need a PO

Eaten at Farmhouse "many times"


[ ] van keith insurance (used to be Farm Bureau)

[ ] TJ's phone number, or Doug Cochran

[ ] Major Cochran, Chief Deputy


SSN

jrodreporting@gmail.com

----

Gents,

 

My bad, I failed to see that Plaintiff identified Mr. Nelson last year. 

 

I email pursuant to USCR 6.4 regarding deficient responses to Defendant Barry Stringers written discovery. 

 

Plaintiff Neal White’s June 17, 2024, supplemental response to Mr. Stringer’s First Interrogatories no. 8 says, Mr. Nelson will testify that “…the entrance to the parking lot…was not appropriate for use as a driveway.”  I do not see where Neal White’s response to the following interrogatories have been supplemented:

 

No. 6:  Identification of all who investigated any aspect of the accident and whether a report was prepared.

Plaintiff responded that only his attorney investigated the incident.  Surely Mr. Nelson conducted some sort of investigation.

 

No. 7:  Describe with reasonable particularity all photographs, charts, diagrams, videotapes, any other illustrations of any person, place or thing involved in this lawsuit, giving the date each was made and the name and address of the person(s) with possession, custody or control of each item.

Plaintiff responded that the only photographs and diagrams were those taken/made by the investigating officer.   

Please supplement this response by providing everything prepared by Mr. Nelson.

 

Plaintiff’s Response to Barry Stringer’s First Interrogatories to Plaintiff as Guardian of Conner White are also deficient.  Plaintiff was required to supplement his responses before Conner White was dropped as a Plaintiff:

 

RPD no. 10: All industry, governmental and private standards, guidelines or recommendations that Plaintiff contends Defendant did not follow or adhere to.

Plaintiff provided nothing in response.  Please supplement with all items Mr. Nelson contends Defendant violated.

RPD no. 11.  All government statues, ordinances, regulations or other laws that Plaintiff contends Defendant(s) did not follow or adhere to.

Plaintiff provided nothing in response.  Please supplement with all items Mr. Nelson contends Defendant violated.

RPD no. 13:  All field notes, sketches, diagrams, letters, memos, reports, photos, and documents of any type related to the incident giving rise to this lawsuit and the damages claimed in this lawsuit that have been generated by or for any expert consulted in this case.

Plaintiff provided nothing in response.  Please supplement with all items Mr. Nelson contends Defendant violated.

RPD no. 15: All documents that support or relate to any contention that an act or omission of Defendants caused or contributed to this incident.

Plaintiff responded, “Attached” but produced nothing related to expert investigation, report, etc.

Please supplement.

RPD no. 17:  A copy of a current CV and all statements for services rendered to date by any expert retained to testify in this case.

Plaintiff provided nothing.

Please provided the requested material.   

RPD no. 18: All materials which constitute evidence reasonably relied upon by experts which support your contentions regarding liability.

Plaintiff responded that an expert has not been identified.

Please provided the requested material.   

 

Plaintiff’s objection to identifying liens, rights of recovery, etc., are unfounded.  We are entitled to know if medical providers have a financial interest in the outcome of the case.  Please identify all such liens, rights of recovery or other such documents.

  



