#+title:      ATU
#+date:       [2024-03-13 Wed 10:34]
#+filetags:   :casenotes:
#+identifier: 20240313T103418

---





EMERGENCY PETITION FOR INJUNCTIVE RELIEF

COMES NOW the above Petitioner and files its Emergency Petition for Injunctive Relief, showing the following:

Jurisdiction and Venue

1. Petitioner Amalgamated Transit Union Local No. 732 (“ATU”) is an unincorporated association acting as the collective bargaining representative of certain employees of Defendant Metropolitan Atlanta Rapid Transit Authority (“MARTA”) and submits itself hereby to the jurisdiction and venue of this Court.

2. MARTA is a joint public instrumentality of the City of Atlanta and the counties ofFulton, DeKalb, Cobb, Clayton and Gwinnett created by for the purpose of operating a public transit system in Atlanta, Georgia. It may be served by its General Manager and Chief Executive Officer, Collie Greenwood, “or clerk thereof,” at 2424 Piedmont Road, NE, Atlanta, Fulton County, Georgia 30324.

3. Venue for this action lies in Fulton County pursuant to the “Metropolitan Atlanta Rapid Transit Authority Act of 1965,” approved March 10, 1965, and subsequently amended, Ga. L. 1965, pp. 2243, 2257 § 10(t) (the "MARTA Act"); Mallard v. Metro. Atlanta Rapid, 361 Ga. App. 717, 717 n.3 (2021).

4. The Superior Court has subject matter jurisdiction of this petition in equity.

Facts Common to All Counts

5. Petitioner is the bargaining unit representative of certain employees of MARTA pursuant to a federal statutory scheme whereby the United States permitted metropolitan areas to create quasi-governmental agencies to manage and consolidate public transportation subject to the requirement that they enter into collective bargaining with certain employees.

6. Pursuant to that statutory scheme, the parties have entered into what is commonly referred to as a “13(c) Agreement,” by way of reference to Section 13(c) of the Urban Mass Transportation Act, 49 USC § 5333(b) (“Section 13(c)”), which is a condition of MARTA’s receipt of federal funding, as well as a series of collective bargaining agreements, most recently one entered into by the parties on {DATE}. A copy of the Section 13(c) Agreement is attached as Exhibit A. A relevant amendment is attached hereto as Exhibit B. The most recent Collective Bargaining Agreement ("CBA") of the parties is attached as Exhibit C.

7. Under Section 13(c), the United States Department of Labor must regularly certify that fair and equitable arrangements exist to preserve the rights and benefits of the members of the bargaining unit and their continuing right to bargain collectively prior to the disbursement of funds by the Federal Transit Authority, amounting to millions of dollars.

8. In avoidance of its statutory obligations, in breach of the CBA, and to the detriment of ATU’s members, MARTA has indicated that it does not intend to honor the bargained for "Juneteenth" holiday in performing its periodic work assignments or "markups." See CBA at 40, 43, 60-70. MARTA has also stated that it will compensate employees at standard wages and deny increased wages for employees scheduled off duty.

9. This has caused widespread disturbance to the schedules of ATU's members as they attempt to adjust to the unexpected refusal to recognize a holiday that was bargained for and important to them. In some instances MARTA appears to be retaliating against employees by changing route assignments of employees wishing to celebrated Juneteenth despite seniority.

10. ATU has requested arbitration of this issue but MARTA has denied the request.

11. While some aspects of this issue such as the refusal to pay overtime rates might be remedied by a damages award, ATU's members will be irreparably harmed by the change to their schedule in ways that are impossible to remediate through damages, as disturbance impacts the lives of the members in any number of ways, notably, for example, by requiring child care accommodation.
    
12. By refusing to expedite arbitration, MARTA is signalling that it intends to go forward with this action without allowing for the grievance and arbitration process to protect ATU's member's interest in participation in the Juneteenth holiday, in violation of the letter and spirit of both the CBA and the 13(c) Agreement and the constitutional rights of the members under the First and Fourteenth Amendments of the Constutition of the United States of America.
    
COUNT I - TEMPORARY AND/OR PRELIMINARY INJUNCTIVE RELIEF PENDING ARBITRATION

13. Given the threat of immediate and irreparable harm, the Court should act to preserve the status quo ante and require MARTA to honor the Juneteenth holiday in the markups currently in process.
    
14. The Court should enter this temporary and/or preliminary injunction to preserve the status quo pending resolution of the dispute between these parties via the contracted for grievance and arbitration process and to enjoin conduct by MARTA that would be in breach of their contractual and statutory obligations and contrary to equity and good conscience, and for which no adequate remedy is provided at law. OCGA § 9-5-1.

WHEREFORE, Petitioner respectfully prays that the Court order a hearing be had on the foregoing petition, that the Court enter a temporary restraining order and/or interlocutory injunction pending expedited arbitration of the dispute between the parties, that the Court retain jurisdiction to ensure compliance, and the Court grant such other and further relief as it deems
proper and just.

VERIFICATION

PERSONALLY APPEARED before the undersigned officer, duly qualified to administer oaths, Britt Dunams, who, upon being sworn, deposed and testified that the allegations of the foregoing petition for equitable relief are true and correct, except as to statements made on information and belief, which statements he believes to be true and correct. He further states that any exhibits attached to the foregoing are true copies of the documents described in the portions of the petition referencing those documents

/s/Britt Dunams
President, ATU Local 732
501 Pulliam Street, Suite 406
Atlanta, Georgia 30312

{NOTARY}

EMERGENCY MOTION FOR TEMPORARY RESTRAINING ORDER AND INTERLOCUTORY INJUNCTION TO MAINTAIN STATUS QUO PENDING ARBITRATION, WITH INDWELLING BRIEF IN SUPPORT

Petitioner submits that the conduct described in its petition plainly violates the spirit and letter of both the Collective Bargaining Agreement of the parties and also the “13(c) Agreement,” which requires MARTA to preserve all of the “rights, privileges and benefits...of employees...under existing collective agreements” and requires MARTA to bargain with ATU regarding organizational or operational changes. 13(c) Agreement, attached to Petition as Exhibit A thereto, at ¶¶2 and 7. To the extent that this interpretation of the governing agreements is disputed, it is subject to arbitration under both the 13(c) Agreement (see id. at ¶20), the “Third Amendment” to the 13(c) Agreement respecting arbitration (Petition at Exhibit B thereto, pp. 1-7), and the CBA itself (CBA, Exhibit 3 to the Petition, at ¶ 13). MARTA's refusal to do so in an expedited manner while the markups are in progress is an action in derogation of those agreements plainly intended to simply impose its will on the membership in a manner they cannot timely challenge.

Petitioner respectfully, on an emergency basis, requests that the Court act to enter a temporary restraining order and interlocutory injunction to preserve the status quo in this matter pending expedited arbitration. This Court is authorized to enter such an order based on its assessment of the balance of the equities, including (but not entirely determined by) its assessment of the petitioner’s likelihood of success on the merits. R.D. Brown Contractors, Inc. v. Bd. of Educ. of Columbia Cnty., 280 Ga 210, 211-12 (2006). Petitioner submits that the balance of equities favors it in this matter. Its employees will suffer irreparable harm from being forced to accept a schedule that simply ignores a bargained for holiday of special significance to the membership. Even if an arbitration is eventually conducted, the arbitrators would be presented with a situation where the harm was already done, and it would be difficult if not impossible to fashion a remedy. Finally, to permit MARTA to go forward with delayed arbitration under the facts of this case would be to reward them for dragging their feet to avoid arbitration of an arbitrable controversy with the bargaining unit. The Court should enter an order to restrain and enjoin MARTA from using contractors for the anticipated service.

The undersigned states in his place that, in addition to putting this document and Petitioner’s Petition out for personal service by a private process server, he will on receipt cause file-stamped copies to be served electronically on Jonathan Hunt, Chief Counsel, at juhunt@itsmarta.com, as well as Jeffrey Schwartz, of Jackson Lewis PC, an attorney known to have represented MARTA recently in a separate litigation matter, at jeffrey.schwartz@jacksonlewis.com.

WHEREFORE, Petitioner respectfully prays on an emergency basis that the Court restrain and enjoin MARTA from contracting the anticipated work described in Petitioner’s Petition pending the completion of the grievance and arbitration process on an expedited basis.

RULE NISI

The Court, having read and considered Petitioner’s Emergency Motion for Temporary Restraining Order and Interlocutory Injunction to Maintain Status Quo Pending Arbitration, with Indwelling Brief in Support, the parties are hereby ordered to appear and show cause why said motion should not be granted, at _________ am/pm on April ___, 2024, in Courtroom ____, Fulton County Justice Center.

PROPOSED ORDER FOR INJUNCTIVE RELIEF

Having considered the submissions of the parties in support and opposition to Petitioner’s Emergency Motion for Temporary Restraining Order and Interlocutory Injunction to Maintain Status Quo Pending Arbitration, and for good cause shown:

IT IS NOW ORDERED that said motion is granted. Respondent Metropolitan Atlanta Rapid Transit Authority (“MARTA”) is hereby restrained and enjoined from disregarding the Juneteenth holiday in its markups and otherwise. The parties shall work together in good faith to obtain expedited decision of this matter by an arbitrator or arbitrators chosen as provided for in the relevant governing documents and agreements. The Court will retain jurisdiction pending the resolution of that process.
