#+title:      conard victoria
#+date:       [2024-04-09 Tue 13:37]
#+filetags:   :casenotes:
#+identifier: 20240409T133728

** /Representation and Coverage/:

Attorney for Ingles: [[https://www.gabar.org/MemberSearchDetail.cfm?ID=NjI4MzI4][James W. Scarbrough, Freeman Mathis and Gary, LLP]]
Attorney for Ingles: [[https://www.gabar.org/MemberSearchDetail.cfm?ID=MDg5MDc5][Peter C. Brown, Mabry & McClelland, LLP]]
Attorney for Primo: [[https://www.gabar.org/MemberSearchDetail.cfm?ID=MTM0MjIy][Danielle C. Le Jeune, Cozen O'Connor]]

Ingles: 1,000,000.00 Safety National Casualty

** /Damages/:

Medical: 59978.84
Income:   3840.00

** /Notes/:

Ingles admits control, won't admit or deny invitee in pleadings but it's admitted in deposition. No concerning defenses in answer. No concerning defenses in Primo's 01-06 answer except "CPUS is an improper party..." All Primo produced was an invoice, case against them is just based on location.
Liens. Client had knee disloc and sprain. Surgery, lots of PT and Tx with inject. Still wearing a brace as of 2023-04-10, pain, working home care.
Spoke with [[../5-CaseFiles/Conard.org][manager]] Joe Reynolds, Stephanie Wood, and Daniel Trifan [hold for now] --> FF (fiance), prior records?
wages: not ready for ppd

---

had been a manager 4-5 months, only 19 at the time
left last year, works at Starbucks
stopped being customer service mgr, switched to Starbucks
vaguely recalls, remember cashiers coming up to her, near the coinstar machine
can't remember if she wanted to fill out the form
no picture, may have taken pictures, probably would have sent to store manager
Wes Kelly, since passed away, Crohns
transferred to Commerce
2 falls while she was there, about 6 month
no recollection of fall hazards in front of the store, sometimes rain, wet floor signs
by the front doors
doesn't remember if it was policy to take pictures, would have taken pictures if she'd wanted to report
don't want to be involved
name of the cashier - Joe Reynolds
quality of cameras is bad, she would have looked at all the cameras


