#+title:      kipfmiller marylynn
#+date:       [2024-05-14 Tue 09:04]
#+filetags:   :casenotes:
#+identifier: 20240514T090408

Wright, Bashuck, Eisenman, Yu, FF, Harben

** Medical Review

EMS sprained ankle, NO LOC, 2023-01-28
Savannah Hospital significant ankle, reports head but no LOC, fracture on imaging, normal head and neck CT except for thyroid nodule, order fu with PCP
NGMC ortho treat Fx with cast/boot and PT, multiple visits with no mention of TBI
Northside Neuro (Cooper) starting soon after fall reports of headache and breakthrough seizures, double vision that resolved. noncompliant with lamictal, increased dose. Improvement wrt seizures but continuing memory issues and headache.
DO two visits, vision resolved?
PCP, issue whether there was DOS on DOL, at least one visit just for a cold, NB thyroid surgery two months after accident. documents ongoing symptoms
Interventional Pain 1 DOS only Rowan MD?
PT discharged with prognosis "fair"
Concussion center repeated causation opinions
pulled a single record from Rehab Institute with good note of concussion symptoms
NB prior records extensive for headache, issues with medication compliance (confusion) wrt epilepsy

** Depos

Counsel,

We are ready to schedule the following depositions, please advise:

# Oak View Group

Chelsea Reynolds, Assistant Manager
Brooke Cima, Assistant General Manager
Monty Jones, Jr. General Manager
30b6 representative to testify on the following topics:
Pathways and approaches providing access to the facility
Policies and procedures regarding safety and fall prevention
The area where Plaintiff fell and any open and obvious conditions in that area that might have contributed to the fall
The incident at issue in this case and the response thereto
Defendant's contractual relationship with City of Savannah
Defendant's responsive pleadings and discovery responses

# City of Savannah

30b6 representative to testify on the following topics:
Pathways and approaches providing access to the facility
Policies and procedures regarding safety and fall prevention
The area where Plaintiff fell and any open and obvious conditions in that area that might have contributed to the fall
The incident at issue in this case and the response thereto
Defendant's contractual relationship with Oak View Group, LLC
Defendant's responsive pleadings and discovery responses



