#+title:      robinson donya
#+date:       [2024-04-18 Thu 12:04]
#+filetags:   :casenotes:
#+identifier: 20240418T120445

COMPLAINT

COMES NOW Plaintiff Donya Robinson ("Robinson") and files her Complaint in this action monetary damages for personal injuries arising from a fall at in a high school gymnasium, showing the following:

Jurisdiction and Venue

x. Plaintiff is a citizen of the State of Georgia submitting herself hereby to the juridiction and venue of this Court, and she may be served pursuant to OCGA ยง 9-11-5 by her undersigned attorneys.

x. Defendant Laura Wilson ("Wilson") is the Principal of South Forsyth High School and she may be served with summons and complaint in this action at South Forsyth High School, 585 Peachtree Parkway, Cumming, Forsyth County, Georgia 30041. On information and belief, she resides in Forsyth County, Georgia.

x. Samir Tartic ("Tartic") is the Head Custodian of South Forsyth High School and resides in Forsyth County, Georgia, at 350 Sugarberry Lane, Suwanee, Forsyth County, Georgia 30024. He may be served with summons and complaint in this action at South Forsyth High School, 585 Peachtree Parkway, Cumming, Forsyth County, Georgia 30041.

x. On information and belief, John Does I through V are employees of Forsyth County.

x. The state court has subject matter jurisdiction of this action for money damages, and venue is proper in Forsyth County pursuant to Ga. Const. Art. VI Sec. II. Paras. IV and VI.

Facts Common to All Counts

x. On January 7, 2022, Robinson attended an event held in the gymnasium at South Forsyth High School in Forsyth County, Georgia.

active negligence, ministerial duty
