#+title:      byers
#+date:       [2024-02-16 Fri 11:21]
#+filetags:   :casenotes:
#+identifier: 20240216T112124
---

** /Representation and Coverage

Attorneys for Defendants: [[https://www.gabar.org/MemberSearchDetail.cfm?ID=MjA2Mjc1][Melody Kiella, McAngus, Goudelock & Courie]]
                          [[https://www.gabar.org/MemberSearchDetail.cfm?ID=OTUzMDczb][Camille D. Dizon, McAngus, Goudelock & Courie]]
			  [[https://www.gabar.org/MemberSearchDetail.cfm?ID=NzkxMDQ5][Hernan Antonio Diaz-Caballero, McAngus, Goudelock & Courie]]
LI Carrier: Nationwide
LI Amount: 1000000.0

** /Damages/

Medical: 84706.89
Income:      0.0

** /Notes/:

[rss re construction permit?] - Satterfield picture, too high for handicap, can't exceed 3/4, SHALL have a landing per international building code 10-10.1.6 "Landings and Doors" failure to maintain is in several codes etc ADA even if not open to the public

[Status]: Teresa Vickers acknowledged service, discovery ran, no affirmative defenses worth worrying about, TV lives in Hall, Byers was a volunteer and tenant, never an employee per them. Steve thinks it's a MM case bc RSD.

[Wages]: lost wages pled $3,642.50


[ ] fu email re depo issues 9/25
[ ] doctor depositions Awad, etc preservation

---

Vickers address from Nursing Board proceedings, 2016

ZJV Limited Partnership [White County property] 165 Larla Davis Drive, Cleveland, White County, Georgia 30528, registered agent is W.W. Vickers at 319 Buffalo Drive West, Dawsonville, Lumpkin County, Georgia 30534 (got the address county correct on this one)

Limited parter is JZ Properties, LLC, same address, this time ra is Warren Vickers

Deerfield Creek Ranch is the horse boarding operation, they own the animals.

zjv owns the property in white county

WHO IS BARBARA VICKERS (I think she's a former wife...)

319 Buffalo Drive W, Dawsonville, Lumpkin County Georgia 30534.

Byers was a volunteer at Swan Lake Manor.

# teresa

some minor issues:

[ ] send disclosures for Satterfield, inspection, "not been to the property"

[ ] 253-80-3105 teresa

[ ] lease? maybe not?

[ ] they did pay her

[ ] whose wedding?
 
[ ] Dawsonville assisted living contract D 

> Forsyth Superior Court
> 15CR-WARR
>
>    - PRACTICE MEDICINE WITHOUT LICENSE- Dismissed
>    - UNLAWFUL PRACTICE PHARMACY WITHOUT A LICENSE- Dismissed
>    - ATTEMPT OR CONSPIRACY TO VIOLATE GEORGIA CONTROLLED SUBSTANCE ACT-
>    Dismissed
>    - UNLAWFUL FOR ANY PERSON TO PURCHASE, POSSESS, OR HAVE UNDER HIS
>    CONTROL ANY CONTROLLED SUBSTANCE- Dismissed
>    - MANUFACTURE/DELIVER/DISTRIBUTE/SELL/POSSESS W/INTENT TO DISTRIBUTE
>    CONTROLLED SUBSTANCE- Dismissed
>    - UNLAWFUL PRESCRIPTION- Dismissed

Tanglewood v. ZGW 

Tell me about:

> Gwinnett State Court
> 20-C-02346-S3
> Arnita Clark Owens, Individually & As Administrator Of The Estate Of
> Louise Clark, Deceased Vs Fort Valley Operator LLC et al
> Tort

How did that case resolve? 

How about:

> Hall State Court
> 2016SV000582
> PDRX Pharmaceuticals, Inc. v Teresa Vickers
> Petition to Domesticate Foreign Judgement

How about that case?

Traffic tickets?

> Hall County State Court Traffic-
>
> 2018TB003507
> Driving Without Seatbelt- Guilty
>
> 2003TB007547
> Speeding- Guilty
>
> 2003TB005017
> Allowing Another to Operate an Unregistered Boat- Guilty

Were you ever arrested in Lumpkin County?

> There may be another arrest in Lumpkin County, however, I am going to have
> to call the Lumpkin Sheriff's Office tomorrow and confirm that. There are a
> few other counties where she's had residence history, and I will also need
> to check those. I just wanted to provide an update with what I have found
> so far.
>

** Time

2024-04-02 1.0 depo prep
2024-04-03 4.0 attend depo, cw client before and after
