#+title:      cladding
#+date:       [2024-08-21 Wed 10:01]
#+filetags:   :casenotes:
#+identifier: 20240821T100113

* /Representation and Coverage/

Attorney for Defendants: [[https://www.gabar.org/member-directory/?id=76B531CCA2947A504CEA34435BF25A76][R. Brandon Galloway, Galloway & Galloway, P.C.]]

This is the deposition of Phuong K. Nguyen [fung when], taken pursuant to notice for all purposes allowable under the Georgia Civil Practice Act. I would propose the parties stipulate that all objections will be reserved until the first lawful use of the transcript except as to form or responsiveness of the answer, and that the parties agree that Mr. Nguyen will be under oath in this remote deposition, is all that agreeable.

[swear]

Mr. Nguyen, my name is Paul Menair and I represent Cladding & Component Solutions in a lawsuit against you. You understand that you are under oath here today.

I would appreciate your helping me to make as clean a transcript as we can, which means we need to try not to interrupt each other or talk with our hands, okay?

I am going to start by asking some questions about you and your company, and then we'll talk about your relationship with my client.

Could you tell me your full name please, and spell it.

What is your date of birth.

Off the record.

Could you tell me your social security number please.

Back on, for the record, Mr. Nguyen provided me with a nine digit number. Also for the record, Mr. Nguyen, that was your social security number, correct?

What is your home address.

Do you have any other residences?

Who lives with you at that address?

Do you have any relatives in Chatham County, Georgia.

You are the registered agent for CamKen Construction, LLC, yes?

Camken all one word or two words? What does it stand for? [Check GSS]

Are you also an officer of that entity?

Which offices do you hold?

Are you a member?

Are you a manager?

Are there any other members, managers, officers, or employees of Cam Ken Construction, LLC

Do you have an operating agreement?

Would you be willing to provide me with a copy of the operating agreement?

Where is it located?

The principal and registered offices of Cam Ken are located at 1160 BIG BEND RD, POOLER, GA, 31322, USA

That is your residence, yes?

Do you have any property titled in the name of the entity, like land, vehicles, that sort of thing?

Do you mind if we just say Cam Ken?

Does Cam Ken have a bank account in its own name?

At which bank?

Just one account for checking?

Ex 1 Check

When you have a contract running, are all of the subs paid out of that account?

Are any payments made to that account?

Always?

Do you ever commingle Cam Ken project funds with your personal accounts?

What's the current balance in that account as of today? Ballpark.

Do you try to keep a specific minimum balance?

Do you have a line of credit?

Does Cam Ken have any other assets you can tell me about.

Do you have any current projects with receivables.

Can you tell me what Cam Ken's EIN is?

Has Cam Ken ever gone through any type of bankruptcy.

Have you personally ever been bankrupt?

Have you ever been arrested, for whatever reason?

Let's look at a document, we'll mark this as Exhibit 2
to the deposition.

These are responses to some questions we sent prepared by your attorney, are you familiar with this document?

Be advised that when I mention your attorney, that doesn't mean I want to know anything about any conversations you guys have had, that's none of my business right now, okay?

Did you assist in preparing this?

Did you review this to prepare for today? Any other documents.

There is ordinarily what's called a "Verification" attached to these documents where you say that the responses are true and correct, but I don't see one here, did you sign anything like that?

Let's go through it now then.

The first question asks if you know of any witnesses who might know something relevant to the case, and the response is Joseph Cumbess, do you see that?

Can you think of anyone else?

Who else did you deal with at Cladding and Component Solutions?

Ms Sewell might know something about this contract and your payment history, right?

So you agree that you might have included her name here, correct?

Who is Sean Sullivan?

We'll get back to him in a bit, but he knows about the boat, right?

So you might have mentioned him, right?

Who did you deal with at Lexis about the project?

Who were the other subs on the Lexus project?

Have they all been paid?

Can you think of anyone else who knows anything about this project in general or your dealings with Cladding specifically.

Have you personally talked to any expert witnesses about this case?

Let's talk about insurance, interrogatory number 3. Does Cam Ken have insurance?

What kind of coverage do you have?

How about personal coverage, other than auto.

It appears to be your contention that there is no available insurance coverage relevant to the claims my client has made, is that still your position sitting here under oath today?

Interrogatory response number 4 says you are improperly identified as a party, is that just because you don't think you should be held liable for Cam Ken's debts? We didn't spell your name wrong or anything, did we?

Interrogatory response 5 references a 32' Regulator boat.

Let's get into this.

Your contention is you gave Joseph Cumbess a boat as part payment for what you owed Cladding, is that correct?

Tell me about how that happened?

At the time Cumbess took title to the boat, who did it belong to?

Was it ever titled in Cam Ken's name?

Or your name?

Exhibit 3 is the title

Exhibit 4 is a bill of sale

Looks like Sullivan sold the boat to you in 2018 and you gave the boat to Cumbess in 2022

Are you the one who put the white-out on the title?

So your name is under there, yes?

Is that the way you're supposed to transfer title to a boat?

Why didn't you get a new title so you could have a clean transfer

You contend this boat was given to Mr. Cumbess to offset your debt to the company, correct?

In 2022

Why would you believe that Mr. Cumbess was authorized to accept a boat as payment of a debt owed to Cladding?

Why would Mr. Cumbess take title to the boat personally if the debt was to Cladding, not him personally?

Cam Ken never owed Cumbess any money, right?

And to be clear, was there any reason other than the fact that he was the person you were dealing with that gave you reason to believe that he had authority to accept an property transfer to him personally as payment on a debt for construction work.

How many other times have you been involved in transactions like that?

Was it Mr. Cumbess' idea or yours?

Did you inform Lexus that you were paying one of your subs with a boat?

Around the time you gave him the boat, you were renegotiating the subcontract with Cladding, correct?

Because you decided to hire a local company to perform some work for you that my client had originally agreed to perform, at a cheaper rate, correct?

Do you have documentation of that change?

Did you inform Lexus that you were having the work done for less by a different sub?

Why not?

Would you be willing to provide me a copy of the Lexus contract?

Your bid?

Mr. Cumbess saved you money by agreeing to that, yes?

And you did not inform Lexus, right?

You didn't want him to inform Lexus

[NON-PARTY info re sub and Lexus]

Your sole defense in this action seems to be that you should be allowed to set off the value of this boat against the money owed to my client.

And in fact you do not otherwise dispute the amount owed as pled by my client in its verified complaint.

What is your basis for saying this boat was worth $200,000?

Do you have anything in writing?

Is there anything you intend to produce at trial to support that valuation?

If Mr. Cumbess were to testify that the boat was in fact worth substantially less than $200,000, would he be lying?

You say at one point that was the "agreed" value of the boat. Who agreed? Is the agreement in writing?

We talked about accounts, interrogatory 10.

We filed a motion to compel a response to this and your attorney did not contest that motion, so you will agree to provide a supplemental response, yes?

Interrogatory 11 asks for any documents at all that might memorialize or constitute an agreement, a modification, an enforceable understanding of any type between Cam Ken and you, on the one hand, and Cladding, on the other. You have nothing.

You agree there was a contract for my client to do cladding work at a Lexus dealership, yes?

But you don't have a copy.

And you don't believe you owe my client, but the only reason is you think the value of this boat offsets any money owed.

Did you ever communicate with Connie Sewell about the contract with Cladding?

Ever by text, email, anything in writing?

When you communicated with her, you agreed you owed them money, didn't you.

You asked for time.

Ex 5

Did you talk to Larry Prosser about the debt and try to renegotiate it?

Cumbess?

How about Connie Sewell?

Ex 6

You did not on any occasion say to her, what about the boat?

I don't owe you anything, you didn't say that, right?

You never told anyone but Cumbess about the boat about the boat, did you?

Let's look at another document, I'll mark it Exhibit 7

These are called requests for admission.

We sent these to you in January.

Have you seen this document?

You did not respond to this, did you?

Were you aware that a failure to respond to a request for admission constitutes a formal admission?

Let's look at these.

Request 1 references the title transfer attached as Exhibit A to the requests, This is the title to the boat, yes?

It shows $80,000 as the selling price, yes?

And so you admit that the fair market value of the boat was at MOST $80,000.

By not responding you admitted that.

And you admit here today again that you have no evidence of a greater value.

You admit that the owner of the boat was Sean Sullivan.

You admit that the original price for the job was in excess of $800,000, but by using local framers you reduced that to about $450,000.

You admit that it was Mr. Sullivan or you that used the white out, not Mr. Cumbess.

And you admit that you told Mr. Cumbess the boat was a gift.

No one ever agreed to take the boat in exchange for a debt.

And you had no reason to think that Mr. Cumbess even had authority from Cladding to do that.

You gave him the boat so he wouldn't tell Lexus about the money you were saving using a different framing company, didn't you?

You are aware we filed a verified complaint stating Cam Ken owed $165,711.44.

You denied that in a responsive pleading filed by your attorney on your behalf, but unverified.

But your only basis for that denial, at least with respect to Cam Ken itself, is this story about a boat.

And based on that story, you've put my client to the expense of further discovery, including this deposition.

NEED THE TEXT AND ANY CHECKS




