#+title:      day daniel
#+date:       [2024-04-16 Tue 09:45]
#+filetags:   :casenotes:
#+identifier: 20240416T094516

* Notes

[ ] exhibits, read medical front to back, anticipate objections
[ ] no PTO, plan a sanctions demand
[ ] work on close next week

Traffic accident in Forsyth, client is an overweight truck driver, we have video of the accident. Bad faith demand to UM was sent. Discovery ran March 4, 2021, not going to depose anyone else re entrustment, primary liability is pretty clear. Medical mostly on lien, preexisting. Service defense withdrawn per discovery responses, which are good. Admit simple negligence. Client has continuing pain, we have video of the accident. No surgery bc no insurance, not a surgical candidate. [wages]: lost income pled in the amount of "at least $6,686.25," no mention of futures, same itemization in several discovery responses -- ACM found an additional 25k in coverage, also from State Farm, OOS SENT. Announced ready for trial, decision on MSJ sent, venue will vanish if we lose the vehicle owner.

McCartney ssn 178-64-4320

Lost income: three days per injection or nerve procedure, lost time for other doctor visits, he has a handwritten log, they could track his time week to week, he's working hard to make up the time, taxes going up, made almost 97,000 last year, was only making 60,000 in Georgia

Case was reviewed by Cabot, he gave a good report, CS was more sceptical based on on initial chiro only treatment.

* Witness Outlines Direct [in order of proof]

** Linda Johanson [cross]

On May 25, 2018, you were the owner of a 1998 Ford F-150, correct?

And that was the vehicle that Mr. McCartney was driving in the collision we're here about today, yes.

At the time of the collision you were involved with the food ministry at your church.

And you gave the vehicle to someone named Royal Clevinger to use in the food ministry.

Mr. McCartney is Royal Clevinger's nephew.

Mr. Clevinger had a key to the truck and would use it from time to time.

He had a key so his so he could pretty much use it any time he wanted.

On the day of the collision, someone just came and picked up the truck from your house while you were asleep.

And that was consistent with your arrangement with Mr. Clevenger, he was just able to swing by and pick up the truck.

You had seen Mr. McCartney drive on at least one other occasion prior to the wreck.

In fact Mr. McCartney and Mr. Clevinger often drove together in separate vehicles when you guys would go pick up food for the food pantry.

But you didn't know McCartney other than through church.

And you didn't know anything about his driving record.

And you had no way of knowing it would be Mr. McCartney using the truck.

** Gilmore

redact

** Amber Day

Amber, tell the jury who you are.

Where are you from originally?

How did you and Daniel meet?

When did you get married?

Children?

Are you a stay at home mom?

Tell me about your relationship with Daniel.

I believe the collision we're here about today happened on May 25, 2018, does that sound right?

Was Daniel driving your car?

Did he call you?

Did you go to the scene?

What did you see?

Whose idea was it to get the video from the gas station?

How was your husband physically before the collision?

What did you guys do after?

Tell me in your own words how this collision impacted Daniel physically?

Was this emotionally difficult for you as his wife?

Did you guys lose income?

Did Daniel have to keep going to work to make ends meet?

Was that hard for him to work sometimes?

What are some things he couldn't do after the collision that he could do before.




Gilmore depo:

22:22-25, 24:3-9, 25:13-21, 26:9-10, 27:16-20, 34:2-3, 35:3-9, 35:10-15, 36:3-4
