#+title:      martin dawn
#+date:       [2024-05-28 Tue 11:00]
#+filetags:   :casenotes:
#+identifier: 20240528T110056

no discovery responses, probably should just go ahead and depose. Ash filed an answer in default claiming she was 1099 and not on company time, Cloud filed a COS but not answer so also default. Mahone has filed nothing and is in default. Arguably everyone is in default. Still no atty or insurance. get asset search from Fenrir? UM out

MOTION TO COMPEL AND FOR SANCTIONS

COMES NOW the above Plaintiff, pursuant to OCGA § 9-11-37, and files her Motion to Compel and for Sanctions, showing the following:

1. Plaintiff filed her Complaint in this action on June 28, 2028 against three defendants, along with Certificates of Service of Discovery Material showing her intention to serve certain requests for admissions, interrogatories, and requests for production of documents on those defendants.

2. Service was perfected on all three persons by private process server on July 15 and August 13. See Affidavits of Service, attached as Exhibits A and B.

3. Defendants Ash and Cloud answered pro se on or about September 12, 2024. See Answers, attached as Exhibits C and D.

4. Defendant Jasmine Mahone has not answered as of the date of this motion.

5. Defendants Ash and Cloud filed Amended Answers on or about February 10, 2025. See Amended Answers, attached as Exhibits E and F.

6. Defendants Ash and Cloud have participated in discovery in this action by propounding discovery on the plaintiff and by attending at their depositions.

7. On April 3, 2025, the undersigned sent defense counsel correspondence requesting discovery responses, notably, but without limitation, to a request for information regarding a policy of insurance that Defendant Cloud refuses to identify. See Correspondence, attached as Exhibit G.

8. It is alleged, and Defendant Cloud has testified, that Defendant Ash was working for him at the time of the collision. Although Defendant Cloud insists she was not acting in the scope of her employment or was acting solely as an independent contractor at the time of the collision giving rise to this litigation, Ms. Ash testified that she was on her way to a job site and that Defendant Cloud assumed a significant degree of control over the time and manner of her work.

9. Defendant Cloud is required under OCGA §§ 9-11-26 and 33-3-28 to provide insurance information.

10. Defendants Cloud and Ash were required to provide verified responses to Plaintiff's First Interrogatories and Requests for Production of Documents within 45 days of service. See Discovery Requests, attached as Exhibits H and I.

11. Defendants Cloud and Ash have not contested service and have otherwise participated in discovery in this action.

13. Plaintiff's requests for admissions are deemed admitted by each defendant and Defendant Mahone is in default.

14. For Defendant Cloud and Ash's entire failure to respond to interrogatories in this action, this Court is authorized to enter an order to compel and also impose such other sanctions as it deems just, including an award of attorney fees.

15. The undersigned has pursuant to Uniform State Court Rule 6.4 attempted in good faith to communicate with opposing counsel to resolve this matter without the necessity of the Court's intervention.

WHEREFORE, Plaintiff respectfully prays that the Court enter an order to compel Defendants Dajuan Cloud and Lynneicia Ash to provide full, accurate and complete responses to Plaintiff's First Interrogatories and Requests for Admissions including, but without limitation, a response to Interrogatory 3 that identifies any and all policies of liability insurance or other forms of indemnification providing liability coverage, within 15 days of the date of its order, that the Court award Plaintiff her attorney fees and costs of the present motion, and that the Court grant such other and further relief as it deems proper and just.

ORDER

The Court having read and considered Plaintiffs Motion to Compel and for Sanctions, and for good cause shown,

IT IS NOW ORDERED:

Defendants Dajuan Cloud and Lynneicia Ash shall provide full, accurate and complete responses to Plaintiff's First Interrogatories and Requests for Admissions including, but without limitation, a response to Interrogatory 3 that identifies any and all policies of liability insurance or other forms of indemnification providing liability coverage, within 15 days of the date of its order,

The Court reserves ruling on Plaintiff's request for sanction of attorney's fees.
