#+title:      Adams Deborah
#+date:       [2024-08-30 Fri 13:09]
#+filetags:   :casenotes:
#+identifier: 20240830T130931

:li: 500,000 Travellers, 1MM umbrella
:um: 250,000 Safeco reduced by
:med: 40,061.82 concussion

Admit breach duty, no service defense. TBI, Pl Depos done, trying to settle. Plenty of insurance. This is the case with the two female lawyers who wanted us to schedule the full seven hours. No experts yet.

Witness at scene? No citation, "misperceived Plaintiff's vehicle's speed," admits duty and breach, denies proximate cause and damages. Medical is ER, then chiro, then neuro (refer from chiro), possible dementia, they will look at it as us working up the file. Denies hitting head or LOC in EMT records and hospital records. Now claims amnesia to accident, sought treatment for short term memory loss immediately after the accident. Childhood TBI.

D SSN 263-39-5349

Medical: Alert and oriented at scene, denied head trauma or LOC, major complaint knee pain. Mild neck soreness, chest and knee pain at hospital. Prior knee replacement. No fractures on imaging. Continuing pain --> specialist (Arthritis and Total Joint Specialists Alpharetta) 8 days post-incident, able to bear weight, Rx ice and contrast baths, XR no fracture. Chiropractor (McNamara) claims she complained of fogginess, loss of memory, trouble speaking, back issues, Dx concussion and spine issues. Note our name is in this file. Treating with Dr. Cooper, he notes (childhood) history of TBI, notes she is amnesiac about the incident. Calls cognitive impairment mild (mostly forgetfullness) and tests for dementia, return normal but he notes she reports some impairment prior to the accident. MRI "consistent" with TBI. Did cognitive therapy at concussion institute, some improvement. Neurocognitive testing average or above as of January 2024, Cooper rules out dementia. Some clotting developed in leg but no need for further treatment. Has anyone seen her since January of 2024?

Expert: Buchanan is the only expert identified so far.

----

FF

Lauren Sweeney (oldest daughter)
toastydesigns@gmail.com
f678-862-5774
  
Jim Morrison
jwmorrison65@gmail.com<mailto:jwmorrison65@gmail.com>
james.morrison@lumpkincounty.gov<mailto:james.morrison@lumpkincounty.gov>
706-429-8669

Charlie Bassham (friend also wife)
cbassham@gmail.com<mailto:cbassham@gmail.com>
770-605-6471

Jeff Baker
backerguitars@yahoo.com<mailto:backerguitars@yahoo.com>
678-468-3639

Allison Baker
jabacker@bellsouth.net<mailto:jabacker@bellsouth.net>
678-557-2355
