#+title:      davis karin
#+date:       [2024-04-09 Tue 15:28]
#+filetags:   :casenotes:
#+identifier: 20240409T152859

** /Representation and Coverage/:

Counsel for Defendant: [[https://www.gabar.org/MemberSearchDetail.cfm?ID=MDQ5ODc2][Timothy Bendin, Bendin Sumbrall & Ladner, LLC]]
Counsel for Defendant: [[https://www.gabar.org/MemberSearchDetail.cfm?ID=MzI1NDQw][Kathleen Simcoe, Bendin Sumbrall & Ladner, LLC]]

** /Notes/:

J. Jane Manning, law clerk is Viraj Parmar, Staff Attorney
(770) 528-1704
Viraj.Parmar@cobbcounty.org<mailto:Viraj.Parmar@cobbcounty.org>

Counsel for Piedmont [inside]: [[https://www.gabar.org/MemberSearchDetail.cfm?ID=MzEzNzc0][Allison Richardson]]

We need the security manual and security protocols for Piedmont Hospital. We need the the amount of assaults that took place in the last five years and how they responded to each assault we need to have any and all publication names of security and security issues that they subscribe to we need to have the names of the risk management people the name of the Head of security and the head of administration to whom they report to. We need to have all incidents and MO use with the Atlanta police department. We need to have the record of Richard Miley and how he got there and how come he wasn’t released we need the protocols for 1031s? And when do they notify the police of someone who is crazy how do they detain individuals who are mentally disturbed and how they handle people whose families do not take them when they are discharged we also need to have any logs of security incidents which regard regarding this rape. We also need to understand why there was nothing in the record aside from one comment, made by the PA concerning this incident.

