#+title:      newman-daniel
#+date:       [2024-03-18 Mon 15:04]
#+filetags:   :casenotes:
#+identifier: 20240318T150448


Discovery and ALL experts including treating by Feb 12, no more change parties. The only expert we identified was MacDonald. NO policy expert. We have to go to Cherokee and Forsyth if CFA gets out. Use ANSI standards for cross?

---

Traffic accident with CFA driver, significant property damage.
standards re motor fleet industry American National Standards Institute Safe Practices for Motor Vehicle

{??} fu client re blood pressure log, FF, deductibles and copays, why were there two pairs of glasses, (only receipt from lenscrafters is relevant)? get mvrs from Walt if there's a problem, don't forget ssn, produce ANSI "Safe Practices" document?

Chik-fil-A case. Went to Northside day after accident, neck leg and chest pain, no headache dizziness etc. Headaches later (neck?), later mood changes. But seems to have denied concussion symptoms initially. Radiculopathy due to impingment, treated.

Panton and HL answer 1/9, want change of venue, no other concerning. Claim Panton had medical emergency --> LOC; NB State Farm produced a bunch of video including scene and hospital with driver being cited

D cited for failure to maintain lane and pled guilty to basic rules.

  Walt is bent about the PT bill

  MRI 5k, PT 5k, the rest is about 7 grand, plus the laptop replacement

problem not from neck, need EMG to Dx elbow, refused EMG, no surgery, can probably manage it, no further treatment, able to live with it "for the moment," not improving

  continuing concussion symptoms, brain fog from time to time

  Two visits from Maloon, "this should go away," it did get better

  anxiety/xanax preexisting

-------

-------

PLAINTIFF'S BRIEF IN RESPONSE TO DEFENDANT CHICK-FIL-A'S MOTION FOR SUMMARY JUDGMENT

COMES NOW Plaintiff Daniel Newman ("Plaintiff" or "Newman") and files his brief in response to the motion for summary judgment filed by Defendant Chick-fil-A ("CFA"), showing the following:

A. Facts and Procedural Posture

This action arises form a motor vehicle collision on February 14, 2022 caused by Defendant Panton. See generally, Complaint. On that day, Kurt Panton was driving to make a food delivery, started coughing, blacked out, and collided with Plaintiff. (Deposition of Kurt Panton, transcript attached to Plaintiff's Record Appendix as Exhibit 1 thereto, ("Panton Depo.") at 23:7-18.) Panton started coughing because he was eating while driving and choked on a muffin that he got from work. (Panton Depo. at 24:5-14; 32:14-16.) The vehicle he was driving belonged to Humble Leaderology, LLC ("Humble Leaderology"). (Panton Depo. at 5-7.)

Humble Leaderology is a franchisee of CFA pursuant to a Franchise Agreement of January 1, 2015, between Benjamin Adam Rhodes and CFA, subsequently assigned to Humble Leaderology pursuant to an Assignement and Consent to Assignment agreement of January 1, 2017. See CFA's Statement of Material Facts ("SMF") at 7-8; Affidavit of Angela Pritchard ("Pritchard Aff.") attached to SMF as Exhibit 2 thereto, ¶ 4-5. A true and correct redacted copy of the Franchise Agreement is attached to the Pritchard Aff. as Exhibit A thereto and is also included in Plaintiff's Record Appendix as Exhibit 2. The Franchise Agreement was in effect between CFA and Humble Leaderology on the date of the collision between Plaintiff and Panton. Prichard Aff. ¶ 6.

Under the Franchise Agreement, in addition to quality requirement manuals, CFA contracted to provide training and operational material to franchisees as part of a comprehensive system it has developed for the operation of its Chick-fil-A branded restaurants. (Franchise Agreement pp. 2-3 §§ 1.1(d), 1.1(o).) Humble Leaderology was required under the Franchise Agreement to operate its business in "strict conformity" with the training and operations policies of CFA, which, in addition to service and product consistency requirements, cover "all other aspects of the operation of the [b]usiness." (Franchise Agreement p. 7 § 12.1(d).) CFA had the right to inspect Humble Leaderology's facility to ensure complaince with all of its policies. (Franchise Agreement p. 8 § 13.1(a).) Any material failure to comply with CFA's operations and training policies would be a breach of the Franchise Agreement sufficient to authorize CFA to terminate the agreement. (Franchise Agreement p. 9 § 24.1(i).)

The Franchise Agreement requires Humble Leaderology to hold itself out to the public as an independent contractor and disclaims any agency relationship. (CFA 0040 § 25.1.) Despite the express requirement of strict conformity with training and operations policies of CFA, the Franchise agreement disclaims any agency relationship and inconsistently asserts that the terms of the agreement "are not intended to control or otherwise affect the time, manner, or method of [Humble Leaderology's] day-to-day operation." (Franchise Agreement at p, 20 § 25.2.)

Ben Rhodes, the owner of Humble Leaderology, has extensive experience working directly for Chik-fil-A and was chosen by them, first to run corporate-owned restaurants and then, later, to be a franchisee. (Deposition of Benjamin Rhodes, copy attached to Plaintiff's Record Appendix as Exhibit 3 thereto ("Rhodes Depo.") at 11:1-12.) He took over an existing drive-thru-only restaurant to manage it as a franchise. (Rhodes Depo. at 11:12-21.) Rhodes is and always has been the sole member of Humble Leaderology, LLC. (Rhodes Depo. at 13:13-20.) The facility in question is the only Chick-fil-A that Mr. Rhodes operates. (Rhodes Depo. at 15:10-12).

Rhodes himself received an initial six weeks of formal training from Chick-fil-A and retrains every two years. (Rhodes Depo. at 16:5-8.) For training his employees, CFA also provides operational training material known as "Pathways," which includes driver training material. (Rhodes Depo. at 16:12-14. See also Deposition of Leroy Hooks, transcript attached to Plaintiff's Record Appendix as Exhibit 3 thereto ("Hooks Depo.") at 10:6-11:8, and Deposition of Madison Pippins, transcript attached to Plaintiff's Record Appendix as Exhibit 4 thereto ("Pippins Depo."), at 8:4-9:6.) The Pathways material was developed by CFA. (Rhodes Depo. at 17:3-5.) CFA regularly inspects the Humble Leaderology facility to ensure compliance with its policies, including safety policies. (Rhodes Depo. at 20:14-21:5.)

Humble Leaderology, LLC has no other written policy material regarding driver safety; in fact, it's only operational training material is provided by CFA through Pathways. (Rhodes Depo. at 17:12-15; Hooks Depo. at 13:5-8, 24:2-4.) CFA regularly visits Humble Leaderology, LLC to ensure the franchise is, among other things, operating in conformance with its safety policies. (Rhodes Depo. at 20:14-24.) Other than the Pathways material, Humble Leaderology provides no driver training and relies on the State of Georgia's ordinary licensing procedure, its insurer's driving history screening, and "the Chick-Fil-A protocol" to ensure driver safety. (Rhodes Depo. at 19:9-25; Panton Depo. at 20-22; Pippins 10:9-19; 15:5-16:17; 21:11-13.) Humble Leaderology has no policies from its insurer or its insurance broker relating to driver training, hiring, or other driver safety issues, other than the requirement to provide a copy of the driver's license to the insurance company. (Hooks Depo. at 16:5-14; Pippins Depo. at 10:4-6.)

The vehicle Panton was driving at the time of the collision had Chick-fil-A branding and no signage or identification associated with Humble Leaderology. (Panton Depo. at 5-7; Hooks Depo. at 15:5-15.) Panton was on the clock at the time of the collision. (Pippins Depo. at 28:2-5.) He told Humble Leaderology that he had passed out but refused to explain why, which led them to decide not to put him on the schedule as a driver again after the incident. (Hooks Depo. at 21:4-22.)[fn][Plaintiff is filing a Motion for Filing Under Seal contemporaneously regarding confidential material relevant to this dispositive motion.]

B. Argument and Citation of Authorities

1. Standard of Decision

Summary adjudication of a civil action is appropriate only where there is no genuine issue of material fact for decision by a jury or fact finder. OCGA § 9-11-56. Questions of construction of contracts, and the threshold question of whether a contract is ambiguous, are matters of law for the Court. Lee v. Mercury Ins. Co. of Ga., 343 Ga. App. 729, 754 (2017). Even where there is an ambiguity, the Court should attempt to resolve it and should only submit it to a jury where the contradiction cannot be resolved simply by applying ordinary rules of construction.  Western Contracting Corp. v. State Hwy. Dep't, 125 Ga. App. 376, 380 (1972). Where contradictions exist, the Court should attempt to construe the contract so as to uphold it "in whole and in every part." OCGA § 13-2-2(4). Where there is a apparent conflict between two portions of a contract, the Court should determine whether one of the clauses can be read as subordinated to the other in a way that resolves the conflict. Joseph Camacho Assoc. v. Millard, 169 Ga. App. 937, 938 (1984). However, genuine conflicts present a genuine issue for decision by a finder of fact. Healthy-IT, LLC v. Agrawal, 343 Ga. App. 660, 667 (2017).

Where a question of agency arises from a contract, accordingly, it is generally a question for the Court. Buchanan v. Canada Dry Corp., 138 Ga. App. 588,  (1976). However, agency may also arise from course of conduct and are properly a question for the jury to the extent not defined by a written agreement. Id.; OCGA § 10-6-1; Renfroe v. Warren-Hawkins Am. Legion Post No. 523, 157 Ga. App. 614 (1981) ("Questions regarding existence of agency and extent of agent’s authority are generally for the trier of fact.").

2. The Vicarious Liability of CFA Is a Jury Issue

Although franchisors are not per se vicariously liable for the conduct of employees of their franchisee, they also are not entirely immune from potential liability. As with any other contractual relationship, an agency may arise, either under the contract or in the course of conduct of the parties, sufficient to impute liability on the franchisor as principal for the conduct of an agent operating on its behalf. McMullan v. Georgia Girl Fashions, 180 Ga. App. 228, 230 (1986) ("[A] 'franchise agreement' does not ipso facto insulate a franchisor if the contract's contents establish an agency relationship.").

In deciding the issue of agency, the question presented is "whether the contract gives, or the [franchisor assumes], the right to control the time and manner of executing the work, as distinguished from the right merely to require results in conformity with the contract." (Id.) (quoting Buchanan v. Canada Dry Corp., 138 Ga. App. 588, 226 S.E.2d 613 (1976)). To the extent that "the question of agency...rests upon a written documents," that would be a question of law for the Court. (Id. at 229.) However, as the language from the Buchanan case suggests, agency may arise from conduct as well as from the agreement. There is in every written franchise agreement, moreover, an inherent tension between the desire of a franchisor to maintain control of the relationship and its desire to avoid liability (see id. at 230.). This contradiction may be resolved by concluding, for example, that assertions of control in a franchise agreement viewed as a whole relate simply to "quality assurance" and brand identity and are not intended to control the manner of operation of the franchise in detail or in relation to the specific subject matter of the law suit. See, e.g., Pizza K, Inc. v. Santagata 249 Ga. App. 36, 39 (2001); Baldino's Giant Jersey Subs, Inc., 216 Ga. App 467, 468 (1995). But they can never simply be resolved by looking at bare assertions of independence and disclaimers of liability in the governing agreement in isolation. OCGA § 13-2-2(4).

Moreover, because agency can also arise from conduct, some jurisdictions have approached the question whether a franchisor has in fact assumed sufficent control over a franchisee's conduct to create an agency relationship as a mixed question of law and fact apart from the agreement itself. See e.g. Clarence David Coryell v. Steven Morris, 2025 PA Super 28 (2025) (holding that agency relationship with franchisor Domino's Pizza was a mixed question of law and fact properly submitted to the jury and sufficient indicia of actual control were presented in evidence at trial to justify jury finding of agency despite express disavowals in the franchise agreement).

Here, even looking solely to the contract itself, this agreement contains broad and sweeping provisions requiring the franchisee to comply with CFA policies regarding not just brand identity and product quality but training and operations in detail. There is no limitation of the type of issues over which CFA asserts control that would suggest that it only has the right to control conduct directly relating to product quality or use of its intellectual property. Training of employees is specifically identified as subject to CFA control and was, in practice, delegated to CFA's "Pathways" program. And the content of the Pathways material, despite a single rote disavowal, is plainly intended to control the actual conduct of Humble Leaderology's operations and the manner in which its employees fulfill their duties. If one looks to material extrinsic to the contract, this included driver training.[fn][Pathways materials are being submitted to the Court for review under seal.] However, even excluding the extrinsic evidence of how this contract was actually put into effect by the parties, the contract itself is not fairly construed in a way that subordinates the clauses asserting operational control to the disclaimer of agency.

In its franchise agreement, CFA asserts sweeping authority to control the manner of operations of its franchisee while also disclaiming agency and vicarious liability. It enforces this authority in practice. The tension here, although present to some extent in any franchise relationship, is in this case irresolvable on summary judgment. The question should be submitted to a jury.

3. Direct Liability

CFA may also be directly liable for negligent training and supervision. Franchisors may be liable in direct negligence for inadequate supervision or training, but is is necessary to first establish that the franchisor had, or had assumed, a legal duty. New Star Realty, Inc. v. Jungang PRI USA, LLC, 346 Ga.App. 548, 560 (2018) ("No matter how innocent the plaintiff may be, [the plaintiff] is not entitled to recover unless the defendant did something that it should not have done, or failed to do something that it should have done pursuant to the duty owed the plaintiff.") (quoting Rasnick v. Krishna Hospitality , 302 Ga. App. 260, 263 (2010).) A franchisor may be liable under a theory of negligent supervision or training when it has a right, or assumes the right, to control the manner in which a franchisee executes its work. Id. at 563.

The issue, as with vicarious liability, can be framed in terms of control. However, one should also note that Georgia has adopted the Restatement view that "One who undertakes, gratuitously or for consideration, to render services to another which he should recognize as necessary for the protection of a third person or his things, is subject to liability to the third person for physical harm resulting from his failure to exercise reasonable care to protect his undertaking, if (a) his failure to exercise reasonable care increases the risk of such harm, or (b) he has undertaken to perform a duty owed by the other to the third person, or (c) the harm is suffered because of reliance of the other or the third person upon the undertaking." Restatement 2d Torts § 324A; Huggins v. Aetna Casualty & Surety Company, 245 Ga. 248, 249 (1980).

Here, CFA had an expansive right to control the operations of Humble Leaderology and exercised that right, inter alia, with respect to training. Having assumed responsibility for driver training, it should not be entitled to disclaim the liability attendant on that undertaking. 

C. Conclusion

The relationship between CFA and Humble Leaderology involved a significant degree of control over the day to day operation of the franchisee, and CFA assumed the particular duty of providing training material, which did not include any warning regarding the foreseeable harm of drivers eating while driving. The Court should deny CFA's motion for summary judgment and allow this matter to proceed to trial.

UNCONTESTED IN CAMERA MOTION FOR LEAVE TO FILE UNDER SEAL

COMES NOW Plaintiff Daniel Newman ("Plaintiff") and submits his Motion for Filing under Seal, showing the following:

1. Defendant Chick-fil-A ("CFA") has produced certain documents as confidential pursuant to a confidentiality agreement of the parties entered by the Court as a Protective Order on February 21, 2024.

2. Certain material so designated by CFA is relevant to CFA's Motion for Summary Judgment, specifically certain training material regarding driver safety.

3. Plaintiff submits it will assist the Court in deciding the motion.

4. Accordingly, pursuant to the Court's order and Uniform State Court Rule 21(D), this motion is submitted to the Court directly, along with the unredacted documents and a proposed order for filing under seal.

PROPOSED ORDER

The Court having considered the Uncontested In Camera Motion for Leave to File Under Seal of Plaintiff Daniel Newman and for good cause show,

IT IS NOW ORDERED, that said plaintiff's Supplemental Brief Filed Under Seal with Sealed Records Appendix is and shall be filed UNDER SEAL. The Clerk is directed to maintain this document with its exhibit as part of the record of the above captioned matter under seal.

SUPPLEMENTAL BRIEF FILED UNDER SEAL WITH SEALED RECORDS APPENDIX

COMES NOW Plaintiff Daniel Newman ("Plaintiff") and files attached hereto UNDER SEAL certain confidential documents numbered CFA0066-0111, attached as Exhibit A hereto. Regarding same, and in further opposition to Defendant Chick-fil-A's Motion for Summary Judgment (the "Motion" of "CFA"), shows the following:

1. The attached training material contains detailed instruction regarding the manner of operating a motor vehicle for delivery purposes. For example, CFA0066-70 contains instructions regarding use of seatbelts, speed of driving, safe distance, route preparation, cell phone use, mirror use, etc. Although these mostly reiterate requirements of state law, they are directed towards specific details the actual conduct of employees at their work. The referenced material also contains specific requirements about when proof of insurance documentation should be carried and when it should be surrendered to the employer, as well as a requirement to limit the amount of cash carried. (CFA 0070.)

2. This training material is supported by a driver safety evaluation checklist that includes apparently mandatory training on additional requirements such as how to park vehicles, when to lock the vehicle, use of mirrors, and, prominently, how much cash to carry. (CFA0071-75.)

3. There is a "Roles and Responsibilities" document (CFA0076-79) that includes further detailed description of how to conduct oneself as a CFA delivery driver including what equipment to use (CFA0076), how to load and unload the vehicle (CFA 0077-78), how to interact with customers and dispatch (id.), and how to check out at end of shift (CFA 0079). (See also CFA0080-88.)

4. In keeping with the well-known brand identity of CFA, there are detailed instructions as to how to interact with guests so as to convey an impression of hospitality. (CFA0089-94.) This includes, for example, a script for interacting with customers on arrival at their home and an instruction to always repeat the customer's name and apologize for any tardiness. (CFA0091-94.) The only anticipated variance from one restaurant to the next is in how detailed a confirmation of the elements of the order the driver should conduct. (CFA0092.) All this is to be reinforced by viewing a video regarding hospitality and customer interactions. (CFA 0094.)

PLAINTIFF'S STATEMENT OF MATERIAL FACTS SHOWING GENUINE ISSUES EXIST FOR TRIAL

COMES NOW the above plaintiff and submits the following Statement of Material Facts Showing Genuine Issues Exist for Trial:

x. Defendant Kurt Panton ("Panton") caused a motor vehicle collision on February 14, 2022. See generally, Complaint.

x. Panton was driving to make a food delivery, started coughing, blacked out, and collided with Plaintiff. (Deposition of Kurt Panton, transcript attached to Plaintiff's Record Appendix as Exhibit 1 thereto, ("Panton Depo.") at 23:7-18.)

x. Panton started coughing because he was eating while driving and choked on a muffin that he got from work. (Panton Depo. at 24:5-14; 32:14-16.)

x. The vehicle that Panton  was driving belonged to Humble Leaderology, LLC ("Humble Leaderology"). (Panton Depo. at 5-7.)

x. Humble Leaderology is a franchisee of Chick-fil-A, Inc. ("CFA") pursuant to a Franchise Agreement of January 1, 2015, between Benjamin Adam Rhodes and CFA, subsequently assigned to Humble Leaderology pursuant to an Assignement and Consent to Assignment agreement of January 1, 2017. See CFA's Statement of Material Facts ("SMF") at 7-8; Affidavit of Angela Pritchard ("Pritchard Aff.") attached to SMF as Exhibit 2 thereto, ¶ 4-5. A true and correct redacted copy of the Franchise Agreement is attached to the Pritchard Aff. as Exhibit A thereto and is also included in Plaintiff's Record Appendix as Exhibit 2.

x. The Franchise Agreement was in effect between CFA and Humble Leaderology on the date of the collision between Plaintiff and Panton. Prichard Aff. ¶ 6.

x. Under the Franchise Agreement, in addition to quality requirement manuals, CFA contracted to provide training and operational material to franchisees as part of a comprehensive system it has developed for the operation of its Chick-fil-A branded restaurants. (Franchise Agreement pp. 2-3 §§ 1.1(d), 1.1(o).)

x. Humble Leaderology was required under the Franchise Agreement to operate its business in "strict conformity" with the training and operations policies of CFA, which, in addition to service and product consistency requirements, cover "all other aspects of the operation of the [b]usiness." (Franchise Agreement p. 7 § 12.1(d).)

x. CFA had the right to inspect Humble Leaderology's facility to ensure complaince with all of its policies. (Franchise Agreement p. 8 § 13.1(a).)

x. Any material failure to comply with CFA's operations and training policies would be a breach of the Franchise Agreement sufficient to authorize CFA to terminate the agreement. (Franchise Agreement p. 9 § 24.1(i).)

x. The Franchise Agreement requires Humble Leaderology to hold itself out to the public as an independent contractor and disclaims any agency relationship. (CFA 0040 § 25.1.)

x. Despite the express requirement of strict conformity with training and operations policies of CFA, the Franchise agreement disclaims any agency relationship and inconsistently asserts that the terms of the agreement "are not intended to control or otherwise affect the time, manner, or method of [Humble Leaderology's] day-to-day operation." (Franchise Agreement at p, 20 § 25.2.)

x. Ben Rhodes ("Rhodes") , the owner of Humble Leaderology, has extensive experience working directly for Chik-fil-A and was chosen by them, first to run corporate-owned restaurants and then, later, to be a franchisee. (Deposition of Benjamin Rhodes, copy attached to Plaintiff's Record Appendix as Exhibit 3 thereto ("Rhodes Depo.") at 11:1-12.)

x. Rhodes took over an existing drive-thru-only restaurant to manage it as a franchise. (Rhodes Depo. at 11:12-21.)

x. Rhodes is and always has been the sole member of Humble Leaderology, LLC. (Rhodes Depo. at 13:13-20.)

x. The facility in question is the only Chick-fil-A restaurant that Mr. Rhodes operates. (Rhodes Depo. at 15:10-12).

x. Rhodes himself received an initial six weeks of formal training from Chick-fil-A and retrains every two years. (Rhodes Depo. at 16:5-8.)

x. CFA provides Rhodes with operational training material known as "Pathways," which includes driver training material. (Rhodes Depo. at 16:12-14. See also Deposition of Leroy Hooks, transcript attached to Plaintiff's Record Appendix as Exhibit 3 thereto ("Hooks Depo.") at 10:6-11:8, and Deposition of Madison Pippins, transcript attached to Plaintiff's Record Appendix as Exhibit 4 thereto ("Pippins Depo."), at 8:4-9:6.)

x. The Pathways material was developed by CFA. (Rhodes Depo. at 17:3-5.)

x. CFA regularly inspects the Humble Leaderology facility to ensure compliance with its policies, including safety policies. (Rhodes Depo. at 20:14-21:5.)

x. Humble Leaderology, LLC has no other written policy material regarding driver safety other than the Pathways material.

x. Humble Leaderology's only operational training material is provided by CFA through Pathways. (Rhodes Depo. at 17:12-15; Hooks Depo. at 13:5-8, 24:2-4.)

x. CFA regularly visits Humble Leaderology, LLC to ensure the franchise is, among other things, operating in conformance with its safety policies. (Rhodes Depo. at 20:14-24.)

x. Other than the Pathways material, Humble Leaderology provides no driver training and relies on the State of Georgia's ordinary licensing procedure, its insurer's driving history screening, and "the Chick-Fil-A protocol" to ensure driver safety. (Rhodes Depo. at 19:9-25; Panton Depo. at 20-22; Pippins 10:9-19; 15:5-16:17; 21:11-13.)

x. Humble Leaderology has no policies from its insurer or its insurance broker relating to driver training, hiring, or other driver safety issues, other than the requirement to provide a copy of the driver's license to the insurance company. (Hooks Depo. at 16:5-14; Pippins Depo. at 10:4-6.)

x. The vehicle Panton was driving at the time of the collision had Chick-fil-A branding and no signage or identification associated with Humble Leaderology. (Panton Depo. at 5-7; Hooks Depo. at 15:5-15.)

x. Panton was on the clock at the time of the collision. (Pippins Depo. at 28:2-5.)

x. Panton told Humble Leaderology that he had passed out but refused to explain why, which led them to decide not to put him on the schedule as a driver again after the incident. (Hooks Depo. at 21:4-22.)

PLAINTIFF'S RESPONSE TO DEFENDANT CHICK-FIL-A'S STATEMENT OF MATERIAL FACTS

COMES NOW the above plaintiff and responds to the individually enumerated purported material facts submitted by Defendant Chick-fil-A, Inc. ("CFA") in support of its Motion for Summary Judgment, as follows:

REQUEST FOR ORAL HEARING

COMES NOW the above plaintiff and, pursuant to Uniform State Court Rule 6.3, respectfully requests that this matter be set for oral argument on Defendant Chick-fil-A, Inc.'s Motion for Summary Judgment.

1. At the time of the alleged incident, Defendant Panton was acting in the course and scope of his employment with Humble Leaderology, LLC. See Defendant Humble Leaderology, LLC’s Response to Plaintiff’s First Request for Admissions, No. 7 (Ex. 1).
RESPONSE: Admitted for purpose of the present motion.

2. At the time of the alleged incident, Defendant Panton was acting as Humble Leaderology, LLC’s agent or otherwise acting on behalf of Humble Leaderology, LLC. See Defendant Humble Leaderology, LLC’s Response to Plaintiff’s First Request for Admissions, No. 8 (Ex. 1).
RESPONSE: Admitted for purpose of the present motion.

3. Humble Leaderology, LLC is vicariously liable for the conduct of Defendant Panton under theories of respondeat superior, lease, agency and/or “logo” or “placard” liability. 1See Defendant Humble Leaderology, LLC’s Response to Plaintiff’s First Request for Admissions, No. 9 (Ex. 1).
RESPONSE: Admitted for purpose of the present motion.

4. Humble Leaderology, LLC owned the vehicle that Defendant Panton was driving at the time of the alleged incident (the “Vehicle”). See Defendant Humble Leaderology, LLC’s Response to Plaintiff’s First Request for Admissions, No. 12 (Ex. 1).
RESPONSE: Admitted for purpose of the present motion.

5. Humble Leaderology, LLC had a duty to exercise due care in hiring, supervising, training and retaining Defendant Panton. See Defendant Humble Leaderology, LLC’s Response to Plaintiff’s First Request for Admissions, No. 10 (Ex. 1).
RESPONSE: Admitted for purpose of the present motion.

6. Humble Leaderology, LLC had a duty to exercise due care in entrusting the Vehicle to Defendant Panton. See Defendant Humble Leaderology, LLC’s Response to Plaintiff’s First Request for Admissions, No. 13 (Ex. 1).
RESPONSE: Admitted for purpose of the present motion.

7. Effective January 1, 2015, Benjamin Adam Rhodes and CFA, Inc. entered into a Franchise Agreement, pursuant to which Mr. Rhodes owned and operated the Restaurant Business as a franchisee and independent contractor of CFA, Inc. See Affidavit of Angela Pritchard (“Pritchard Aff.”) ¶ 4 (Ex. 2). 1
RESPONSE: Denied as stated. The Franchise Agreement speaks for itself but must be construed as a whole, and the question whether Rhodes as an independent contractor for purpose of liability determination is an ultimate issue here.

8. Effective January 1, 2017, Mr. Rhodes, CFA, Inc. and Humble Leaderology, LLC entered into an Assignment and Consent to Assignment Agreement, pursuant to which Mr. Rhodes assigned and transferred to Humble Leaderology, LLC all his rights, title and interests in and to the Restaurant Business, including the Franchise Agreement. See Prichard Aff. ¶ 5 (Ex. 2).
RESPONSE: Admitted for purpose of the present motion.

9. The Franchise Agreement was in full force and effect between CFA, Inc. and Humble Leaderology, LLC on the date of the alleged incident. See Prichard Aff. ¶ 6 (Ex. 2).
RESPONSE: Admitted for purpose of the present motion.

10. The Franchise Agreement defines the relationship of CFA, Inc. and Humble Leaderology, LLC as that of independent contractors:

25. FRANCHISE RELATIONSHIP
The relationship of the parties created pursuant to this Agreement
is intended by each party hereto to be and is that of a franchise
between Chick-fil-A and the Operator, who is an independent
contractor and business person, and neither party shall incur any
liability, other than as specifically set forth herein, to any person or
entity, including without limitation the other party, for any action
undertaken pursuant to or as a result of this Agreement. Nothing
herein makes or shall be deemed to make the Operator (or any
individual whose salary, wages or other compensation is to be paid
by the Operator) an agent, partner, legal representative, joint
venturer, joint employer or employee with or of Chick-fil-A. In all
public records in the Operator’s relationship with all other persons
or entities, and in any document, the Operator agrees to indicate
clearly the independent ownership and operation by the Operator of
the Businesses. The Operator shall, upon commencement of the
Operator’s duties at the Site of any Business, inform each employee
that Chick-fil-A is not such employee’s employer. The Operator
further agrees to hold itself out to the public as an independent
contractor operating the Businesses pursuant to a franchise with
Chick-fil-A.

See Franchise Agreement at ¶ 25.1 (emphasis added), attached as Ex. A to Pritchard Aff. (Ex. 2).
RESPONSE: Denied as stated. The Franchise Agreement speaks for itself but must be construed as a whole, and the question whether Rhodes as an independent contractor for purpose of liability determination is an ultimate issue here.

11. The Franchise Agreement describes in detail the specific aspects of the relationship between CFA, Inc. and its franchisees, as well as the responsibilities of each party to the Franchise Agreement. See Franchise Agreement, generally.
RESPONSE: Admitted for purpose of the present motion.

12. As described in the Franchise Agreement, CFA, Inc. sets certain “Minimum Standards” for the operation of Chick-fil-A-branded restaurant businesses. These Minimum Standards require franchisees to achieve and uphold certain levels and specifications of product quality, cleanliness, sanitation, and operation. See Franchise Agreement at ¶ 1(j), attached as Ex. 3A to Pritchard Aff. (Ex. 2). Food products must be prepared in accordance with the methods specified by CFA, Inc. See Franchise Agreement, ¶ 1(i). To protect the public image of and goodwill associated with CFA, Inc.’s trademarks, franchisees are required to open and operate their restaurant businesses six days each week, excluding Sundays. Id. at ¶12.1(b). Additionally, CFA, Inc. may inspect the Restaurant Business at any time to ensure compliance with the Minimum Standards. Id. at ¶ 13.1 These standards and requirements are vital to protect CFA, Inc.’s trademarks and the goodwill associated with those marks, the high quality of Chick-fil-A products, and the sanitation of Chick-fil-A branded restaurant businesses. Id. at ¶ 12.1(d)
RESPONSE: Denied as stated. The Franchise Agreement speaks for itself but must be construed as a whole.

13. Humble Leaderology, LLC agreed to operate the Restaurant Business in compliance with CFA, Inc.’s Minimum Standards to maintain the high quality of Chick-fil-A products and to protect CFA, Inc.’s trademarks and the goodwill associated with those trademarks. See Franchise Agreement at ¶ 12.1(d), attached as Ex. A to Pritchard Aff. (Ex. 2).
RESPONSE: Denied as stated. The Franchise Agreement speaks for itself but must be construed as a whole.


14. The Franchise Agreement confirms that the quality guidelines established by CFA, Inc. are not intended to control the time, manner, or method of the Restaurant Business’s daily operations:

The Operator and Chick-fil-A acknowledge that any restrictions
imposed upon the Operator by this Agreement are not intended to
control or otherwise affect the time, manner or method of the
Operator’s day-to-day operation of the Businesses but rather to
ensure that: (i) the image of the Businesses, as ultimately seen and
judged by its customers, is as positive as possible and therefore such
that the Businesses can be operated for the greatest mutual benefit
of the Operator and Chick-fil-A; (ii) the Trade Secrets, the
Confidential Information and other proprietary rights of Chick-fil-A
and CFA Properties are adequately protected; and (iii) all Minimum
Standards are maintained.

Franchise Agreement at ¶ 25.2 (emphasis added).
RESPONSE: Denied as stated. The Franchise Agreement speaks for itself but must be construed as a whole.

15. The guidelines set forth in the Franchise Agreement are intended to promote a level of quality and uniformity among Chick-fil-A-branded restaurant businesses. See Franchise Agreement at ¶ 12.1.
RESPONSE: Denied as stated. The Franchise Agreement speaks for itself but must be construed as a whole.

16. As the franchisee, owner and operator of the Restaurant Business, Humble Leaderology, LLC was solely responsible for the day-to-day operations and management of the Restaurant Business on the date of Plaintiff’s alleged incident. See Franchise Agreement at ¶¶ 25.1, 25.2 (Ex. 2); CFA, Inc.’s Answers and Objections to Plaintiff’s First Interrogatories, No. 1 and 9 (Ex. 3). Humble Leaderology LLC. has the right and license to use CFA, Inc.’s trademarks in connection with the operation and promotion of the Restaurant Business. See Franchise Agreement at ¶¶ 12.1(e), 19.1.
RESPONSE: Denied as stated. The Franchise Agreement speaks for itself but must be construed as a whole.

17. The individuals who worked at the Restaurant Business at the time of the alleged incident – including Defendant Panton – were employed by Humble Leaderology, LLC, not CFA, Inc. See CFA, Inc.’s Answers and Objections to Plaintiff’s First Interrogatories, No. 1 and 9 (Ex. 3); Franchise Agreement ¶¶ 12.1(f), 25.1, Ex. A to Pritchard Aff. (Ex. 2); Defendant Humble Leaderology, LLC’s Response to Plaintiff’s First Request for Admissions, No. 7 (Ex. 1).
RESPONSE: Denied as stated. The Franchise Agreement speaks for itself but must be construed as a whole.

18. Humble Leaderology, LLC is solely responsible for hiring, training and supervising its employees. See Franchise Agreement ¶¶ 12.1(f), 25.1; Defendant Humble Leaderology, LLC’s Response to Plaintiff’s First Request for Admissions, No. 10 (Ex. 1).
RESPONSE: Denied as stated. The Franchise Agreement speaks for itself but must be construed as a whole.

19. The employees of the Restaurant Business are the “sole and exclusive responsibility” of Humble Leaderology, LLC. See Franchise Agreement ¶ 12.1(f).
RESPONSE: Denied as stated. The Franchise Agreement speaks for itself but must be construed as a whole.
