#+title:      wallace
#+date:       [2025-02-27 Thu 11:44]
#+filetags:   :casenotes:
#+identifier: 20250227T114435

Sherry Wallace,

Plaintiff,

v.

Grady Memorial Hospital Corporation d/b/a Grady Memorial Hospital,

Defendant.

COMPLAINT
JURY TRIAL DEMANDED

x. Plaintiff is a citizen of the State of Georgia submitting herself hereby to the jurisdiction and venue of this Court, and she may be served in relation to this action pursuant to OCGA § 9-11-5 by her undersigned attorney.

x. The Fulton-DeKalb Hospital Authority (“FDHA”) is a public body, corporate and politic, created by the General Assembly of the State of Georgia under the Hospital Authorities Law, originally set forth in Georgia Laws 1941, p. 24-1 et. seq., as amended, and now in O.C.G.A. § 31-7-70 et. seq., as amended, (the “Hospital Authorities Law”) and activated by like resolutions of Fulton and DeKalb Counties. FDHA oversees the operation of the Grady Health System as part of its mandate.

x. In 2007, a coalition of state and community leaders establised the Grady Memorial Hospital Corporation to handle the day to day administration of the Grady Health System. Grady Memorial Hospital Corporation d/b/a Grady Health System ("Grady") is a Georgia nonprofit corporation with its principal office at 80 Jesse Hill Jr. Drive, SE, P.O. Box 26145, Atlanta, Fulton County, Georgia, 30303. It may be served with summons and process by its registered agent, Timothy Jefferson, at that address.

x. The state court has jurisdiction of this action for money damages for a personal injury.

x. Venue is proper in Fulton County, Georgia The tortious conduct alleged herein occurred in Fulton County, Georgia. Pursuant to OCGA § 14-3-510(b)(1) and (3), venue in this action is proper in Fulton County, Georgia, in that this county is the place where the cause of action arose and the principal place of business and registered office of the non-profit entity defendant.

Facts Common to All Counts

x. Grady operate a hospital located at 80 Jessie Hill Jr. Drive, Atlanta, Fulton County, Georgia 30303.

x. On September 27, 2024, Shamon Pearce was observed in the hospital in the elevators smoking cocaine.

x. Pearce proceeded to the seventh floor of the hospital. Staff on the floor were aware that he represented a cause for concern but did not prevent him from entering the room of Sherry Wallace, a patient at the facility.

x. Pearce sexually assaulted Wallace, a stroke victim.

x. Wallace had seen Pearce in the hospital on prior occasions.

x. Pearce was subesequently arrested and charged with aggravated assault wiht intent to rape, sexual battery, and battery.

x. As a direct and proximate consequence of Pearce's conduct, which involved actual physical contact, Wallace suffered personal injury for which she should be entitled to recover both special and general damages.

COUNT I - NEGLIGENCE

x. On information and belief, and at all times material hereto, Grady owned, operated, and controlled the premises where the incident described above occurred (the “Premises”).

x. Wallace was Grady’s invitee and lawfully on the Premises by Grady’s invitation.

x. Grady, through its employees or agents, negligently permitted Pearce enter, remain on, and attack people on the Premises.

x. Grady also provided insufficient security staff and and negligently trained its staff in responding to incidents like the one alleged herein.

x. Grady failed to implement adequate security measures to prevent individuals like the Pearce from engaging in tortious conduct on the Premises.

x. Grady had a duty to provide security policies and procedures for the protection of their invitees, like Wallace.

x. Grady failed to provide adequate security policies and/or security procedures and staff for the protection of invitees, like Wallace, which constituted a breach of duty and negligence.

x. Grady had a duty to exercise ordinary care in the hiring, supervision, training, and retention of its employees.

x. Grady breached that duty of care by failing properly to hire, supervise, train, or retain its employees in their duties respecting patient safety and the prevention of assaults.

x. Grady had a duty to patrol and secure the Premises and failed to do so, despite knowledge of the hazard to patients and staff posed by Pearce, which failure constituted a breach of duty and negligence.

x. As a direct and proximate consequence of Grady’s negligence, Wallace suffered a personal injury for which she should be entitled to recover damages including past and future medical expenses in the amount of at least $XXX.00, which continue to accrue, and general damages for her pain, suffering, and emotional distress in an amount to be determined at trial.

x. Grady also is vicariously liable for the negligent conduct of its employees relevant to this action.

COUNT II – PREMISES LIABILITY

x. Grady has a statutory duty under OCGA § 51-3-1 to exercise reasonable care to keep its premises and approaches safe for invitees such as Wallace.

x. Grady breached said statutory duty as described above.

x. Specifically, but without limitation, Defendant failed to take appropriate action to remedy or reduce the danger to their invitees and allowed the dangerous environment on the Premises to continue to exist unabated.

x. As a direct and proximate consequence of Grady’s negligence, Wallace suffered a personal injury for which she should be entitled to recover damages including past and future medical expenses and general damages for her pain, suffering, and emotional distress in an amount to be determined at trial.

COUNT III - PUNITIVE DAMAGES

x. Defendant acted with willful misconduct, malice, fraud, oppression, wantonness, and an entire want of care raising the presumption of a conscience indifference to the consequences. Accordingly, Plaintiff is entitled to recover punitive damages from Defendant, in accordance with the enlightened conscience of an impartial jury, pursuant to O.C.G.A. § 51-12-5.1.

WHEREFORE, Plaintiff prays that summons issue and be served with the foregoing complaint as provided by law, that discovery be had, that the matter be tried to a jury and judgment be awarded to Plaintiff and against the Defendant, with the costs of the action cast against said Defendant.
